### ISSUE TITLE
LG phone Android 10 arm64-v8a

### ISSUE THREAD

**Issue by man4567890** [DeviceFarmer/stf#124]
Confirm that this problem is solved or not please
Vector<> have different types (this=0x7fcc7b3280, rhs=0x7fcc7b33d0)"

List of devices attached                                                                     
LMK920TMef2ec11c       device usb:1-1.1.3 product:acexlm model:LM_K920 device:acexlm         

Opening the UI I get this and then your phone has been stolen

2020-10-06T06:45:22.458Z INF/device:plugins:group 4248 [LMK920TMef2ec11c] Subscribing to group channel "27wYow6vQ7KHx53MvmzFQw=="
2020-10-06T06:45:23.561Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Setting frame producer projection to 865x864
2020-10-06T06:45:23.562Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Requesting frame producer to start
2020-10-06T06:45:23.563Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Launching screen service
2020-10-06T06:45:23.641Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "PID: 1737"
2020-10-06T06:45:23.642Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: Using projection 1080x2400@389x864/0"
2020-10-06T06:45:23.642Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:241) Creating SurfaceComposerClient"
2020-10-06T06:45:23.643Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Connecting to minicap service
2020-10-06T06:45:23.647Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:244) Performing SurfaceComposerClient init check"
2020-10-06T06:45:23.649Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:255) Creating virtual display"
2020-10-06T06:45:23.655Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:261) Creating buffer queue"
2020-10-06T06:45:23.657Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:264) Setting buffer options"
2020-10-06T06:45:23.658Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:268) Creating CPU consumer"
2020-10-06T06:45:23.660Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:272) Creating frame waiter"
2020-10-06T06:45:23.661Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:276) Publishing virtual display"
2020-10-06T06:45:23.662Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] minicap says: "Vector<> have different types (this=0x7fcc7b3280, rhs=0x7fcc7b33d0)"
2020-10-06T06:45:23.754Z WRN/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Shell keeping minicap running ended unexpectedly
2020-10-06T06:45:25.524Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Disconnecting from minicap service
2020-10-06T06:45:25.526Z INF/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Stopping minicap service
2020-10-06T06:45:25.527Z FTL/device:plugins:screen:stream 4248 [LMK920TMef2ec11c] Frame producer had an error FailError: Failure: 'closed'
    at /usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/parser.js:183:29
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2020-10-06T06:45:25.528Z FTL/util:lifecycle 4248 [LMK920TMef2ec11c] Shutting down due to fatal error
2020-10-06T06:45:25.556Z INF/provider 23167 [*] Cleaning up device worker "LMK920TMef2ec11c"
2020-10-06T06:45:25.557Z ERR/provider 23167 [*] Device worker "LMK920TMef2ec11c" died with code 1
2020-10-06T06:45:25.557Z INF/provider 23167 [*] Restarting device worker "LMK920TMef2ec11c"
2020-10-06T06:45:26.602Z INF/device:support:push 7385 [LMK920TMef2ec11c] Sending output to "tcp://127.0.0.1:7116"
2020-10-06T06:45:26.608Z INF/device 7385 [LMK920TMef2ec11c] Preparing device
2020-10-06T06:45:27.643Z INF/device:support:sub 7385 [LMK920TMef2ec11c] Receiving input from "tcp://127.0.0.1:7114"
2020-10-06T06:45:27.646Z INF/device:support:sub 7385 [LMK920TMef2ec11c] Subscribing to permanent channel "*ALL"
2020-10-06T06:45:27.746Z INF/device:support:properties 7385 [LMK920TMef2ec11c] Loading properties
2020-10-06T06:45:27.838Z INF/device:support:sdk 7385 [LMK920TMef2ec11c] Supports SDK 29
2020-10-06T06:45:27.840Z INF/device:support:abi 7385 [LMK920TMef2ec11c] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2020-10-06T06:45:28.084Z INF/device:resources:minicap 7385 [LMK920TMef2ec11c] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2020-10-06T06:45:28.085Z INF/device:resources:minicap 7385 [LMK920TMef2ec11c] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-29/minicap.so" as "/data/local/tmp/minicap.so"
2020-10-06T06:45:28.402Z INF/device:resources:service 7385 [LMK920TMef2ec11c] Checking whether we need to install STFService
2020-10-06T06:45:28.486Z INF/device:resources:service 7385 [LMK920TMef2ec11c] Running version check
2020-10-06T06:45:28.866Z INF/device:resources:service 7385 [LMK920TMef2ec11c] Installing STFService
2020-10-06T06:45:31.452Z INF/device:resources:service 7385 [LMK920TMef2ec11c] STFService up to date
2020-10-06T06:45:31.458Z INF/device:plugins:service 7385 [LMK920TMef2ec11c] Launching agent
2020-10-06T06:45:32.168Z INF/device:plugins:service 7385 [LMK920TMef2ec11c] Agent says: "Starting minitouch agent"
2020-10-06T06:45:32.169Z INF/device:plugins:service 7385 [LMK920TMef2ec11c] Agent says: "Listening on @stfagent"
2020-10-06T06:45:32.232Z INF/device:plugins:service 7385 [LMK920TMef2ec11c] Launching service
2020-10-06T06:45:32.233Z INF/device:plugins:service 7385 [LMK920TMef2ec11c] using 'start-foreground-service' command for API 29
2020-10-06T06:45:32.237Z INF/device:plugins:service 7385 [LMK920TMef2ec11c] Agent says: "InputClient started"
2020-10-06T06:45:32.414Z INF/device:plugins:display 7385 [LMK920TMef2ec11c] Reading display info
2020-10-06T06:45:32.491Z INF/device:plugins:phone 7385 [LMK920TMef2ec11c] Fetching phone info
2020-10-06T06:45:32.571Z INF/device:plugins:identity 7385 [LMK920TMef2ec11c] Solving identity
2020-10-06T06:45:32.577Z INF/device:plugins:solo 7385 [LMK920TMef2ec11c] Subscribing to permanent channel "wz4oakJcAfWJVyJ8BYbxk/6jqns="
2020-10-06T06:45:32.579Z INF/device:plugins:screen:stream 7385 [LMK920TMef2ec11c] Starting WebSocket server on port 7528
2020-10-06T06:45:32.805Z INF/device:resources:minitouch 7385 [LMK920TMef2ec11c] Installing "/usr/lib/node_modules/stf/node_modules/minitouch-prebuilt-beta/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
2020-10-06T06:45:33.003Z WRN/device:plugins:data 7385 [LMK920TMef2ec11c] Unable to find device data { serial: 'LMK920TMef2ec11c',
  platform: 'Android',
  manufacturer: 'LGE',
  operator: **********',
  model: 'LM-K920',
  version: '10',
  abi: 'arm64-v8a',
  sdk: '29',
  product: 'acexlm',
  cpuPlatform: 'lito',
  openGLESVersion: '3.2',
  marketName: 'acexlm',
  display: 
   { id: 0,
     width: 1080,
     height: 2400,
     xdpi: 397.56500244140625,
     ydpi: 395.843994140625,
     fps: 60.000003814697266,
     density: 2.625,
     rotation: 0,
     secure: true,
     size: 6.643754683286824,
     url: '*******' },
  phone: { network: 'UNKNOWN' } }
2020-10-06T06:45:33.008Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] Touch origin is top left
2020-10-06T06:45:33.009Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] Requesting touch consumer to start
2020-10-06T06:45:33.010Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] Launching touch service
2020-10-06T06:45:33.031Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] Connecting to minitouch service
2020-10-06T06:45:33.089Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "open: Permission denied"
2020-10-06T06:45:33.090Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/event6 for inspectionopen: Permission denied"
2020-10-06T06:45:33.090Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/event5 for inspectionopen: Permission denied"
2020-10-06T06:45:33.091Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2020-10-06T06:45:33.091Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/event4 for inspectionopen: Permission denied"
2020-10-06T06:45:33.091Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2020-10-06T06:45:33.092Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/mice for inspectionopen: Permission denied"
2020-10-06T06:45:33.092Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/event1 for inspectionopen: Permission denied"
2020-10-06T06:45:33.092Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Unable to open device /dev/input/event3 for inspectionUnable to find a suitable touch device"
2020-10-06T06:45:33.093Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "using Android InputManager"
2020-10-06T06:45:33.163Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] Reading minitouch banner
2020-10-06T06:45:33.206Z INF/device:plugins:touch 7385 [LMK920TMef2ec11c] minitouch says: "Connection established"
2020-10-06T06:45:33.212Z INF/device:plugins:vnc 7385 [LMK920TMef2ec11c] Starting VNC server on port 7530
2020-10-06T06:45:33.214Z INF/device:plugins:browser 7385 [LMK920TMef2ec11c] Loading browser list
2020-10-06T06:45:33.236Z INF/device:plugins:browser 7385 [LMK920TMef2ec11c] Updating browser list
2020-10-06T06:45:33.239Z INF/device:plugins:mute 7385 [LMK920TMef2ec11c] Will not mute master volume
2020-10-06T06:45:33.401Z INF/device:resources:minirev 7385 [LMK920TMef2ec11c] Installing "/usr/lib/node_modules/stf/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
2020-10-06T06:45:33.601Z INF/device:plugins:forward 7385 [LMK920TMef2ec11c] Launching reverse port forwarding service
2020-10-06T06:45:33.622Z INF/device:plugins:forward 7385 [LMK920TMef2ec11c] Connecting to reverse port forwarding service
2020-10-06T06:45:33.760Z INF/device 7385 [LMK920TMef2ec11c] Fully operational

stf doctor
2020-10-06T07:01:17.627Z INF/cli:doctor 17539 [*] OS Arch: x64
2020-10-06T07:01:17.630Z INF/cli:doctor 17539 [*] OS Platform: linux
2020-10-06T07:01:17.631Z INF/cli:doctor 17539 [*] OS Platform: 3.10.0-1062.9.1.el7.x86_64
2020-10-06T07:01:17.631Z INF/cli:doctor 17539 [*] Using Node 8.15.0
2020-10-06T07:01:17.681Z INF/cli:doctor 17539 [*] Using ZeroMQ 4.1.4
2020-10-06T07:01:17.708Z ERR/cli:doctor 17539 [*] ProtoBuf is not installed (`protoc` is missing)
2020-10-06T07:01:17.709Z INF/cli:doctor 17539 [*] Using ADB 1.0.31
2020-10-06T07:01:17.741Z INF/cli:doctor 17539 [*] Using RethinkDB 2.3.6
2020-10-06T07:01:17.769Z INF/cli:doctor 17539 [*] Using GraphicsMagick 1.3.32

**Comment by man4567890** [comment]
👍

**Comment by pcrepieux** [comment]
Unfortunately it is not. This is the same issue as reported in DeviceFarmer/minicap#2 and also https://github.com/openstf/minicap/issues/169
We are working on an alternative implementation to get rid of this issue.

**Comment by man4567890** [comment]
Thanks so much @pcrepieux

**Comment by varundtsfi** [comment]
> Unfortunately it is not. This is the same issue as reported in [DeviceFarmer/minicap#2](https://github.com/DeviceFarmer/minicap/issues/2) and also [openstf/minicap#169](https://github.com/openstf/minicap/issues/169)
> We are working on an alternative implementation to get rid of this issue.

Hi @pcrepieux and @man4567890 . 
For LG Android Version 10 to get rid of vector issue. you can use the following binaries.
 
https://github.com/varundtsfi/Xiaomi_Vector_issue/tree/main/LG
If you have any issue just let us know.
