### ISSUE TITLE
Xiaomi Note 9 Pro, impossible to see screen

### ISSUE THREAD

**Issue by nicodeur** [DeviceFarmer/stf#126]
**What is the issue or idea you have?**
Impossible to use Xiaomi Note 9 Pro on STF latest (I have docker pull today)

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Yes
```
ae223d4                device usb:3-2.3.4.4.1.4 product:joyeuse_eea model:Redmi_Note_9_Pro device:joyeuse transport_id:13187
```

**Please provide the steps to reproduce the issue.**
Plug a Xiaomi Note 9 Pro on STF. Test to use it. A green screen is displayed

![image](https://user-images.githubusercontent.com/6707556/95309865-f5aa7f00-088b-11eb-9ec3-5da5fa09d663.png)

**What is the expected behavior?**
I can used the phone screen on STF.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

```
1              | 2020-10-07T08:50:48.814Z INF/device:plugins:display 3670 [ae223d4] Reading display info
stf-local_1              | 2020-10-07T08:50:48.868Z INF/device:plugins:phone 3670 [ae223d4] Fetching phone info
stf-local_1              | 2020-10-07T08:50:48.890Z INF/device:plugins:identity 3670 [ae223d4] Solving identity
stf-local_1              | 2020-10-07T08:50:48.896Z INF/device:plugins:solo 3670 [ae223d4] Subscribing to permanent channel "ysGE+35oxbQxUYgsUYRHBtC6+s8="
stf-local_1              | 2020-10-07T08:50:48.899Z INF/device:plugins:screen:stream 3670 [ae223d4] Starting WebSocket server on port 7708
stf-local_1              | Wed, 07 Oct 2020 08:50:48 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:48 GMT adb:command Send '0014shell:ps 2>/dev/null'
stf-local_1              | Wed, 07 Oct 2020 08:50:48 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:48 GMT adb:command Send '0019shell:ps -lef 2>/dev/null'
stf-local_1              | 2020-10-07T08:50:49.014Z INF/device:resources:minitouch 3670 [ae223d4] Installing "/app/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '002Bshell:'rm' '-f' '/data/local/tmp/minitouch''
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0005sync:'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:sync SEND /data/local/tmp/minitouch,33261
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:sync DONE
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0005sync:'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:sync STAT /data/local/tmp/minitouch
stf-local_1              | 2020-10-07T08:50:49.077Z WRN/device:plugins:data 3670 [ae223d4] Unable to find device data { serial: 'ae223d4',
stf-local_1              |   platform: 'Android',
stf-local_1              |   manufacturer: 'XIAOMI',
stf-local_1              |   operator: null,
stf-local_1              |   model: ' Note 9 Pro',
stf-local_1              |   version: '10',
stf-local_1              |   abi: 'arm64-v8a',
stf-local_1              |   sdk: '29',
stf-local_1              |   product: 'joyeuse_eea',
stf-local_1              |   cpuPlatform: 'atoll',
stf-local_1              |   openGLESVersion: '3.2',
stf-local_1              |   marketName: 'Redmi Note 9 Pro',
stf-local_1              |   display: 
stf-local_1              |    { id: 0,
stf-local_1              |      width: 1080,
stf-local_1              |      height: 2400,
stf-local_1              |      xdpi: 397.56500244140625,
stf-local_1              |      ydpi: 395.843994140625,
stf-local_1              |      fps: 60.000003814697266,
stf-local_1              |      density: 2.75,
stf-local_1              |      rotation: 0,
stf-local_1              |      secure: true,
stf-local_1              |      size: 6.643754683286824,
stf-local_1              |      url: 'ws://10.110.151.129:7708' },
stf-local_1              |   phone: { network: 'UNKNOWN' } }
stf-local_1              | 2020-10-07T08:50:49.081Z INF/device:plugins:touch 3670 [ae223d4] Touch origin is top left
stf-local_1              | 2020-10-07T08:50:49.081Z INF/device:plugins:touch 3670 [ae223d4] Requesting touch consumer to start
stf-local_1              | 2020-10-07T08:50:49.081Z INF/device:plugins:touch 3670 [ae223d4] Launching touch service
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0024shell:exec /data/local/tmp/minitouch'
stf-local_1              | 2020-10-07T08:50:49.095Z INF/device:plugins:touch 3670 [ae223d4] Connecting to minitouch service
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0017localabstract:minitouch'
stf-local_1              | 2020-10-07T08:50:49.136Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "open: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.136Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event9 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.136Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event8 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.137Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event7 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.137Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event6 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.137Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.138Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event5 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.138Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event3 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.139Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event1 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.139Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
stf-local_1              | 2020-10-07T08:50:49.140Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Unable to open device /dev/input/event4 for inspectionUnable to find a suitable touch device"
stf-local_1              | 2020-10-07T08:50:49.140Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "using Android InputManager"
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0017localabstract:minitouch'
stf-local_1              | 2020-10-07T08:50:49.205Z INF/device:plugins:touch 3670 [ae223d4] Reading minitouch banner
stf-local_1              | 2020-10-07T08:50:49.205Z INF/device:plugins:touch 3670 [ae223d4] minitouch says: "Connection established"
stf-local_1              | 2020-10-07T08:50:49.249Z INF/device:plugins:vnc 3670 [ae223d4] Starting VNC server on port 7710
stf-local_1              | 2020-10-07T08:50:49.251Z INF/device:plugins:browser 3670 [ae223d4] Loading browser list
stf-local_1              | 2020-10-07T08:50:49.266Z INF/device:plugins:browser 3670 [ae223d4] Updating browser list
stf-local_1              | 2020-10-07T08:50:49.267Z INF/device:plugins:mute 3670 [ae223d4] Will not mute master volume
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0014shell:ps 2>/dev/null'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0019shell:ps -lef 2>/dev/null'
stf-local_1              | 2020-10-07T08:50:49.371Z INF/device:resources:minirev 3670 [ae223d4] Installing "/app/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0029shell:'rm' '-f' '/data/local/tmp/minirev''
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0005sync:'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:sync SEND /data/local/tmp/minirev,33261
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:sync DONE
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0005sync:'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:sync STAT /data/local/tmp/minirev
stf-local_1              | 2020-10-07T08:50:49.414Z INF/device:plugins:forward 3670 [ae223d4] Launching reverse port forwarding service
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0026shell:'exec' '/data/local/tmp/minirev''
stf-local_1              | 2020-10-07T08:50:49.426Z INF/device:plugins:forward 3670 [ae223d4] Connecting to reverse port forwarding service
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0016host:transport:ae223d4'
stf-local_1              | Wed, 07 Oct 2020 08:50:49 GMT adb:command Send '0015localabstract:minirev'
stf-local_1              | 2020-10-07T08:50:49.461Z FTL/device 3657 [183568d10304] Setup had an error Error: Service had an error: "Error: Not found; no service started."
stf-local_1              |     at /app/lib/units/device/plugins/service.js:104:23
stf-local_1              | From previous event:
stf-local_1              |     at /app/lib/units/device/plugins/service.js:79:14
stf-local_1              |     at runCallback (timers.js:789:20)
stf-local_1              |     at tryOnImmediate (timers.js:751:5)
stf-local_1              |     at processImmediate [as _immediateCallback] (timers.js:722:5)
stf-local_1              | 2020-10-07T08:50:49.461Z FTL/util:lifecycle 3657 [183568d10304] Shutting down due to fatal error
stf-local_1              | 2020-10-07T08:50:49.469Z INF/provider 46 [*] Cleaning up device worker "183568d10304"
stf-local_1              | 2020-10-07T08:50:49.469Z ERR/provider 46 [*] Device worker "183568d10304" died with code 1
stf-local_1              | 2020-10-07T08:50:49.469Z INF/provider 46 [*] Restarting device worker "183568d10304"
```

**Comment by goldcome** [comment]
The same problem on XiaoMi Note3 Android9

**Comment by Chadarr** [comment]
Same problem for a multitude of Xiaomi devices with MIUI
Would be awesome, if anyone from the dev team could provide problem status

**Comment by dimakozin** [comment]
Same problem for a Redmi Note 10 Pro

When I open page for device I got stacktrace
Tried to open /data/system by adb shell - Permission denied
But tried to open directory on another device - permission denied too, but I got screen and no errors

```
minicap says: "java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)"
minicap says: "    at libcore.io.IoBridge.open(IoBridge.java:492)"
 minicap says: "    at java.io.FileInputStream.<init>(FileInputStream.java:160)"
 minicap says: "    at java.io.FileInputStream.<init>(FileInputStream.java:115)"
 minicap says: "    at java.io.FileReader.<init>(FileReader.java:58)"
 minicap says: "    at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)"
 minicap says: "    at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)"
 minicap says: "    at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)"
 minicap says: "    at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)"
 minicap says: "    at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)"
 minicap says: "    at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)"
 minicap says: "    at android.content.res.Resources.<init>(Resources.java:353)"
 minicap says: "    at android.content.res.MiuiResources.<init>(MiuiResources.java:49)"
 minicap says: "    at android.content.res.Resources.getSystem(Resources.java:233)"
 minicap says: "    at miui.util.HardwareInfo.<clinit>(HardwareInfo.java:59)"
 minicap says: "    at java.lang.Class.classForName(Native Method)"
 minicap says: "    at java.lang.Class.forName(Class.java:454)"
 minicap says: "    at java.lang.Class.forName(Class.java:379)"
 minicap says: "    at miui.os.Build.getTotalPhysicalRam(Build.java:459)"
 minicap says: "    at miui.os.Build.<clinit>(Build.java:279)"
 minicap says: "    at android.os.storage.StorageManager.getVolumeList(StorageManager.java:1376)"
 minicap says: "    at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:160)"
 minicap says: "    at android.os.Environment.getExternalStorageState(Environment.java:1143)"
 minicap says: "    at ch.qos.logback.core.android.AndroidContextUtil.getMountedExternalStorageDirectoryPath(Unknown Source:0)"
 minicap says: "    at ch.qos.logback.core.android.AndroidContextUtil.setupProperties(Unknown Source:14)"
 minicap says: "    at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source:12)"
 minicap says: "    at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source:7)"
 minicap says: "    at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source:20)"
 minicap says: "    at org.slf4j.impl.StaticLoggerBinder.getSingleton(Unknown Source:0)"
 minicap says: "    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)"
 minicap says: "    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)"
 minicap says: "    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)"
 minicap says: "    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)"
 minicap says: "    at io.devicefarmer.minicap.provider.BaseProvider.<clinit>(BaseProvider.kt:44)"
 minicap says: "    at io.devicefarmer.minicap.Main$Companion.main(Main.kt:62)"
 minicap says: "    at io.devicefarmer.minicap.Main.main(Unknown Source:2)"
 minicap says: "    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)"
 minicap says: "    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:483)"
 minicap says: "Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)"
 minicap says: "    at libcore.io.Linux.open(Native Method)"
 minicap says: "    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)"
 minicap says: "    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)"
 minicap says: "    at libcore.io.IoBridge.open(IoBridge.java:478)"
 minicap says: "    ... 36 more"
 Requesting frame producer to stop
 minicap says: "23:53:37.523 [main] INFO  BaseProvider - framePeriodMs: 0"
 minicap says: "PID: 12658"
 minicap says: "INFO: 1080x2400@535x1188/0"
 minicap says: "23:53:37.526 [main] INFO  Main - Listening on socket : minicap"
 Connecting to minicap service
 Reading minicap banner
 Disconnecting from minicap service
 Stopping minicap service
 Sending SIGTERM to minicap
 minicap says: "Terminated "

```

**Comment by denis99999** [comment]
@dimakozin , did you well create a XIAOMI account and insert a SIM card ? You have also to enable "debug USB" and "install via USB" in developer options.
