### ISSUE TITLE
A device OPPO_R9s_Plus is in a status of 'preparing' forever from a STF app

### ISSUE THREAD

**Issue by jay0129** [DeviceFarmer/stf#145]
Yes

**What is the issue or idea you have?**
- Connect `OPPO_R9s_Plus` device to STF provider
- The device is attached to `adb` unit and I can control it using adb, but the `status` of the device in the STF UI is `preparing` and I cannot use it from the STF app

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
`99292447` is the subject device
```
72V7N16607005229       device usb:1-3.3 product:VNS-L22 model:HUAWEI_VNS_L22 device:HWVNS-H transport_id:2
99292447               device usb:1-3.1.4 product:R9sPlus model:OPPO_R9s_Plus device:R9sPlus transport_id:3
BH903Z8VB5             device usb:1-1.1 product:SO-02K model:SO_02K device:SO-02K transport_id:6
F5AZFG04S191           device usb:1-3.1.3 product:JP_Z00A model:ASUS_Z00AD device:Z00A transport_id:4
FA72A1701109           device usb:1-1.4 product:ocedugl_00708 model:HTC_U_Ultra device:htc_ocedugl transport_id:5
J7R0220309000125       device usb:1-3.4 product:LIO-N29 model:LIO_N29 device:HWLIO transport_id:8
QV7100LK3E             device usb:1-3.1.2 product:SOG01_jp_kdi model:SOG01 device:SOG01 transport_id:1
ZX1G42265V             offline usb:1-3.2 transport_id:7
```

**Please provide the steps to reproduce the issue.**
- Connect `OPPO_R9s_Plus` device to STF provider
- Go to STF app site

**What is the expected behavior?**
OPPO_R9s_Plus should be available from the STF app

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
No

**Please run `stf doctor` and paste the output here.**
On a master side:
```
2020-11-22T06:05:47.124Z INF/cli:doctor 20 [*] OS Arch: x64
2020-11-22T06:05:47.125Z INF/cli:doctor 20 [*] OS Platform: linux
2020-11-22T06:05:47.125Z INF/cli:doctor 20 [*] OS Platform: 5.4.0-52-generic
2020-11-22T06:05:47.126Z INF/cli:doctor 20 [*] Using Node 8.9.3
2020-11-22T06:05:47.136Z INF/cli:doctor 20 [*] Using ZeroMQ 4.1.4
2020-11-22T06:05:47.145Z ERR/cli:doctor 20 [*] RethinkDB is not installed (`rethinkdb` is missing)
2020-11-22T06:05:47.146Z ERR/cli:doctor 20 [*] ProtoBuf is not installed (`protoc` is missing)
2020-11-22T06:05:47.146Z ERR/cli:doctor 20 [*] ADB is not installed (`adb` is missing)
2020-11-22T06:05:47.146Z INF/cli:doctor 20 [*] Using GraphicsMagick 1.3.23
```
On a provider side:
```
2020-11-22T06:04:37.602Z INF/cli:doctor 238 [*] OS Arch: x64
2020-11-22T06:04:37.603Z INF/cli:doctor 238 [*] OS Platform: linux
2020-11-22T06:04:37.604Z INF/cli:doctor 238 [*] OS Platform: 5.4.0-52-generic
2020-11-22T06:04:37.604Z INF/cli:doctor 238 [*] Using Node 8.9.3
2020-11-22T06:04:37.644Z INF/cli:doctor 238 [*] Using ZeroMQ 4.1.4
2020-11-22T06:04:37.656Z ERR/cli:doctor 238 [*] RethinkDB is not installed (`rethinkdb` is missing)
2020-11-22T06:04:37.656Z ERR/cli:doctor 238 [*] ProtoBuf is not installed (`protoc` is missing)
2020-11-22T06:04:37.656Z ERR/cli:doctor 238 [*] ADB is not installed (`adb` is missing)
2020-11-22T06:04:37.793Z INF/cli:doctor 238 [*] Using GraphicsMagick 1.3.23

**The device details:**
```
[DEVICE_PROVISIONED]: [1]
[af.fast_track_multiplier]: [2]
[android.telephony.mcc_change]: [440]
[audio.deep_buffer.media]: [true]
[audio.dolby.ds2.enabled]: [true]
[audio.offload.buffer.size.kb]: [64]
[audio.offload.gapless.enabled]: [true]
[audio.offload.min.duration.secs]: [30]
[audio.offload.multiple.enabled]: [false]
[audio.offload.pcm.16bit.enable]: [true]
[audio.offload.pcm.24bit.enable]: [true]
[audio.offload.track.enable]: [true]
[audio.offload.video]: [true]
[audio.parser.ip.buffer.size]: [262144]
[audio.playback.mch.downsample]: [true]
[audio.pp.asphere.enabled]: [false]
[audio.safx.pbe.enabled]: [true]
[audio_hal.period_size]: [192]
[av.debug.disable.pers.cache]: [true]
[bluetooth.hfp.client]: [1]
[camera.display.lmax]: [1280x720]
[camera.display.umax]: [1920x1080]
[camera.hal1.packagelist]: [com.skype.raider,com.google.android.talk]
[camera.lowpower.record.enable]: [1]
[camera.video.brightness]: [199]
[config.cabl.path]: [/system/etc/FOSSConfig.xml]
[config.cabl.xml]: [1]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.heapgrowthlimit]: [192m]
[dalvik.vm.heapmaxfree]: [8m]
[dalvik.vm.heapminfree]: [4m]
[dalvik.vm.heapsize]: [512m]
[dalvik.vm.heapstartsize]: [16m]
[dalvik.vm.heaptargetutilization]: [0.75]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.isa.arm.features]: [default]
[dalvik.vm.isa.arm.variant]: [cortex-a53]
[dalvik.vm.isa.arm64.features]: [default]
[dalvik.vm.isa.arm64.variant]: [generic]
[dalvik.vm.stack-trace-file]: [/data/anr/traces.txt]
[debug.atrace.tags.enableflags]: [0]
[debug.choreographer.skipwarning]: [60]
[debug.egl.force_msaa]: [false]
[debug.egl.hw]: [0]
[debug.egl.trace]: [false]
[debug.enable.sglscale]: [1]
[debug.force_rtl]: [0]
[debug.hwui.overdraw]: [false]
[debug.hwui.profile]: [false]
[debug.hwui.show_dirty_regions]: []
[debug.hwui.show_layers_updates]: []
[debug.hwui.show_non_rect_clip]: [false]
[debug.junk.process.name]: [com.coloros.safecenter]
[debug.junk.process.pid]: [3950]
[debug.layout]: [false]
[debug.mdpcomp.logs]: [0]
[debug.oppo.morning.time]: [2 : 48]
[debug.screenoff.unlock]: [0]
[debug.sf.hw]: [0]
[dev.bootcomplete]: [1]
[dev.pm.dyn_samplingrate]: [1]
[drm.service.enabled]: [true]
[gr.apk.number]: [5]
[gr.download.url]: [http://otafs.coloros.com/googles/7a3341ea988614321a209c55265d381f]
[gr.use.leader]: [true]
[gsm.current.phone-type]: [1,1]
[gsm.lte.ca.support]: [1]
[gsm.network.type]: [Unknown,Unknown]
[gsm.operator.alpha]: []
[gsm.operator.iso-country]: []
[gsm.operator.isroaming]: [false,false]
[gsm.operator.numeric]: []
[gsm.sim.operator.alpha]: [,]
[gsm.sim.operator.iso-country]: [,]
[gsm.sim.operator.numeric]: [,]
[gsm.sim.operator.spn]: [Emergency calls only,No service]
[gsm.sim.state]: [ABSENT,ABSENT]
[gsm.version.baseband]: [Q_V1_P14,Q_V1_P14]
[gsm.version.ril-impl]: [Qualcomm RIL 1.0]
[hw.cabl.version]: [2.0.20140905]
[hw.cabl.yuv]: [0]
[init.svc.RIDL]: [stopped]
[init.svc.adbd]: [running]
[init.svc.adsprpcd]: [running]
[init.svc.alipayservice]: [running]
[init.svc.atfwd]: [running]
[init.svc.audiod]: [running]
[init.svc.bms-sh]: [stopped]
[init.svc.bootanim]: [stopped]
[init.svc.bspCriticalLog]: [running]
[init.svc.charger]: [stopped]
[init.svc.cnd]: [running]
[init.svc.cnss-daemon]: [running]
[init.svc.config-zram]: [stopped]
[init.svc.config_bluetooth]: [stopped]
[init.svc.config_bt_addr]: [stopped]
[init.svc.criticallog]: [running]
[init.svc.cs-early-boot]: [stopped]
[init.svc.cs-post-boot]: [stopped]
[init.svc.datafree]: [stopped]
[init.svc.debuggerd]: [running]
[init.svc.debuggerd64]: [running]
[init.svc.defaultcrypto]: [stopped]
[init.svc.dpmd]: [running]
[init.svc.drm]: [running]
[init.svc.engineermode-sh]: [stopped]
[init.svc.fingerprintd]: [running]
[init.svc.flash_recovery]: [stopped]
[init.svc.fpc1020_sh]: [stopped]
[init.svc.gatekeeperd]: [running]
[init.svc.healthd]: [running]
[init.svc.hypnus_context]: [stopped]
[init.svc.hypnus_logging]: [stopped]
[init.svc.imsdatadaemon]: [running]
[init.svc.imsqmidaemon]: [running]
[init.svc.installd]: [running]
[init.svc.ipacm]: [running]
[init.svc.ipacm-diag]: [running]
[init.svc.irsc_util]: [stopped]
[init.svc.junklog]: [running]
[init.svc.keystore]: [running]
[init.svc.lmkd]: [running]
[init.svc.loc_launcher]: [running]
[init.svc.logd]: [running]
[init.svc.logd-reinit]: [stopped]
[init.svc.mdtpd]: [running]
[init.svc.media]: [running]
[init.svc.msm_irqbal_lb]: [running]
[init.svc.netd]: [running]
[init.svc.netmgrd]: [running]
[init.svc.p2p_supplicant]: [running]
[init.svc.per_mgr]: [running]
[init.svc.per_proxy]: [running]
[init.svc.ppd]: [running]
[init.svc.ptt_socket_app]: [stopped]
[init.svc.qcamerasvr]: [running]
[init.svc.qcom-c_core-sh]: [stopped]
[init.svc.qcom-c_main-sh]: [stopped]
[init.svc.qcom-post-boot]: [stopped]
[init.svc.qcom-sh]: [stopped]
[init.svc.qcom-usb-sh]: [stopped]
[init.svc.qfintverify]: [stopped]
[init.svc.qmuxd]: [running]
[init.svc.qseecomd]: [running]
[init.svc.qseeproxydaemon]: [running]
[init.svc.qti]: [running]
[init.svc.qti-testscripts]: [stopped]
[init.svc.ril-daemon]: [running]
[init.svc.ril-daemon2]: [running]
[init.svc.rmt_storage]: [running]
[init.svc.rutilsdaemon]: [stopped]
[init.svc.seemp_healthd]: [running]
[init.svc.sensors]: [running]
[init.svc.servicemanager]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.tftp_server]: [running]
[init.svc.time_daemon]: [running]
[init.svc.ueventd]: [running]
[init.svc.vold]: [running]
[init.svc.wcnss-service]: [running]
[init.svc.wifiserver]: [stopped]
[init.svc.zygote]: [running]
[init.svc.zygote_secondary]: [running]
[keyguard.no_require_sim]: [true]
[media.aac_51_output_enabled]: [true]
[media.camera.ts.monotonic]: [1]
[media.msm8956.version]: [1]
[media.msm8956hw]: [1]
[media.settings.xml]: [/etc/media_profiles_8956.xml]
[mm.enable.qcom_parser]: [1048575]
[mm.enable.smoothstreaming]: [true]
[mmp.enable.3g2]: [true]
[net.bt.name]: [Android]
[net.change]: [net.dns3]
[net.dns1]: [10.122.122.129]
[net.dns2]: [10.122.122.193]
[net.dns3]: [8.8.8.8]
[net.hostname]: [android-e4f2e5d740712703]
[net.qtaguid_enabled]: [1]
[net.tcp.2g_init_rwnd]: [10]
[net.tcp.buffersize.default]: [4096,87380,524288,4096,16384,110208]
[net.tcp.buffersize.edge]: [4093,26280,35040,4096,16384,35040]
[net.tcp.buffersize.evdo]: [4094,87380,524288,4096,16384,262144]
[net.tcp.buffersize.gprs]: [4092,8760,11680,4096,8760,11680]
[net.tcp.buffersize.hsdpa]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.hspa]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.hspap]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.hsupa]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.lte]: [2097152,4194304,8388608,262144,524288,1048576]
[net.tcp.buffersize.umts]: [4094,87380,110208,4096,16384,110208]
[net.tcp.buffersize.wifi]: [524288,2097152,4194304,262144,524288,1048576]
[net.tcp.default_init_rwnd]: [60]
[oppo.camera.fmask]: [0]
[oppo.camera.jpegpath]: [/storage/sdcard1/DCIM]
[oppo.camera.lightIntensity]: [1073742645]
[oppo.camera.packname]: [com.oppo.camera]
[oppo.camera.sensor]: [imx398]
[oppo.camera.switch]: [0]
[oppo.camera.switch.time]: [650-650]
[oppo.camsensor.out]: [0]
[oppo.clear.running]: [0]
[oppo.device.firstboot]: [0]
[oppo.device.imeicache]: [864337038771235,864337038771227]
[oppo.dex.front.package]: [com.coloros.safecenter]
[oppo.dex.thread.count.switch]: [false]
[oppo.hostap.state]: [0]
[oppo.rutils.used.count]: [0]
[oppo.service.datafree.enable]: [0]
[oppo.service.rutils.enable]: [0]
[persist.audio.fluence.speaker]: [true]
[persist.audio.fluence.voicecall]: [true]
[persist.audio.fluence.voicerec]: [false]
[persist.camera.debug.logfile]: [0]
[persist.cne.feature]: [1]
[persist.data.mode]: [concurrent]
[persist.data.netmgrd.qos.enable]: [true]
[persist.dbg.volte_avail_ovr]: [1]
[persist.dbg.vt_avail_ovr]: [1]
[persist.debug.8976.config]: [true]
[persist.debug.coresight.config]: [stm-events]
[persist.debug.wfd.enable]: [1]
[persist.demo.hdmirotationlock]: [false]
[persist.dirac.acs.controller]: [qem]
[persist.dirac.acs.ignore_error]: [1]
[persist.fuse_sdcard]: [true]
[persist.gps.qc_nlp_in_use]: [1]
[persist.hwc.downscale_threshold]: [1.15]
[persist.hwc.enable_vds]: [1]
[persist.hwc.mdpcomp.enable]: [true]
[persist.loc.nlp_name]: [com.qualcomm.location]
[persist.logd.size]: []
[persist.oppo.signal]: [4000]
[persist.power.useautobrightadj]: [true]
[persist.qfp]: [false]
[persist.radio.adb_log_on]: [0]
[persist.radio.apm_sim_not_pwdn]: [1]
[persist.radio.custom_ecc]: [1]
[persist.radio.eons.enabled]: [false]
[persist.radio.force_on_dc]: [true]
[persist.radio.lte_vrte_ltd]: [1]
[persist.radio.lw_enabled]: [true]
[persist.radio.msim.stackid_0]: [0]
[persist.radio.msim.stackid_1]: [1]
[persist.radio.multisim.config]: [dsds]
[persist.radio.rat_on]: [legacy]
[persist.radio.ril_payload_on]: [0]
[persist.radio.sglte_target]: [0]
[persist.radio.sib16_support]: [1]
[persist.radio.stack_id_0]: [0]
[persist.radio.stack_id_1]: [1]
[persist.rild.nitz_long_ons_0]: []
[persist.rild.nitz_long_ons_1]: []
[persist.rild.nitz_long_ons_2]: []
[persist.rild.nitz_long_ons_3]: []
[persist.rild.nitz_plmn]: []
[persist.rild.nitz_short_ons_0]: []
[persist.rild.nitz_short_ons_1]: []
[persist.rild.nitz_short_ons_2]: []
[persist.rild.nitz_short_ons_3]: []
[persist.sys.adddevdiag]: [0]
[persist.sys.assert.enabletip]: [0]
[persist.sys.assert.panic]: [false]
[persist.sys.assert.state]: [false]
[persist.sys.autostoplog]: [1]
[persist.sys.cfu_auto]: [1]
[persist.sys.cnd.iwlan]: [1]
[persist.sys.dalvik.vm.lib.2]: [libart.so]
[persist.sys.device_first_boot]: [0]
[persist.sys.dpmd.nsrm]: [2]
[persist.sys.dpmd.tcm]: [2]
[persist.sys.dump]: [0]
[persist.sys.hdcp_checking]: [false]
[persist.sys.lasttime]: [1605985279000]
[persist.sys.locale]: [en-US]
[persist.sys.media.use-awesome]: [false]
[persist.sys.mute.state]: [2]
[persist.sys.no_req_encrypt]: [true]
[persist.sys.ns_version]: [1.01]
[persist.sys.oem_smooth]: [1]
[persist.sys.oppo.displaymetrics]: [1080,1920]
[persist.sys.oppo.dragstate]: [0]
[persist.sys.oppo.fatal]: []
[persist.sys.oppo.fb_upgraded]: [1]
[persist.sys.oppo.fp_psensor]: [true]
[persist.sys.oppo.fp_tpprotecet]: [true]
[persist.sys.oppo.junklog]: [false]
[persist.sys.oppo.junkmonitor]: [true]
[persist.sys.oppo.reboot]: []
[persist.sys.oppo.region]: [CN]
[persist.sys.oppo.screendrag]: [0,0,0,0.0]
[persist.sys.ota.downloaded]: [true]
[persist.sys.ota.last_screenoff]: [1605752716110]
[persist.sys.panic.file]: []
[persist.sys.permission.enable]: [true]
[persist.sys.poweralarm.time]: [-1]
[persist.sys.poweroffsound]: [1]
[persist.sys.poweronsound]: [1]
[persist.sys.procmon_enable]: [1]
[persist.sys.profiler_ms]: [0]
[persist.sys.sau.launchcheck]: [2]
[persist.sys.screenshot.times]: [3]
[persist.sys.strictmode.visual]: []
[persist.sys.systemserver.pid]: [1145]
[persist.sys.timezone]: [Asia/Shanghai]
[persist.sys.ui.hw]: [false]
[persist.sys.usb.config]: [mtp,adb]
[persist.sys.usb.config.extra]: [none]
[persist.sys.wipemedia]: [0]
[persist.timed.enable]: [true]
[persist.version.confidential]: [false]
[qcom.audio.init]: [complete]
[qcom.hw.aac.encoder]: [true]
[qemu.hw.mainkeys]: [1]
[ril.ecclist]: [911,*911,#911,120,122,112,000,08,110,999,118,119]
[ril.ecclist1]: [911,*911,#911,120,122,112,000,08,110,999,118,119]
[ril.qcril_pre_init_lock_held]: [0]
[ril.subscription.types]: [NV,RUIM]
[rild.libargs]: [-d /dev/smd0]
[rild.libpath]: [/vendor/lib64/libril-qc-qmi-1.so]
[ro.adb.secure]: [1]
[ro.alarm_boot]: [false]
[ro.allow.mock.location]: [0]
[ro.baseband]: [msm]
[ro.bluetooth.dun]: [true]
[ro.bluetooth.hfp.ver]: [1.6]
[ro.bluetooth.sap]: [true]
[ro.board.platform]: [msm8952]
[ro.boot.authorized_kernel]: [true]
[ro.boot.baseband]: [msm]
[ro.boot.bootdevice]: [7824900.sdhci]
[ro.boot.console]: [ttyHSL0]
[ro.boot.emmc]: [true]
[ro.boot.hardware]: [qcom]
[ro.boot.keymaster]: [1]
[ro.boot.mode]: [normal]
[ro.boot.selinux]: [enforcing]
[ro.boot.serialno]: [99292447]
[ro.boot.startupmode]: [pwrkey]
[ro.boot.verifiedbootstate]: [green]
[ro.boot.veritymode]: [enforcing]
[ro.bootimage.build.date]: [Thu Dec 22 22:53:14 CST 2016]
[ro.bootimage.build.date.utc]: [1482418394]
[ro.bootimage.build.fingerprint]: [Android/msm8952_64/msm8952_64:6.0.1/MMB29M/root12222245:user/dev-keys]
[ro.bootloader]: [unknown]
[ro.bootmode]: [normal]
[ro.build.characteristics]: [nosdcard]
[ro.build.date]: [Thu Dec 22 22:46:50 CST 2016]
[ro.build.date.YmdHM]: [201612222246]
[ro.build.date.utc]: [1482418010]
[ro.build.date.ymd]: [161222]
[ro.build.description]: [msm8952_64-user 6.0.1 MMB29M eng.root.20161222.224308 dev-keys]
[ro.build.display.full_id]: [R9sPlus_11_A.06_161222]
[ro.build.display.id]: [R9sPlus_11_A.06_161222]
[ro.build.fingerprint]: [OPPO/R9sPlus/R9sPlus:6.0.1/MMB29M/1474513791:user/release-keys]
[ro.build.flavor]: [msm8952_64-user]
[ro.build.host]: [ubuntu-121-137]
[ro.build.id]: [MMB29M]
[ro.build.kernel.id]: [3.10.84-G201612222218]
[ro.build.master.date]: [201611080336]
[ro.build.product]: [R9sPlus]
[ro.build.release_type]: [true]
[ro.build.soft.majorversion]: []
[ro.build.soft.version]: [A.06]
[ro.build.tags]: [dev-keys]
[ro.build.type]: [user]
[ro.build.user]: [root]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: [OPPO/R9sPlus/R9sPlus:6.0.1/MMB29M/1474513791:user/release-keys]
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [eng.root.20161222.224308]
[ro.build.version.opporom]: [V3.0]
[ro.build.version.ota]: [R9sPlus_11.A.06_006_201612222218]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [6.0.1]
[ro.build.version.sdk]: [23]
[ro.build.version.security_patch]: [2016-10-01]
[ro.carrier]: [unknown]
[ro.com.android.dataroaming]: [true]
[ro.com.google.clientidbase]: [android-oppo]
[ro.config.alarm_alert]: [alarm_001.ogg]
[ro.config.calendar_sound]: [notification_003.ogg]
[ro.config.notification_sim2]: [notification_001.ogg]
[ro.config.notification_sound]: [notification_001.ogg]
[ro.config.ringtone]: [ringtone_001.ogg]
[ro.config.ringtone_sim2]: [ringtone_001.ogg]
[ro.core_ctl_max_cpu]: [4]
[ro.core_ctl_min_cpu]: [2]
[ro.crypto.fs_crypto_blkdev]: [/dev/block/dm-0]
[ro.crypto.state]: [encrypted]
[ro.crypto.type]: [block]
[ro.cutoff_voltage_mv]: [3200]
[ro.dalvik.vm.native.bridge]: [0]
[ro.debuggable]: [0]
[ro.dumpenvironment.time]: [10000]
[ro.expect.recovery_id]: []
[ro.fm.transmitter]: [false]
[ro.frp.pst]: [/dev/block/bootdevice/by-name/config]
[ro.gps.agps_provider]: [1]
[ro.hardware]: [qcom]
[ro.hwui.drop_shadow_cache_size]: [6]
[ro.hwui.gradient_cache_size]: [1]
[ro.hwui.layer_cache_size]: [48]
[ro.hwui.path_cache_size]: [32]
[ro.hwui.r_buffer_cache_size]: [8]
[ro.hwui.text_large_cache_height]: [2048]
[ro.hwui.text_large_cache_width]: [2048]
[ro.hwui.text_small_cache_height]: [1024]
[ro.hwui.text_small_cache_width]: [1024]
[ro.hwui.texture_cache_flushrate]: [0.4]
[ro.hwui.texture_cache_size]: [72]
[ro.lcd.backlight.config_jdi]: [11,788,17,247,392,648,879,1135,1402,1546,1789,2047]
[ro.lcd.backlight.config_samsung]: [7,52,11,30,65,108,175,255]
[ro.mdtp.package_name2]: [com.qualcomm.qti.securemsm.mdtp.MdtpDemo]
[ro.opengles.version]: [196609]
[ro.oppo.theme.version]: [801]
[ro.product.authentication]: [2016CP6413]
[ro.product.board]: [msm8952]
[ro.product.brand]: [OPPO]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cpuinfo]: [MSM8976 Pro]
[ro.product.device]: [R9sPlus]
[ro.product.locale]: [zh-CN]
[ro.product.manufacturer]: [OPPO]
[ro.product.model]: [OPPO R9s Plus]
[ro.product.name]: [R9sPlus]
[ro.qc.sdk.audio.fluencetype]: [none]
[ro.qc.sdk.audio.ssr]: [false]
[ro.qti.sensors.wu]: [false]
[ro.qualcomm.bluetooth.ftp]: [true]
[ro.qualcomm.bluetooth.hfp]: [true]
[ro.qualcomm.bluetooth.hsp]: [true]
[ro.qualcomm.bluetooth.map]: [true]
[ro.qualcomm.bluetooth.nap]: [true]
[ro.qualcomm.bluetooth.opp]: [true]
[ro.qualcomm.bluetooth.pbap]: [true]
[ro.qualcomm.bt.hci_transport]: [smd]
[ro.qualcomm.cabl]: [0]
[ro.qualcomm.display.paneltype]: [1]
[ro.report.tid]: [1]
[ro.revision]: [0]
[ro.rf_version]: [TDD_FDD_Ch_A_16037]
[ro.ril.svdo]: [false]
[ro.ril.svlte1x]: [false]
[ro.runtime.firstboot]: [1605750920911]
[ro.secure]: [1]
[ro.separate.soft]: [MSM_16037]
[ro.serialno]: [99292447]
[ro.sf.lcd_density]: [480]
[ro.sys.fw.dex2oat_thread_count]: [4]
[ro.sys.fw.empty_app_percent]: [50]
[ro.sys.fw.trim_cache_percent]: [100]
[ro.sys.fw.trim_empty_percent]: [100]
[ro.sys.fw.trim_enable_memory]: [2147483648]
[ro.sys.fw.use_trim_settings]: [true]
[ro.telephony.call_ring.multiple]: [false]
[ro.telephony.default_network]: [10,20]
[ro.use_data_netmgrd]: [true]
[ro.vendor.at_library]: [libqti-at.so]
[ro.vendor.extension_library]: [libqti-perfd-client.so]
[ro.vendor.gt_library]: [libqti-gt.so]
[ro.wandrfmode]: [0]
[ro.wifi.channels]: []
[ro.xxversion]: [v1.0]
[ro.zygote]: [zygote64_32]
[sched.colocate.enable]: [1]
[security.perf_harden]: [1]
[selinux.reload_policy]: [1]
[service.bootanim.exit]: [1]
[sys.app_freeze_timeout]: [0]
[sys.appcrash_reboot]: [0]
[sys.boot_completed]: [1]
[sys.boottime]: [8063]
[sys.enable.hypnus]: [1]
[sys.foreground_process]: [android]
[sys.ims.QMI_DAEMON_STATUS]: [1]
[sys.keymaster.loaded]: [true]
[sys.listeners.registered]: [true]
[sys.oem_unlock_allowed]: [0]
[sys.oppo.boot_completed]: [1]
[sys.oppo.justshot]: [0]
[sys.oppo.multibrightness]: [2047]
[sys.oppo.screenshot]: [0]
[sys.power.screenoff.reason]: [2]
[sys.settings_global_version]: [11]
[sys.settings_secure_version]: [4]
[sys.settings_system_version]: [1360]
[sys.sysctl.extra_free_kbytes]: [24300]
[sys.sysctl.tcp_def_init_rwnd]: [60]
[sys.usb.config]: [mtp,mass_storage,adb]
[sys.usb.configfs]: [0]
[sys.usb.ffs.ready]: [1]
[sys.usb.rps_mask]: [0]
[sys.usb.state]: [mtp,mass_storage,adb]
[telephony.lteOnCdmaDevice]: [1]
[tunnel.audio.encode]: [false]
[use.voice.path.for.pcm.voip]: [true]
[vidc.enc.dcvs.extra-buff-count]: [2]
[vidc.enc.narrow.searchrange]: [1]
[voice.conc.fallbackpath]: [deep-buffer]
[voice.playback.conc.disabled]: [true]
[voice.record.conc.disabled]: [false]
[voice.voip.conc.disabled]: [true]
[vold.decrypt]: [trigger_restart_framework]
[vold.has_adoptable]: [0]
[vold.post_fs_data_done]: [1]
[wifi.interface]: [wlan0]
[wlan.driver.ath]: [0]
[wlan.driver.config]: [/data/misc/wifi/WCNSS_qcom_cfg.ini]
[wlan.driver.status]: [ok]

**Comment by jay0129** [comment]
Additional log FYI.
```
FTL/device 464 [99292447]
Setup had an error Error: /data/local/tmp/STFService.apk could not be installed [-99]
    at /app/node_modules/@devicefarmer/adbkit/lib/adb/command/host-transport/install.js:28:23
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by jay0129** [comment]
https://github.com/openstf/stf/issues/978
