### ISSUE TITLE
s20 Android 11 update no longer working with Docker image

### ISSUE THREAD

**Issue by Norensien** [DeviceFarmer/stf#150]
**What is the issue or idea you have?**
Updated an s20 from android 10 to android 11, STF is no longer working. I am using the latest docker Image. 

**What is the expected behavior?**
STF has worked perfectly using docker for the last few months on android 10, after updating to android 11 it is not working, i have recently updated all my devices, so im just wondering if the docker image supports android 11, if not when is it expected to? and if it does can you see anything wrong with my setup? 

Current setup is a laptop running a linux VM, using Devicefarmer/stf latest build connected to a hub of 11 s20s all of which have been updated to android 11 and no longer work. 

below is an output from my docker logs 

_2020-12-03T14:12:17.287Z INF/provider 39 [*] Found device "R3CMA03K3EE" (offline)
2020-12-03T14:12:17.332Z INF/provider 39 [*] Registered device "R3CMA03K3EE"
2020-12-03T14:12:17.332Z INF/provider 39 [*] Device "R3CMA03K3EE" is now "device" (was "offline")
2020-12-03T14:12:17.362Z INF/reaper 25 [reaper001] Device "R3CMA03K3EE" is present
2020-12-03T14:12:19.081Z INF/device:support:push 12581 [R3CMA03K3EE] Sending output to "tcp://0.0.0.0:7116"
2020-12-03T14:12:19.087Z INF/device 12581 [R3CMA03K3EE] Preparing device
2020-12-03T14:12:20.033Z INF/device:support:sub 12581 [R3CMA03K3EE] Receiving input from "tcp://0.0.0.0:7114"
2020-12-03T14:12:20.037Z INF/device:support:sub 12581 [R3CMA03K3EE] Subscribing to permanent channel "*ALL"
2020-12-03T14:12:20.807Z INF/device:support:properties 12581 [R3CMA03K3EE] Loading properties
2020-12-03T14:12:20.877Z INF/device:support:sdk 12581 [R3CMA03K3EE] Supports SDK 30
2020-12-03T14:12:20.883Z INF/device:support:abi 12581 [R3CMA03K3EE] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2020-12-03T14:12:20.901Z FTL/device 12581 [R3CMA03K3EE] Setup had an error Error: At least one of these paths should exist: /app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/armeabi/lib/android-30/minicap.so, /app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/armeabi/lib/android-30/minicap.so
    at Object.module.exports.requiredMatch (/app/lib/util/pathutil.js:33:9)
    at /app/lib/units/device/resources/minicap.js:41:23
    at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
    at /app/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2020-12-03T14:12:20.924Z FTL/util:lifecycle 12581 [R3CMA03K3EE] Shutting down due to fatal error_

thanks for any help you can provide.

**Comment by KBearRJ** [comment]
I understand there is limited supportability for Emulators however was this ever fixed or is there more detail around it? I recently attempted to connect android emulators of Android version 11 and received this exact issue - Spun down and upgraded to 3.6.1 to ensure i was at a version that had support for Android 11 (3.5.0) as there are numerous posts about 3.4.1 not supporting this deployment. 

Also running numerous versions of android emulators without any issues. (8/9/etc)
