### ISSUE TITLE
Pixel 3 XL doesn't work

### ISSUE THREAD

**Issue by jay0129** [DeviceFarmer/stf#182]
**What is the issue or idea you have?**
I update STF version to the latest which is https://github.com/DeviceFarmer/stf/commit/0fc3d091ef0c8bc15ed6558fdd74fad5aa206311
However, it seems like minicap and minitouch doesn't work for this new device Pixel_3_XL.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
List of devices attached
...
8A8Y0FQKQ              device usb:1-13.3 product:crosshatch model:Pixel_3_XL device:crosshatch transport_id:1

**Please provide the steps to reproduce the issue.**
Connect Android device Pixel_3_XL to STF

**What is the expected behavior?**
Pixel_3_XL should be usable from STF console

**Please run `stf doctor` and paste the output here.**
$ stf doctor
2021-02-24T02:32:57.640Z INF/cli:doctor 20 [*] OS Arch: x64
2021-02-24T02:32:57.642Z INF/cli:doctor 20 [*] OS Platform: linux
2021-02-24T02:32:57.642Z INF/cli:doctor 20 [*] OS Platform: 5.4.0-56-generic
2021-02-24T02:32:57.642Z INF/cli:doctor 20 [*] Using Node 8.9.3
2021-02-24T02:32:57.651Z INF/cli:doctor 20 [*] Using ZeroMQ 4.1.4
2021-02-24T02:32:57.661Z ERR/cli:doctor 20 [*] RethinkDB is not installed (`rethinkdb` is missing)
2021-02-24T02:32:57.661Z ERR/cli:doctor 20 [*] ProtoBuf is not installed (`protoc` is missing)
2021-02-24T02:32:57.661Z ERR/cli:doctor 20 [*] ADB is not installed (`adb` is missing)
2021-02-24T02:32:57.662Z INF/cli:doctor 20 [*] Using GraphicsMagick 1.3.23
$ stf --version
3.5.0

** Provider log **
2021-02-24T02:40:46.634Z IMP/device:plugins:group 92 [8A8Y0FQKQ] Now owned by "abc3232@gmail.com"
2021-02-24T02:40:46.634Z INF/device:plugins:group 92 [8A8Y0FQKQ] Subscribing to group channel "REkS2k53RoWgXIojaNlGlA=="
2021-02-24T02:40:46.740Z INF/device:plugins:screen:stream 92 [8A8Y0FQKQ] Setting frame producer projection to 628x1173
2021-02-24T02:40:46.741Z INF/device:plugins:screen:stream 92 [8A8Y0FQKQ] Requesting frame producer to start
2021-02-24T02:40:46.742Z INF/device:plugins:screen:stream 92 [8A8Y0FQKQ] Launching screen service
2021-02-24T02:40:46.763Z INF/device:plugins:connect 92 [8A8Y0FQKQ] Listening on port 7425
2021-02-24T02:40:46.766Z IMP/device:plugins:connect 92 [8A8Y0FQKQ] Remote Connect Started for device "8A8Y0FQKQ" at "localhost:7425"
2021-02-24T02:40:46.778Z INF/device:plugins:screen:stream 92 [8A8Y0FQKQ] minicap says: "CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": cannot locate symbol "_ZN7android21SurfaceComposerClient23getPhysicalDisplayTokenEm" referenced by "/data/local/tmp/minicap.so"..."
2021-02-24T02:40:46.779Z WRN/device:plugins:screen:stream 92 [8A8Y0FQKQ] Shell keeping minicap running ended unexpectedly
2021-02-24T02:40:48.446Z IMP/device:plugins:group 92 [8A8Y0FQKQ] No longer owned by "abc3232@gmail.com"
2021-02-24T02:40:48.447Z INF/device:plugins:group 92 [8A8Y0FQKQ] Unsubscribing from group channel "REkS2k53RoWgXIojaNlGlA=="
2021-02-24T02:40:48.449Z INF/device:plugins:screen:stream 92 [8A8Y0FQKQ] Requesting frame producer to stop
2021-02-24T02:40:48.757Z INF/device:plugins:screen:stream 92 [8A8Y0FQKQ] Disconnecting from minicap service
2021-02-24T02:40:48.759Z INF/device:plugins:screen:stream 92 [8A8Y0FQKQ] Stopping minicap service
2021-02-24T02:40:48.761Z FTL/device:plugins:screen:stream 92 [8A8Y0FQKQ] Frame producer had an error TimeoutError: operation timed out
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
From previous event:
    at FrameProducer._waitForPid (/app/lib/units/device/plugins/screen/stream.js:271:10)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:80:27)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
2021-02-24T02:40:48.762Z FTL/util:lifecycle 92 [8A8Y0FQKQ] Shutting down due to fatal error
2021-02-24T02:40:48.769Z INF/provider 1 [*] Cleaning up device worker "8A8Y0FQKQ"
2021-02-24T02:40:48.769Z ERR/provider 1 [*] Device worker "8A8Y0FQKQ" died with code 1
2021-02-24T02:40:48.769Z INF/provider 1 [*] Restarting device worker "8A8Y0FQKQ"
2021-02-24T02:40:49.503Z INF/device:support:push 104 [8A8Y0FQKQ] Sending output to "tcp://dev-triproxy:7270"
2021-02-24T02:40:49.505Z INF/device 104 [8A8Y0FQKQ] Preparing device
2021-02-24T02:40:49.791Z INF/device:support:sub 104 [8A8Y0FQKQ] Receiving input from "tcp://dev-triproxy:7250"
2021-02-24T02:40:49.792Z INF/device:support:sub 104 [8A8Y0FQKQ] Subscribing to permanent channel "*ALL"
2021-02-24T02:40:49.830Z INF/device:support:properties 104 [8A8Y0FQKQ] Loading properties
2021-02-24T02:40:49.871Z INF/device:support:sdk 104 [8A8Y0FQKQ] Supports SDK 31 (base 30, preview delta +1)
2021-02-24T02:40:49.872Z INF/device:support:abi 104 [8A8Y0FQKQ] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2021-02-24T02:40:50.118Z INF/device:resources:minicap 104 [8A8Y0FQKQ] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2021-02-24T02:40:50.119Z INF/device:resources:minicap 104 [8A8Y0FQKQ] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-30/minicap.so" as "/data/local/tmp/minicap.so"
2021-02-24T02:40:50.212Z INF/device:resources:service 104 [8A8Y0FQKQ] Checking whether we need to install STFService
2021-02-24T02:40:50.271Z INF/device:resources:service 104 [8A8Y0FQKQ] Running version check
2021-02-24T02:40:51.511Z INF/device:resources:service 104 [8A8Y0FQKQ] Installing STFService
2021-02-24T02:40:53.942Z INF/device:resources:service 104 [8A8Y0FQKQ] STFService up to date
2021-02-24T02:40:53.943Z INF/device:plugins:service 104 [8A8Y0FQKQ] Launching agent
2021-02-24T02:40:54.415Z INF/device:plugins:service 104 [8A8Y0FQKQ] Agent says: "Starting minitouch agent"
2021-02-24T02:40:54.453Z INF/device:plugins:service 104 [8A8Y0FQKQ] Agent says: "Listening on @stfagent"
2021-02-24T02:40:54.468Z INF/device:plugins:service 104 [8A8Y0FQKQ] Launching service
2021-02-24T02:40:54.469Z INF/device:plugins:service 104 [8A8Y0FQKQ] using 'start-foreground-service' command for API 30
2021-02-24T02:40:54.471Z INF/device:plugins:service 104 [8A8Y0FQKQ] Agent says: "InputClient started"
2021-02-24T02:40:54.633Z INF/device:plugins:display 104 [8A8Y0FQKQ] Reading display info
2021-02-24T02:40:54.656Z INF/device:plugins:phone 104 [8A8Y0FQKQ] Fetching phone info
2021-02-24T02:40:54.667Z INF/device:plugins:identity 104 [8A8Y0FQKQ] Solving identity
2021-02-24T02:40:54.679Z INF/device:plugins:solo 104 [8A8Y0FQKQ] Subscribing to permanent channel "kLHVUwxrT3bHrDlagx1a2fWs9M4="
2021-02-24T02:40:54.682Z INF/device:plugins:screen:stream 104 [8A8Y0FQKQ] Starting WebSocket server on port 7428
2021-02-24T02:40:54.889Z INF/device:resources:minitouch 104 [8A8Y0FQKQ] Installing "/app/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
2021-02-24T02:40:54.932Z WRN/device:plugins:data 104 [8A8Y0FQKQ] Unable to find device data { serial: '8A8Y0FQKQ',
  platform: 'Android',
  manufacturer: 'GOOGLE',
  operator: null,
  model: 'Pixel 3 XL',
  version: '11',
  abi: 'arm64-v8a',
  sdk: '30',
  product: 'crosshatch',
  cpuPlatform: 'sdm845',
  openGLESVersion: '3.2',
  marketName: 'Pixel 3 XL',
  display:
   { id: 0,
     width: 1440,
     height: 2960,
     xdpi: 522.5139770507812,
     ydpi: 522.1110229492188,
     fps: 60.000003814697266,
     density: 3.5,
     rotation: 0,
     secure: true,
     size: 6.303641748967742,
     url: 'ws://localhost/d/KOREA_BS_1/8A8Y0FQKQ/7428/' },
  phone: { network: 'UNKNOWN' } }
2021-02-24T02:40:54.935Z INF/device:plugins:touch 104 [8A8Y0FQKQ] Touch origin is top left
2021-02-24T02:40:54.935Z INF/device:plugins:touch 104 [8A8Y0FQKQ] Requesting touch consumer to start
2021-02-24T02:40:54.935Z INF/device:plugins:touch 104 [8A8Y0FQKQ] Launching touch service
2021-02-24T02:40:54.945Z INF/device:plugins:touch 104 [8A8Y0FQKQ] Connecting to minitouch service
2021-02-24T02:40:54.964Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "open: Permission denied"
2021-02-24T02:40:54.964Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "Unable to open device /dev/input/event3 for inspectionopen: Permission denied"
2021-02-24T02:40:54.965Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2021-02-24T02:40:54.965Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied"
2021-02-24T02:40:54.966Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "Unable to open device /dev/input/mice for inspectionopen: Permission denied"
2021-02-24T02:40:54.967Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2021-02-24T02:40:54.967Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
2021-02-24T02:40:54.968Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "using Android InputManager"
2021-02-24T02:40:55.053Z INF/device:plugins:touch 104 [8A8Y0FQKQ] minitouch says: "Connection established"
2021-02-24T02:40:55.054Z INF/device:plugins:touch 104 [8A8Y0FQKQ] Reading minitouch banner
2021-02-24T02:40:55.066Z INF/device:plugins:vnc 104 [8A8Y0FQKQ] Starting VNC server on port 7430
2021-02-24T02:40:55.070Z INF/device:plugins:browser 104 [8A8Y0FQKQ] Loading browser list
2021-02-24T02:40:55.078Z INF/device:plugins:browser 104 [8A8Y0FQKQ] Updating browser list
2021-02-24T02:40:55.082Z INF/device:plugins:mute 104 [8A8Y0FQKQ] Will not mute master volume
2021-02-24T02:40:55.283Z INF/device:resources:minirev 104 [8A8Y0FQKQ] Installing "/app/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
2021-02-24T02:40:55.333Z INF/device:plugins:forward 104 [8A8Y0FQKQ] Launching reverse port forwarding service
2021-02-24T02:40:55.341Z INF/device:plugins:forward 104 [8A8Y0FQKQ] Connecting to reverse port forwarding service
2021-02-24T02:40:55.462Z INF/device 104 [8A8Y0FQKQ] Fully operational

**Comment by passself** [comment]
pixel3xl android9 can't connected, android 10 can connect

**Comment by denis99999** [comment]
@passself , I see `"permission denied"` error in logs, so propably you should review the configuration of your device in particular developer settings concerning `USB`
