### ISSUE TITLE
TypeError: Cannot read property 'subscribed' of undefined in docker stf-api

### ISSUE THREAD

**Issue by robernaveiras** [DeviceFarmer/stf#183]
**What is the issue or idea you have?**

After changing the services of docker for stf upgrade we get a 500 error on /api/v1/devices

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

No

**Please provide the steps to reproduce the issue.**
Change in the .service files for docker openstf/stf:v3.4.1 for devicefarmer/stf:3.5

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

In the docker for stf-api we get this error

TypeError: Cannot read property 'subscribed' of undefined
    at getGenericDevices (/app/lib/units/api/controllers/devices.js:31:31)
    at getDevices (/app/lib/units/api/controllers/devices.js:213:7)
    at swagger_router (/app/node_modules/swagger-node-runner/fittings/swagger_router.js:104:13)
    at Runner.<anonymous> (/app/node_modules/bagpipes/lib/bagpipes.js:171:7)
    at bound (domain.js:301:14)
    at Runner.runBound (domain.js:314:12)
    at Runner.pipeline (/app/node_modules/pipeworks/pipeworks.js:72:17)
    at Runner.flow (/app/node_modules/pipeworks/pipeworks.js:223:19)
    at Pipeworks.flow (/app/node_modules/pipeworks/pipeworks.js:135:17)
    at Pipeworks.siphon (/app/node_modules/pipeworks/pipeworks.js:186:19)
    at Runner.<anonymous> (/app/node_modules/bagpipes/lib/bagpipes.js:98:22)
    at bound (domain.js:301:14)
    at Runner.runBound (domain.js:314:12)
    at Runner.<anonymous> (/app/node_modules/pipeworks/pipeworks.js:72:17)
    at postFlight (/app/node_modules/bagpipes/lib/bagpipes.js:220:3)
    at /app/node_modules/bagpipes/lib/bagpipes.js:174:9

**Please run `stf doctor` and paste the output here.**

**Comment by denis99999** [comment]
@robernaveiras , from v3.4.1 to v3.5.0 the database model has been updated because a new great feature has been introduced named "group feature" designed for device booking/partitionning, normally the migration process through the migrate unit makes the job but you have also to update the way you launch the other service units including the API one, you have also to launch a new service unit named "groups-engine", see the `DEPLOYMENT.md` file for details as well as instructions in `README.md` file at `Running` and `Features` section.
