### ISSUE TITLE
Proxy had an error Error: connect ECONNREFUSED 127.0.0.1:7106

### ISSUE THREAD

**Issue by kevin32** [DeviceFarmer/stf#197]
**What is the issue or idea you have?**
I use docker-compose with OAuth2 to run stf (MacBook)
When I start it everything works, but  after 5 to 10 hours, I can't see no devices, but STF webpage is running. 
What I see from the logs.
<img width="788" alt="Screenshot 2021-03-09 at 16 35 20" src="https://user-images.githubusercontent.com/7901760/110614106-a948cf80-819a-11eb-9d77-9ad252d27213.png">

My docker compose:
`version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  stf:
    container_name: stf
    build: . #I tried using stf image from hub, same thing
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=xxx@xx.xx
      - STF_ADMIN_NAME=Kevin
    restart: unless-stopped
    command: stf local --public-ip stf.xxx.xx.ee --auth-type oauth2 --auth-options '[ "--oauth-authorization-url", "https://login.microsoftonline.com/-x-x--x-x-x/oauth2/v2.0/authorize", "--oauth-token-url", "https://login.microsoftonline.com/-x-x-x-x--x-x-/oauth2/v2.0/token", "--oauth-userinfo-url", "https://graph.microsoft.com/oidc/userinfo", "--oauth-client-id", "-x-x-x-x-x", "--oauth-client-secret", "-x-x-x-x-x-", "--oauth-callback-url", "https://stf.xxx.xx.ee/auth/oauth/callback", "--oauth-scope", "openid email" ]' --provider-min-port 7400 --provider-max-port 7500 --adb-host docker.for.mac.host.internal

volumes:
  rethinkdb-data: {}
`

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

> stf@a14dd3587790:/app$ stf local
2021-03-09T15:05:54.111Z INF/util:procutil 614 [*] Forking "/app/lib/cli migrate"
2021-03-09T15:05:54.330Z INF/db 620 [*] Connecting to rethinkdb:28015
2021-03-09T15:05:54.347Z INF/db:setup 620 [*] Database "stf" already exists
2021-03-09T15:05:54.351Z INF/db:setup 620 [*] Table "users" already exists
2021-03-09T15:05:54.351Z INF/db:setup 620 [*] Table "accessTokens" already exists
2021-03-09T15:05:54.351Z INF/db:setup 620 [*] Table "vncauth" already exists
2021-03-09T15:05:54.352Z INF/db:setup 620 [*] Table "devices" already exists
2021-03-09T15:05:54.352Z INF/db:setup 620 [*] Table "logs" already exists
2021-03-09T15:05:54.352Z INF/db:setup 620 [*] Table "groups" already exists
2021-03-09T15:05:54.372Z INF/db:setup 620 [*] Index "users"."adbKeys" already exists
2021-03-09T15:05:54.372Z INF/db:setup 620 [*] Index "accessTokens"."email" already exists
2021-03-09T15:05:54.372Z INF/db:setup 620 [*] Index "vncauth"."response" already exists
2021-03-09T15:05:54.372Z INF/db:setup 620 [*] Index "vncauth"."responsePerDevice" already exists
2021-03-09T15:05:54.372Z INF/db:setup 620 [*] Index "devices"."owner" already exists
2021-03-09T15:05:54.373Z INF/db:setup 620 [*] Index "devices"."logs_enabled" already exists
2021-03-09T15:05:54.373Z INF/db:setup 620 [*] Index "devices"."present" already exists
2021-03-09T15:05:54.373Z INF/db:setup 620 [*] Index "devices"."providerChannel" already exists
2021-03-09T15:05:54.373Z INF/db:setup 620 [*] Index "devices"."group" already exists
2021-03-09T15:05:54.374Z INF/db:setup 620 [*] Index "groups"."privilege" already exists
2021-03-09T15:05:54.374Z INF/db:setup 620 [*] Index "groups"."owner" already exists
2021-03-09T15:05:54.374Z INF/db:setup 620 [*] Index "groups"."startTime" already exists
2021-03-09T15:05:54.374Z INF/db:setup 620 [*] Waiting for index "users"."adbKeys"
2021-03-09T15:05:54.375Z INF/db:setup 620 [*] Waiting for index "accessTokens"."email"
2021-03-09T15:05:54.376Z INF/db:setup 620 [*] Waiting for index "vncauth"."response"
2021-03-09T15:05:54.376Z INF/db:setup 620 [*] Waiting for index "vncauth"."responsePerDevice"
2021-03-09T15:05:54.377Z INF/db:setup 620 [*] Waiting for index "devices"."owner"
2021-03-09T15:05:54.377Z INF/db:setup 620 [*] Waiting for index "devices"."logs_enabled"
2021-03-09T15:05:54.378Z INF/db:setup 620 [*] Waiting for index "devices"."present"
2021-03-09T15:05:54.379Z INF/db:setup 620 [*] Waiting for index "devices"."providerChannel"
2021-03-09T15:05:54.379Z INF/db:setup 620 [*] Waiting for index "devices"."group"
2021-03-09T15:05:54.380Z INF/db:setup 620 [*] Waiting for index "groups"."privilege"
2021-03-09T15:05:54.380Z INF/db:setup 620 [*] Waiting for index "groups"."owner"
2021-03-09T15:05:54.381Z INF/db:setup 620 [*] Waiting for index "groups"."startTime"
2021-03-09T15:05:54.382Z INF/db:setup 620 [*] Index "users"."adbKeys" is ready
2021-03-09T15:05:54.383Z INF/db:setup 620 [*] Index "accessTokens"."email" is ready
2021-03-09T15:05:54.383Z INF/db:setup 620 [*] Index "vncauth"."response" is ready
2021-03-09T15:05:54.384Z INF/db:setup 620 [*] Index "vncauth"."responsePerDevice" is ready
2021-03-09T15:05:54.384Z INF/db:setup 620 [*] Index "devices"."logs_enabled" is ready
2021-03-09T15:05:54.384Z INF/db:setup 620 [*] Index "devices"."present" is ready
2021-03-09T15:05:54.384Z INF/db:setup 620 [*] Index "devices"."owner" is ready
2021-03-09T15:05:54.385Z INF/db:setup 620 [*] Index "devices"."providerChannel" is ready
2021-03-09T15:05:54.385Z INF/db:setup 620 [*] Index "groups"."privilege" is ready
2021-03-09T15:05:54.386Z INF/db:setup 620 [*] Index "groups"."owner" is ready
2021-03-09T15:05:54.386Z INF/db:setup 620 [*] Index "groups"."startTime" is ready
2021-03-09T15:05:54.386Z INF/db:setup 620 [*] Index "devices"."group" is ready
2021-03-09T15:05:55.406Z INF/util:procutil 614 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2021-03-09T15:05:55.408Z INF/util:procutil 614 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2021-03-09T15:05:55.410Z INF/util:procutil 614 [*] Forking "/app/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2021-03-09T15:05:55.412Z INF/util:procutil 614 [*] Forking "/app/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2021-03-09T15:05:55.415Z INF/util:procutil 614 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2021-03-09T15:05:55.416Z INF/util:procutil 614 [*] Forking "/app/lib/cli provider --name a14dd3587790 --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2021-03-09T15:05:55.418Z INF/util:procutil 614 [*] Forking "/app/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2021-03-09T15:05:55.423Z INF/util:procutil 614 [*] Forking "/app/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2021-03-09T15:05:55.440Z INF/util:procutil 614 [*] Forking "/app/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2021-03-09T15:05:55.448Z INF/util:procutil 614 [*] Forking "/app/lib/cli groups-engine --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2021-03-09T15:05:55.461Z INF/util:procutil 614 [*] Forking "/app/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2021-03-09T15:05:55.477Z INF/util:procutil 614 [*] Forking "/app/lib/cli storage-temp --port 7102"
2021-03-09T15:05:55.483Z INF/util:procutil 614 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2021-03-09T15:05:55.501Z INF/util:procutil 614 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2021-03-09T15:05:55.514Z INF/util:procutil 614 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
lib/cli triproxy [name]
Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                              [string] [default: "a14dd3587790"]
Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).
Address already in use
2021-03-09T15:05:55.737Z FTL/cli:local 614 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2021-03-09T15:05:55.737Z INF/cli:local 614 [*] Shutting down all child `processes`

**Please run `stf doctor` and paste the output here.**

<img width="712" alt="Screenshot 2021-03-09 at 17 04 05" src="https://user-images.githubusercontent.com/7901760/110490955-78648e00-80f9-11eb-9740-7bd0a4523dff.png">

**Comment by denis99999** [comment]
@kevin32 you have to open the port range 7100:7120
