### ISSUE TITLE
STF app can't start on Android 12 DP3

### ISSUE THREAD

**Issue by Chadarr** [DeviceFarmer/stf#237]
**What is the issue or idea you have?**
STF app could not start on Pixel 4a Android 12 DP3 device

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
It happens only on a specific device
0A031JEC219410         device usb:338690048X product:sunfish model:Pixel_4a device:sunfish transport_id:2

**Please provide the steps to reproduce the issue.**
Update Pixel device to Android 12 DP via this instruction https://developer.android.com/about/versions/12/get
Connect Pixel to the existing and working STF service

**What is the expected behavior?**
The device appeared in the STF main UI and responsive to touches/other actions

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
Apr 27 09:39:11 raspberrypi docker[1444]: 2021-04-27T08:39:11.695Z INF/device 1286 [0A031JEC219410] Preparing device
Apr 27 09:39:12 raspberrypi docker[1444]: 2021-04-27T08:39:12.902Z INF/device:support:sub 1286 [0A031JEC219410] Receiving input from "tcp://stf.avp.ru:7250"
Apr 27 09:39:12 raspberrypi docker[1444]: 2021-04-27T08:39:12.908Z INF/device:support:sub 1286 [0A031JEC219410] Subscribing to permanent channel "*ALL"
Apr 27 09:39:12 raspberrypi docker[1444]: 2021-04-27T08:39:12.968Z INF/device:support:properties 1286 [0A031JEC219410] Loading properties
Apr 27 09:39:13 raspberrypi docker[1444]: 2021-04-27T08:39:13.007Z INF/device:support:sdk 1286 [0A031JEC219410] Supports SDK 31 (base 30, preview delta +1)
Apr 27 09:39:13 raspberrypi docker[1444]: 2021-04-27T08:39:13.009Z INF/device:support:abi 1286 [0A031JEC219410] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
Apr 27 09:39:13 raspberrypi docker[1444]: 2021-04-27T08:39:13.196Z INF/device:resources:minicap 1286 [0A031JEC219410] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/mi
Apr 27 09:39:13 raspberrypi docker[1444]: 2021-04-27T08:39:13.199Z INF/device:resources:minicap 1286 [0A031JEC219410] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-30/minicap.so" as "/dat
Apr 27 09:39:13 raspberrypi docker[1444]: 2021-04-27T08:39:13.424Z INF/device:resources:service 1286 [0A031JEC219410] Checking whether we need to install STFService
Apr 27 09:39:13 raspberrypi docker[1444]: 2021-04-27T08:39:13.466Z INF/device:resources:service 1286 [0A031JEC219410] Running version check
Apr 27 09:39:14 raspberrypi docker[1444]: 2021-04-27T08:39:14.543Z INF/device:resources:service 1286 [0A031JEC219410] Installing STFService
Apr 27 09:39:15 raspberrypi docker[1444]: 2021-04-27T08:39:15.696Z INF/device:resources:service 1286 [0A031JEC219410] STFService up to date
Apr 27 09:39:15 raspberrypi docker[1444]: 2021-04-27T08:39:15.701Z INF/device:plugins:service 1286 [0A031JEC219410] Launching agent
Apr 27 09:39:15 raspberrypi docker[1444]: 2021-04-27T08:39:15.851Z INF/provider 1 [*] Providing 7 of 8 device(s); waiting for "0A031JEC219410"
Apr 27 09:39:16 raspberrypi docker[1444]: 2021-04-27T08:39:16.226Z INF/device:plugins:service 1286 [0A031JEC219410] Agent says: "Starting minitouch agent"
Apr 27 09:39:25 raspberrypi docker[1444]: 2021-04-27T08:39:25.853Z INF/provider 1 [*] Providing 7 of 8 device(s); waiting for "0A031JEC219410"
Apr 27 09:39:26 raspberrypi docker[1444]: 2021-04-27T08:39:26.044Z FTL/device 1286 [0A031JEC219410] Setup had an error TimeoutError: operation timed out
Apr 27 09:39:26 raspberrypi docker[1444]:     at afterTimeout (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
Apr 27 09:39:26 raspberrypi docker[1444]:     at Timeout.timeoutTimeout [as _onTimeout] (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
Apr 27 09:39:26 raspberrypi docker[1444]:     at ontimeout (timers.js:466:11)
Apr 27 09:39:26 raspberrypi docker[1444]:     at tryOnTimeout (timers.js:304:5)
Apr 27 09:39:26 raspberrypi docker[1444]:     at Timer.listOnTimeout (timers.js:267:5)
Apr 27 09:39:26 raspberrypi docker[1444]: 2021-04-27T08:39:26.046Z FTL/util:lifecycle 1286 [0A031JEC219410] Shutting down due to fatal error
Apr 27 09:39:26 raspberrypi docker[1444]: 2021-04-27T08:39:26.082Z INF/provider 1 [*] Cleaning up device worker "0A031JEC219410"
Apr 27 09:39:26 raspberrypi docker[1444]: 2021-04-27T08:39:26.082Z ERR/provider 1 [*] Device worker "0A031JEC219410" died with code 1
Apr 27 09:39:26 raspberrypi docker[1444]: 2021-04-27T08:39:26.082Z INF/provider 1 [*] Restarting device worker "0A031JEC219410"

**Please run `stf doctor` and paste the output here.**
2021-04-27T08:51:45.375Z INF/cli:doctor 1344 [*] OS Arch: arm64
2021-04-27T08:51:45.381Z INF/cli:doctor 1344 [*] OS Platform: linux
2021-04-27T08:51:45.382Z INF/cli:doctor 1344 [*] OS Platform: 5.10.11-v8+
2021-04-27T08:51:45.383Z INF/cli:doctor 1344 [*] Using Node 9.9.0
2021-04-27T08:51:45.426Z INF/cli:doctor 1344 [*] Using ZeroMQ 4.3.2
2021-04-27T08:51:45.467Z ERR/cli:doctor 1344 [*] RethinkDB is not installed (`rethinkdb` is missing)
2021-04-27T08:51:45.468Z ERR/cli:doctor 1344 [*] ProtoBuf is not installed (`protoc` is missing)
2021-04-27T08:51:45.468Z ERR/cli:doctor 1344 [*] ADB is not installed (`adb` is missing)
2021-04-27T08:51:45.644Z INF/cli:doctor 1344 [*] Using GraphicsMagick 1.4
2021-04-27T08:51:45.648Z ERR/cli:doctor 1344 [*] Unexpected error checking GraphicsMagick: TypeError: Invalid Version: 1.4

Our STF is working via docker, so adb is present in a separate container, as well as rethinkdb and protobuf

------
Logcat from the aforementioned pixel is attached
[pixel_and12dp.log](https://github.com/DeviceFarmer/stf/files/6383258/pixel_and12dp.log)

**Comment by Chadarr** [comment]
Pixel 4a is currently in my possession, so I am able and more than happy to provide any additional logs and tests if there is a need

**Comment by rajdeepv** [comment]
I am facing the same issue on Android 12

**Comment by sudhalucky** [comment]
I think we need the latest minitouch.so and minicap.so build for Android-12 for STF to work

**Comment by Chadarr** [comment]
Seems like, but actually isn't
With new STF apk STFService is finally able to start, but when you try to take device from STF web console, aforementioned STFService crashes with this stacktrace

05-31 16:18:58.655  8312  8339 W .cyberagent.st: Accessing hidden method Landroid/view/IWindowManager$Stub$Proxy;->getDefaultDisplayRotation()I (max-target-o, reflection, denied)
05-31 16:18:58.655  8312  8339 W .cyberagent.st: Accessing hidden method Landroid/view/IWindowManager;->getDefaultDisplayRotation()I (max-target-o, reflection, denied)
05-31 16:18:58.655  8312  8339 W System.err: java.lang.NoSuchMethodException: android.view.IWindowManager$Stub$Proxy.getRotation []
05-31 16:18:58.655  8312  8339 W System.err: 	at java.lang.Class.getMethod(Class.java:2103)
05-31 16:18:58.655  8312  8339 W System.err: 	at java.lang.Class.getMethod(Class.java:1724)
05-31 16:18:58.656  8312  8339 W System.err: 	at jp.co.cyberagent.stf.compat.WindowManagerWrapper.getRotation(WindowManagerWrapper.java:65)
05-31 16:18:58.656  8312  8339 W System.err: 	at jp.co.cyberagent.stf.monitor.RotationMonitor.peek(RotationMonitor.java:54)
05-31 16:18:58.656  8312  8339 W System.err: 	at jp.co.cyberagent.stf.Service$Server$Connection.run(Service.java:369)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-31 16:18:58.656  8312  8339 W System.err: 	at java.lang.Thread.run(Thread.java:920)

**Comment by svyatoslavmo** [comment]
Any updates on this issue? Does stf support Android 12 emulators?

**Comment by matanbaruch** [comment]
@svyatoslavmo All emulators are supported
https://github.com/DeviceFarmer/stf/actions/runs/34631085540
