### ISSUE TITLE
Setup had an error TimeoutError: operation timed out

### ISSUE THREAD

**Issue by xycong520** [DeviceFarmer/stf#238]
**I have Magisk refresh installed on my device. When the device is connected to USB, a pop-up window on the STF admin page prompts Someone to steal your device. Then the STF error log shows:**
2021-04-28T01:17:39.249759931Z 2021-04-28T01:17:39.249Z INF/device 10547 [S47DBYKZ5HKBVCYT] Preparing device
2021-04-28T01:17:39.690974881Z 2021-04-28T01:17:39.690Z INF/device:support:sub 10547 [S47DBYKZ5HKBVCYT] Receiving input from "tcp://127.0.0.1:7114"
2021-04-28T01:17:39.697535105Z 2021-04-28T01:17:39.697Z INF/device:support:sub 10547 [S47DBYKZ5HKBVCYT] Subscribing to permanent channel "*ALL"
2021-04-28T01:17:39.752264894Z 2021-04-28T01:17:39.751Z INF/device:support:properties 10547 [S47DBYKZ5HKBVCYT] Loading properties
2021-04-28T01:17:39.780299636Z 2021-04-28T01:17:39.780Z INF/device:support:sdk 10547 [S47DBYKZ5HKBVCYT] Supports SDK 22
2021-04-28T01:17:39.780757225Z 2021-04-28T01:17:39.780Z INF/device:support:abi 10547 [S47DBYKZ5HKBVCYT] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2021-04-28T01:17:39.828623824Z 2021-04-28T01:17:39.828Z INF/device:resources:minicap 10547 [S47DBYKZ5HKBVCYT] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2021-04-28T01:17:39.829011169Z 2021-04-28T01:17:39.828Z INF/device:resources:minicap 10547 [S47DBYKZ5HKBVCYT] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-22/minicap.so" as "/data/local/tmp/minicap.so"
2021-04-28T01:17:39.942281466Z 2021-04-28T01:17:39.941Z INF/device:resources:service 10547 [S47DBYKZ5HKBVCYT] Checking whether we need to install STFService
2021-04-28T01:17:40.359512245Z 2021-04-28T01:17:40.359Z INF/device:resources:service 10547 [S47DBYKZ5HKBVCYT] Running version check
2021-04-28T01:17:40.974149597Z 2021-04-28T01:17:40.973Z INF/device:resources:service 10547 [S47DBYKZ5HKBVCYT] STFService up to date
2021-04-28T01:17:40.975929257Z 2021-04-28T01:17:40.975Z INF/device:plugins:service 10547 [S47DBYKZ5HKBVCYT] Launching agent
2021-04-28T01:17:51.030813021Z 2021-04-28T01:17:51.030Z FTL/device 10547 [S47DBYKZ5HKBVCYT] Setup had an error TimeoutError: operation timed out
2021-04-28T01:17:51.030878820Z     at afterTimeout (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
2021-04-28T01:17:51.030886650Z     at Timeout.timeoutTimeout [as _onTimeout] (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
2021-04-28T01:17:51.030892643Z     at ontimeout (timers.js:475:11)
2021-04-28T01:17:51.030897778Z     at tryOnTimeout (timers.js:310:5)
2021-04-28T01:17:51.030902916Z     at Timer.listOnTimeout (timers.js:270:5)
2021-04-28T01:17:51.031890177Z 2021-04-28T01:17:51.031Z FTL/util:lifecycle 10547 [S47DBYKZ5HKBVCYT] Shutting down due to fatal error
2021-04-28T01:17:51.044001157Z 2021-04-28T01:17:51.043Z INF/provider 38 [*] Cleaning up device worker "S47DBYKZ5HKBVCYT"
2021-04-28T01:17:51.044123759Z 2021-04-28T01:17:51.044Z ERR/provider 38 [*] Device worker "S47DBYKZ5HKBVCYT" died with code 1
2021-04-28T01:17:51.044237101Z 2021-04-28T01:17:51.044Z INF/provider 38 [*] Restarting device worker "S47DBYKZ5HKBVCYT"
2021-04-28T01:17:51.961946660Z 2021-04-28T01:17:51.960Z INF/device:support:push 10559 [S47DBYKZ5HKBVCYT] Sending output to "tcp://127.0.0.1:7116"
2021-04-28T01:17:51.964348982Z 2021-04-28T01:17:51.964Z INF/device 10559 [S47DBYKZ5HKBVCYT] Preparing device
2021-04-28T01:17:52.431066294Z 2021-04-28T01:17:52.430Z INF/device:support:sub 10559 [S47DBYKZ5HKBVCYT] Receiving input from "tcp://127.0.0.1:7114"
2021-04-28T01:17:52.432056927Z 2021-04-28T01:17:52.431Z INF/device:support:sub 10559 [S47DBYKZ5HKBVCYT] Subscribing to permanent channel "*ALL"
2021-04-28T01:17:52.487186693Z 2021-04-28T01:17:52.486Z INF/device:support:properties 10559 [S47DBYKZ5HKBVCYT] Loading properties
2021-04-28T01:17:52.514688898Z 2021-04-28T01:17:52.514Z INF/device:support:sdk 10559 [S47DBYKZ5HKBVCYT] Supports SDK 22
2021-04-28T01:17:52.515204682Z 2021-04-28T01:17:52.515Z INF/device:support:abi 10559 [S47DBYKZ5HKBVCYT] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2021-04-28T01:17:52.563634969Z 2021-04-28T01:17:52.563Z INF/device:resources:minicap 10559 [S47DBYKZ5HKBVCYT] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2021-04-28T01:17:52.564117488Z 2021-04-28T01:17:52.563Z INF/device:resources:minicap 10559 [S47DBYKZ5HKBVCYT] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-22/minicap.so" as "/data/local/tmp/minicap.so"
2021-04-28T01:17:52.685669510Z 2021-04-28T01:17:52.685Z INF/device:resources:service 10559 [S47DBYKZ5HKBVCYT] Checking whether we need to install STFService
2021-04-28T01:17:53.152035751Z 2021-04-28T01:17:53.151Z INF/device:resources:service 10559 [S47DBYKZ5HKBVCYT] Running version check
2021-04-28T01:17:53.799828643Z 2021-04-28T01:17:53.799Z INF/device:resources:service 10559 [S47DBYKZ5HKBVCYT] STFService up to date
How do I fix it ,Thinks!

**Comment by fjrKurniawan** [comment]
I'm facing same issue. Any update on this?
