### ISSUE TITLE
STF API getUser missing description field

### ISSUE THREAD

**Issue by le91688** [DeviceFarmer/stf#302]
**What is the issue or idea you have?**

When using a Swagger Codegen SDK (swagger-codegen-cli-2.3.1.jar  built for python) with a fresh STF deployment, calls to `User.getUser()` result in the following error:
```
Traceback (most recent call last):
  File "./codegen_controller.py", line 34, in <module>
    api_response = user_api.get_user()
  File "build/bdist.linux-x86_64/egg/swagger_client/api/user_api.py", line 931, in get_user
  File "build/bdist.linux-x86_64/egg/swagger_client/api/user_api.py", line 1002, in get_user_with_http_info
  File "build/bdist.linux-x86_64/egg/swagger_client/api_client.py", line 322, in call_api
  File "build/bdist.linux-x86_64/egg/swagger_client/api_client.py", line 161, in __call_api
  File "build/bdist.linux-x86_64/egg/swagger_client/api_client.py", line 233, in deserialize
  File "build/bdist.linux-x86_64/egg/swagger_client/api_client.py", line 272, in __deserialize
  File "build/bdist.linux-x86_64/egg/swagger_client/api_client.py", line 615, in __deserialize_model
  File "build/bdist.linux-x86_64/egg/swagger_client/models/user_response.py", line 54, in __init__
  File "build/bdist.linux-x86_64/egg/swagger_client/models/user_response.py", line 99, in description
ValueError: Invalid value for `description`, must not be `None`
```

This is because, the resulting json returned from the `GET api/v1/user` , is indeed missing a `description` field

here is the output from our deployment with certain info changed for privacy:
```
{"success":true,"user":{"createdAt":"2021-07-21T17:34:00.521Z","email":"joe@myorg.com","forwards":[],"group":"ourGroup==","groups":{"lock":false,"quotas":{"allocated":{"duration":1296000000,"number":5},"consumed":{"duration":0,"number":1},"defaultGroupsDuration":1296000000,"defaultGroupsNumber":5,"defaultGroupsRepetitions":10,"repetitions":10},"subscribed":["24f097abd4194119b50a2a57d0d77afb"]},"ip":"1.1.1.1","lastLoggedInAt":"2021-07-29T01:04:34.645Z","name":"Joe.User","privilege":"admin","settings":{"dateFormat":"M/d/yy h:mm:ss a","deviceListActiveTabs":{"details":true,"icons":false},"emailAddressSeparator":",","lastUsedDevice":"SOMEDEVICE"}}}
```

I've found a workaround for this, by manually editing the generated SDK python code
```
    @description.setter
    def description(self, description):
        """Sets the description of this UserResponse.


        :param description: The description of this UserResponse.  # noqa: E501
        :type: str
        """
        if description is None:
            description = "This field was missing!!!!"
            #raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description
```
This makes everything work fine, but the correct fix is to change the API unit so that calls to getUser return a `description` field as required by the Swagger2.0 spec, and I have no idea how to go about that.

**Please provide the steps to reproduce the issue.**

Generate swagger SDK for python from a new deployment, and attempt to call User.getUser() via the api

**What is the expected behavior?**
The generated JSON return data should include a `description` field, and the SDK code should parse that json data, and return it to you without errors.

**Comment by le91688** [comment]
Also noticed that `GET hostname/api/v1/devices?serial=<whatever>` returns JSON with a `devices` field, but not `device` field as required by the Swagger SDK
