### ISSUE TITLE
"Find Device" Button does not work on Android 11

### ISSUE THREAD

**Issue by p47-6** [DeviceFarmer/stf#336]
**What is the issue or idea you have?**
The find Device Button does not work on Android 11. Also the Battery Information only appears as soon as you opened the STF app manually on the phone by pulling down the notifications bar and click on the STF Service Notification.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
device usb:1-2.3 product:OnePlus9Pro_EEA model:LE2123 device:OnePlus9Pro transport_id:6
device usb:1-2.4 product:beyond1lteeea model:SM_G973F device:beyond1 transport_id:1

(serials removed for privacy)

**Please provide the steps to reproduce the issue.**
Just click on the "Find Device" Button in the Info Pane of the Device

**What is the expected behavior?**
It should show the red Info Screen on the Device.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
I've actually never tried it with stf local but the stf provider throws a timeout:
```
Unhandled rejection TimeoutError: operation timed out
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
From previous event:
    at EventEmitter.plugin.identity (/app/lib/units/device/plugins/service.js:486:10)
    at Router.<anonymous> (/app/lib/units/device/plugins/service.js:718:20)
    at Router.emit (/app/node_modules/eventemitter3/index.js:118:35)
    at Router.<anonymous> (/app/lib/wire/router.js:36:12)
    at emitTwo (events.js:126:13)
    at exports.Socket.emit (events.js:214:7)
    at exports.Socket.Socket._flushRead (/app/node_modules/zmq/lib/index.js:638:15)
    at exports.Socket.Socket._flushReads (/app/node_modules/zmq/lib/index.js:676:23)
    at Object._zmq.onReadReady (/app/node_modules/zmq/lib/index.js:297:10)
```

**Please run `stf doctor` and paste the output here.**
```
2021-10-13T14:13:41.597Z INF/cli:doctor 124 [*] OS Arch: x64
2021-10-13T14:13:41.604Z INF/cli:doctor 124 [*] OS Platform: linux
2021-10-13T14:13:41.605Z INF/cli:doctor 124 [*] OS Platform: 5.11.0-37-generic
2021-10-13T14:13:41.605Z INF/cli:doctor 124 [*] Using Node 8.9.3
2021-10-13T14:13:41.657Z INF/cli:doctor 124 [*] Using ZeroMQ 4.1.4
2021-10-13T14:13:41.724Z ERR/cli:doctor 124 [*] RethinkDB is not installed (`rethinkdb` is missing)
2021-10-13T14:13:41.724Z ERR/cli:doctor 124 [*] ProtoBuf is not installed (`protoc` is missing)
2021-10-13T14:13:41.725Z ERR/cli:doctor 124 [*] ADB is not installed (`adb` is missing)
2021-10-13T14:13:41.728Z INF/cli:doctor 124 [*] Using GraphicsMagick 1.3.23
```

Rethinkdb: 2.3

docker exec -it stf_adb_1 adb version
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133

**Comment by p47-6** [comment]
After digging a little bit deeper into this it seems like the app does not have enough permissions to bring an app into foreground.
(https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW)
