### ISSUE TITLE
Clicking on ui doesn't work on Android 12

### ISSUE THREAD

**Issue by Jcouto33** [DeviceFarmer/stf#343]
**What is the issue or idea you have?**

When I use STF on android 12 device, the display is correctly displayed but it's not possible to click on the screen. 

**Please provide the steps to reproduce the issue.**

1) Start STF
2) Connect Android 12 device
3) Try to click on screen but nothing append

**What is the expected behavior?**

When click on screen I expect screen change like on Android 10/11

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
2021-10-28T08:23:02.676Z IMP/device:plugins:connect 167 [emulator-5554] Remote Connect Started for device "emulator-5554" at "tldlab241.tls.renault.fr:7450"
2021-10-28T08:23:02.939Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "Failed to instantiate [ch.qos.logback.classic.LoggerContext]"
2021-10-28T08:23:02.939Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "Reported exception:"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "java.lang.ArrayIndexOutOfBoundsException: length=0; index=0"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at android.os.Environment.getExternalStorageState(Environment.java:1208)"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at ch.qos.logback.core.android.AndroidContextUtil.getMountedExternalStorageDirectoryPath(Unknown Source:0)"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at ch.qos.logback.core.android.AndroidContextUtil.setupProperties(Unknown Source:14)"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source:12)"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source:7)"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source:20)"
2021-10-28T08:23:02.940Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at org.slf4j.impl.StaticLoggerBinder.getSingleton(Unknown Source:0)"
2021-10-28T08:23:02.941Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)"
2021-10-28T08:23:02.941Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)"
2021-10-28T08:23:02.944Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)"
2021-10-28T08:23:02.944Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)"
2021-10-28T08:23:02.944Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at io.devicefarmer.minicap.provider.BaseProvider.<clinit>(BaseProvider.kt:43)"
2021-10-28T08:23:02.944Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at io.devicefarmer.minicap.Main$Companion.main(Main.kt:61)"
2021-10-28T08:23:02.945Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at io.devicefarmer.minicap.Main.main(Unknown Source:2)"
2021-10-28T08:23:02.945Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)"
2021-10-28T08:23:02.945Z INF/device:plugins:screen:stream 167 [emulator-5554] minicap says: "	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)"

**Comment by siva-kranthi** [comment]
Facing a similar issue. Please help us

**Comment by childnode** [comment]
perhaps related to scrcopy 

actually minicap is not built and updated correct for new versions 31+

https://github.com/DeviceFarmer/stf/blob/master/package.json#L39

see https://github.com/DeviceFarmer/minicap/issues/34 for gathered details
