### ISSUE TITLE
Run the reaper process manually?

### ISSUE THREAD

**Issue by man4567890** [DeviceFarmer/stf#361]
All my deployments are remote, IE all the computers where the devices are connect to, work via a network, The remotes are all connected to the main STF server on the network. When the network disconnects or has a problem and the remote computer reboots, it seems that the reaper process does not "re-reap" the device? 
All I see in the logfile is this below

```
marketName: 'Galaxy Grand Prime Plus',
  display: 
   { id: 0,
     width: 540,
     height: 960,
     xdpi: 214.31199645996094,
     ydpi: 221.67201232910156,
     fps: 59.71000289916992,
     density: 1.5,
     rotation: 0,
     secure: true,
     size: 5.0103893082791755,
     url: 'ws://10.70.11.168:7448' },
  phone: { network: 'UNKNOWN' } }
2021-11-23T09:18:12.914Z INF/device:plugins:touch 8948 [920104a528b235ad] Touch origin is top left
2021-11-23T09:18:12.916Z INF/device:plugins:touch 8948 [920104a528b235ad] Requesting touch consumer to start
2021-11-23T09:18:12.918Z INF/device:plugins:touch 8948 [920104a528b235ad] Launching touch service
2021-11-23T09:18:13.100Z INF/device:plugins:touch 8948 [920104a528b235ad] Connecting to minitouch service
2021-11-23T09:18:13.283Z INF/device:plugins:touch 8948 [920104a528b235ad] minitouch says: "Type B touch device sec_touchscreen (539x959 with 2 contacts) detected on /dev/input/event4 (score 21719)"
2021-11-23T09:18:13.387Z INF/device:plugins:touch 8948 [920104a528b235ad] minitouch says: "Connection established"
2021-11-23T09:18:13.391Z INF/device:plugins:touch 8948 [920104a528b235ad] Reading minitouch banner
2021-11-23T09:18:13.403Z INF/device:plugins:vnc 8948 [920104a528b235ad] Starting VNC server on port 7450
2021-11-23T09:18:13.408Z INF/device:plugins:browser 8948 [920104a528b235ad] Loading browser list
2021-11-23T09:18:13.496Z INF/device:plugins:browser 8948 [920104a528b235ad] Updating browser list
2021-11-23T09:18:13.504Z INF/device:plugins:mute 8948 [920104a528b235ad] Will not mute master volume
2021-11-23T09:18:13.719Z INF/device:resources:minirev 8948 [920104a528b235ad] Installing "/usr/lib/node_modules/stf/vendor/minirev/armeabi-v7a/minirev" as "/data/local/tmp/minirev"
2021-11-23T09:18:14.298Z INF/device:plugins:forward 8948 [920104a528b235ad] Launching reverse port forwarding service
2021-11-23T09:18:14.478Z INF/device:plugins:forward 8948 [920104a528b235ad] Connecting to reverse port forwarding service
2021-11-23T09:18:14.584Z INF/device 8948 [920104a528b235ad] Fully operational
2021-11-23T09:18:15.855Z INF/provider 2776 [*] Providing all 1 device(s)
2021-11-23T09:19:11.309Z WRN/device:plugins:touch 8948 [920104a528b235ad] Shell keeping minitouch running ended unexpectedly
2021-11-23T09:19:11.311Z INF/device:plugins:touch 8948 [920104a528b235ad] Disconnecting from minitouch service
2021-11-23T09:19:11.316Z IMP/device:plugins:service 8948 [920104a528b235ad] Agent connection ended, attempting to relaunch
2021-11-23T09:19:11.317Z INF/device:plugins:service 8948 [920104a528b235ad] Launching service
2021-11-23T09:19:11.318Z INF/device:plugins:service 8948 [920104a528b235ad] using 'startservice' command for API 23
2021-11-23T09:19:11.319Z FTL/util:lifecycle 2776 [*] Tracker had an error Error: Connection closed
2021-11-23T09:56:02.770Z INF/provider 21957 [*] Subscribing to permanent channel "gmroBu9+SX2Iopb1s4eBAw=="
2021-11-23T09:56:02.798Z INF/provider 21957 [*] Sending output to "tcp://127.0.0.1:7116"
2021-11-23T09:56:02.800Z INF/provider 21957 [*] Receiving input from "tcp://127.0.0.1:7114"
2021-11-23T09:56:05.830Z INF/provider 21957 [*] Tracking devices
2021-11-23T09:57:26.364Z FTL/util:lifecycle 21957 [*] Tracker had an error Error: Connection closed
    at /usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/lib/adb/tracker.js:21:13
    at tryCatcher (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2021-11-23T09:57:26.365Z FTL/util:lifecycle 21957 [*] Shutting down due to fatal error
2021-11-23T09:58:02.174Z INF/provider 22680 [*] Subscribing to permanent channel "GbqnTwbZSnyDpENxNP0tLQ=="
2021-11-23T09:58:02.202Z INF/provider 22680 [*] Sending output to "tcp://127.0.0.1:7116"
2021-11-23T09:58:02.203Z INF/provider 22680 [*] Receiving input from "tcp://127.0.0.1:7114"
2021-11-23T09:58:05.236Z INF/provider 22680 [*] Tracking devices


2021-11-23T09:59:02.276Z INF/provider 22936 [*] Subscribing to permanent channel "UvLinnzdSm+Mg5vulY/3fg=="
2021-11-23T09:59:02.303Z INF/provider 22936 [*] Sending output to "tcp://127.0.0.1:7116"
2021-11-23T09:59:02.304Z INF/provider 22936 [*] Receiving input from "tcp://127.0.0.1:7114"
2021-11-23T09:59:05.333Z INF/provider 22936 [*] Tracking devices
```

Restarting the device, adb server, remote computer does not seem the help, the only way I can get the device back is to restart the main server. Even killing all the stf processes and starting them again on the main server does not help.
Any way or running the reaper process manually please?

**Comment by denis99999** [comment]
@man4567890 ,

Yes, the `reaper `"re-reap" the device after a while once the network connection is established again, anyway on my side I have tested it and it works.
Regards.

**Comment by man4567890** [comment]
Any way to kick it off manually please

**Comment by denis99999** [comment]
@man4567890 

I assume the same way you started it the first time, which I don't know... can you correctly fill in the recommended issue template and the commands you used to start STF on each side.

What is strange is that you say that your deployment is distributed on the network, except that the logs of your provider indicate loopback addresses?

Refer to the `DEPLOYMENT.md` documention where everything is sufficiently explained, you can also use the online help `stf reaper --help`

**Comment by man4567890** [comment]
Yea, I open a lot of tunnels, ok I will have a look at stf reaper --help, thanks so much for the help

**Comment by man4567890** [comment]
Hi @denis99999 ,
The problem seems to be with STF 3.6.1, when I switch in STF 3.4.x, I can see the devices, but with STF 3.6.1 about 8 out 55 devices are not available, in rethinkDB. the devices is marked as 
 ```
"platform": "Android" ,
"presenceChangedAt": Wed Mar 16 2022 07:20:30 GMT+00:00 ,
"present": false ,
"product": "starqltesq" ,
"provider": {

    "channel": "YNg6QjrQSXmK2Up1I9aUPQ==" ,
    "name": "controller-2377265048"

} ,
"ready": true ,
"remoteConnect": false ,
"remoteConnectUrl": null ,
"reverseForwards": [ ],
"sdk": "26" ,
"serial": "4c39533735313498" ,
"status": 3 ,
"statusChangedAt": Wed Mar 16 2022 07:17:04 GMT+00:00 ,
"usage": null ,
"usageChangedAt": Tue Mar 15 2022 16:53:53 GMT+00:00 ,
"version": "8.0.0"  
```

In STF it is
![image](https://user-images.githubusercontent.com/53390181/158542903-c3467950-094e-4d57-8030-847e8dbe15e5.png)

I setup tunnels to the various controllers, the devices are plugged into the controllers, for example, a working one
![image](https://user-images.githubusercontent.com/53390181/158543330-0cf313b0-1455-4d91-83d5-32f4a1c6645c.png)

From rethinkDB
```
     "openGLESVersion": "3.1" ,
    "operator": "xxxxxx" ,
    "owner": null ,
    "phone": {
        "iccid": null ,
        "imei": null ,
        "imsi": null ,
        "network": "LTE" ,
        "phoneNumber": null
    } ,
    "platform": "Android" ,
    "presenceChangedAt": Wed Mar 16 2022 07:12:27 GMT+00:00 ,
    "present": true ,
    "product": "hero2qlteusc" ,
    "provider": {
        "channel": "aldBS/VDQsiI+NA8NBYE6Q==" ,
        "name": "controller-3779325013"
    } ,
    "ready": true ,
    "remoteConnect": false ,
    "remoteConnectUrl": null ,
    "reverseForwards": [ ],
    "sdk": "23" ,
    "serial": "f984bb7b" ,
    "status": 3 ,
    "statusChangedAt": Wed Mar 16 2022 07:00:12 GMT+00:00 ,
    "usage": null ,
    "version": "6.0.1"

}
```

```
ps -ef | grep "controller-3779325013"
+ 17136 19873  0 02:14 ?        00:00:02 /usr/bin/node /usr/lib/node_modules/stf/lib/cli device --serial f984bb7b --provider controller-3779325013 --screen-port 7536 --connect-port 7537 --vnc-port 7538 --public-ip 10.189.12.81 --group-timeout 900 --storage-url http://127.0.0.1:7100/ --adb-host 127.0.0.1 --adb-port 5080 --screen-jpeg-quality 80 --screen-ping-interval 30000 --screen-ws-url-pattern ws://${publicIp}:${publicPort} --connect-url-pattern ${publicIp}:${publicPort} --heartbeat-interval 10000 --boot-complete-timeout 60000 --vnc-initial-size 600x800 --mute-master never --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --no-cleanup

+ 19873     1  0 02:00 ?        00:00:01 node /usr/local/bin/stf provider --name controller-3779325013 --no-cleanup --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.189.12.81 --storage-url http://127.0.0.1:7100/ --adb-host 127.0.0.1 --adb-port 5080 --vnc-initial-size 600x800 --mute-master never --allow-remote
```

And the tunnels to the remote controller
```
ps -ef | grep -w "10.188.36.6" | grep -v grep
+ 21858     1  0 Mar15 ?        00:00:09 ssh -fN xx@10.188.36.6 -L 127.0.0.1:1143:127.0.0.1:22 -L 127.0.0.1:5080:127.0.0.1:5037 -L :13043:127.0.0.1:8091 -L :12043:127.0.0.1:8090 -L :4243:127.0.0.1:4200

```
For the one that does not appear on STF, the /usr/bin/node /usr/lib/node_modules/stf/lib/cli device is missing

for example 
```
ps -ef | grep "controller-2377265048" | grep -v grep
+ 13546     1  0 02:20 ?        00:00:00 node /usr/local/bin/stf provider --name controller-2377265048 --no-cleanup --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.189.12.81 --storage-url http://127.0.0.1:7100/ --adb-host 127.0.0.1 --adb-port 5063 --vnc-initial-size 600x800 --mute-master never --allow-remote

ps -ef | grep "10.188.36.31" | grep -v grep
+ 24030     1  0 02:44 ?        00:00:00 ssh -fN xx@10.188.36.31 -L 127.0.0.1:1126:127.0.0.1:22 -L 127.0.0.1:5063:127.0.0.1:5037 -L :13026:127.0.0.1:8091 -L :12026:127.0.0.1:8090 -L :4226:127.0.0.1:4200

```
When I try and launch the command manually, I get device not found
```
/usr/bin/node /usr/lib/node_modules/stf/lib/cli device --serial 4c39533735313498 --provider controller-3692221693 --screen-port 7568 --connect-port 7569 --vnc-port 7570 --public-ip 10.189.12.81 --group-timeout 900 --storage-url http://127.0.0.1:7100/ --adb-host 127.0.0.1 --adb-port 5055 --screen-jpeg-quality 80 --screen-ping-interval 30000 --screen-ws-url-pattern ws://${publicIp}:${publicPort} --connect-url-pattern ${publicIp}:${publicPort} --heartbeat-interval 10000 --boot-complete-timeout 60000 --vnc-initial-size 600x800 --mute-master never --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --no-cleanup
2022-03-16T08:17:36.573Z INF/device:support:push 31393 [4c39533735313498] Sending output to "tcp://127.0.0.1:7116"
2022-03-16T08:17:36.577Z INF/device 31393 [4c39533735313498] Preparing device
2022-03-16T08:17:37.212Z INF/device:support:sub 31393 [4c39533735313498] Receiving input from "tcp://127.0.0.1:7114"
2022-03-16T08:17:37.215Z INF/device:support:sub 31393 [4c39533735313498] Subscribing to permanent channel "*ALL"
2022-03-16T08:17:37.366Z FTL/device 31393 [4c39533735313498] Setup had an error FailError: Failure: 'device '4c39533735313498' not found'
    at /usr/lib/node_modules/stf/node_modules/@devicefarmer/adbkit/lib/adb/parser.js:183:29
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2022-03-16T08:17:37.367Z FTL/util:lifecycle 31393 [4c39533735313498] Shutting down due to fatal error

```
And the device above worked on STF 3.4.x

So my question would be, what happens when a device comes on line, where does STF *see* the device and start to reap it, does the device need to be in a certain state in rethinkDB to be reaped?
From the logfile when I started STF 3.6.1, for that device I see

```
cat /var/log/stf/stf.log | grep 4c39533735313498
2022-03-16T07:00:04.890Z INF/reaper 15652 [reaper001] Reaping device "4c39533735313498" due to heartbeat timeout
2022-03-16T07:00:07.325Z INF/reaper 15652 [reaper001] Device "4c39533735313498" is present
2022-03-16T07:13:29.729Z INF/reaper 15652 [reaper001] Reaping device "4c39533735313498" due to heartbeat timeout
2022-03-16T07:16:31.934Z INF/reaper 15652 [reaper001] Device "4c39533735313498" is present
2022-03-16T07:17:01.935Z INF/reaper 15652 [reaper001] Reaping device "4c39533735313498" due to heartbeat timeout
2022-03-16T07:17:04.028Z INF/reaper 15652 [reaper001] Device "4c39533735313498" is present
2022-03-16T07:17:45.297Z INF/reaper 15652 [reaper001] Reaping device "4c39533735313498" due to heartbeat timeout
2022-03-16T07:18:30.271Z INF/reaper 15652 [reaper001] Device "4c39533735313498" is present
2022-03-16T07:20:30.355Z INF/reaper 15652 [reaper001] Reaping device "4c39533735313498" due to heartbeat timeout

```
But the device is off line, I also start a logfile on the controller side and this is what I get
```
cat controller-2377265048
2022-03-16T07:20:04.738Z INF/provider 13546 [*] Subscribing to permanent channel "xCA4LIAjS9K0Nt7LtKoYdw=="
2022-03-16T07:20:04.767Z INF/provider 13546 [*] Sending output to "tcp://127.0.0.1:7116"
2022-03-16T07:20:04.768Z INF/provider 13546 [*] Receiving input from "tcp://127.0.0.1:7114"
2022-03-16T07:20:07.791Z INF/provider 13546 [*] Tracking devices
```

**Comment by man4567890** [comment]
I forgot to add, on the controller I can see the device as well

```
ssh xx@controller-3692221693
Warning: Permanently added 'controller-3692221693,10.188.36.56' (ECDSA) to the list of known hosts.
xx@controller-3692221693's password: 
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have new mail.
Last login: Tue Mar 15 12:18:23 2022 from 127.0.0.1

 adb devices -l
List of devices attached
4c39533735313498       device usb:1-1.1.2 product:starqltesq model:SM_G960U device:starqltesq transport_id:1

 adb shell
starqltesq:/ $ ls -ltr
total 4956
-rw-r--r--   1 root   root       524 1969-12-31 18:00 verity_key
drwxr-xr-x  14 root   root      4096 1969-12-31 18:00 vendor
-rw-r--r--   1 root   root      5439 1969-12-31 18:00 ueventd.rc
drwxr-xr-x  25 root   root      4096 1969-12-31 18:00 system
-rw-r--r--   1 root   root      1030 1969-12-31 18:00 sepolicy_version
lrwxrwxrwx   1 root   root        21 1969-12-31 18:00 sdcard -> /storage/self/primary
drwxr-x---   2 root   root         0 1969-12-31 18:00 sbin
drwxr-xr-x   3 root   root         0 1969-12-31 18:00 res
-rw-r--r--   1 root   root      1509 1969-12-31 18:00 publiccert.pem
dr-xr-xr-x 663 root   root         0 1969-12-31 18:00 proc
-rw-r--r--   1 root   root      2088 1969-12-31 18:00 postrecovery.do
drwxr-xr-x   3 root   root         0 1969-12-31 18:00 oem
drwxr-xr-x   7 root   root      4096 1969-12-31 18:00 odm
-rwxr-x---   1 root   root      2146 1969-12-31 18:00 init.zygote64_32.rc
-rwxr-x---   1 root   root       535 1969-12-31 18:00 init.zygote32.rc
-rwxr-x---   1 root   root      4076 1969-12-31 18:00 init.wifi.rc
-rwxr-x---   1 root   root      5773 1969-12-31 18:00 init.usb.rc
-rwxr-x---   1 root   root     11011 1969-12-31 18:00 init.usb.configfs.rc
-rwxr-x---   1 root   root      1674 1969-12-31 18:00 init.recovery.qcom.rc
-rwxr-x---   1 root   root     89690 1969-12-31 18:00 init.rc
-rwxr-x---   1 root   root      1771 1969-12-31 18:00 init.environ.rc
-rwxr-x---   1 root   root      3201 1969-12-31 18:00 init.container.rc
-rwxr-x---   1 root   root   4762672 1969-12-31 18:00 init
dr-xr-x---   4 root   system   16384 1969-12-31 18:00 firmware-modem
dr-xr-x---   4 root   system   16384 1969-12-31 18:00 firmware
lrwxrwxrwx   1 root   root        11 1969-12-31 18:00 etc -> /system/etc
drwxr-xr-x   6 root   root      4096 1969-12-31 18:00 dsp
lrwxrwxrwx   1 root   root        23 1969-12-31 18:00 default.prop -> system/etc/prop.default
lrwxrwxrwx   1 root   root        17 1969-12-31 18:00 d -> /sys/kernel/debug
lrwxrwxrwx   1 root   root        13 1969-12-31 18:00 charger -> /sbin/charger
drwxrwx--x   3 system system    4096 1969-12-31 18:00 carrier
lrwxrwxrwx   1 root   root        50 1969-12-31 18:00 bugreports -> /data/user_de/0/com.android.shell/files/bugreports
drwxr-xr-x   2 root   root         0 1969-12-31 18:00 bt_firmware
-rw-r--r--   1 root   root     43632 1969-12-31 18:00 audit_filter_table
-rw-r--r--   1 root   root       225 1969-12-31 18:00 android.hardware.drm@1.0-service.widevine.rc
drwxr-xr-x   5 root   root         0 1969-12-31 18:00 config
drwxrwx--x   3 system system    4096 2017-12-31 18:00 omr
drwxrwx---   4 system system    4096 2017-12-31 18:00 dqmdbg
drwxrwx---   7 system cache     4096 2017-12-31 18:00 cache
drwxrwx--x  18 root   system    4096 2017-12-31 18:00 persist
dr-xr-xr-x  13 root   root         0 2018-03-27 10:20 sys
lrwxrwxrwx   1 root   root        16 2018-03-27 10:20 tombstones -> /data/tombstones
drwxrwx--x   2 system system       0 2018-03-27 10:20 preload
drwxr-xr-x  12 root   system     260 2018-03-27 10:20 mnt
dr-xr-xr-x 127 root   root         0 2018-03-27 10:20 acct
drwxr-xr-x  18 root   root      5160 2018-03-27 10:20 dev
drwx------   2 root   root         0 2018-11-25 23:13 root
drwxrwx--x  29 system radio     4096 2020-04-07 16:32 efs
drwxrwx--x  58 system system    4096 2022-03-16 02:41 data
drwxr-xr-x   5 root   root       100 2022-03-16 02:41 storage
starqltesq:/ $ 
```

**Comment by trungnghia2121** [comment]
@man4567890 @denis99999  How to solve the above problem? help me

**Comment by denis99999** [comment]
@man4567890 database model has changed from `v3.4.2` by introducing the "group feature", perhaps it explains your issue, ideally you should rebuild your database from scratch, at least you can try to delete your 8/55 devices from the database and restart STF, ensure also you have the same version for all STF nodes, do you use the official docker image of STF or did you build your own image ? In this last case, you have to use a recent version of Node (e.g. 17.9.0).
