### ISSUE TITLE
stf installation in cent os 7 - not detecting zeromq and protobuf 

### ISSUE THREAD

**Issue by siva89r** [DeviceFarmer/stf#378]
i am installing stf in Linux server. cent os 7.  

Npm install and npm link is working fine. when i start stf application i get the below error.

```
2021-12-20T13:28:32.211Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli migrate"
2021-12-20T13:28:32.481Z INF/db 22139 [*] Connecting to 127.0.0.1:28015
2021-12-20T13:28:32.498Z INF/db:setup 22139 [*] Database "stf" already exists
2021-12-20T13:28:32.503Z INF/db:setup 22139 [*] Table "users" already exists
2021-12-20T13:28:32.503Z INF/db:setup 22139 [*] Table "accessTokens" already exists
2021-12-20T13:28:32.503Z INF/db:setup 22139 [*] Table "vncauth" already exists
2021-12-20T13:28:32.504Z INF/db:setup 22139 [*] Table "devices" already exists
2021-12-20T13:28:32.504Z INF/db:setup 22139 [*] Table "logs" already exists
2021-12-20T13:28:32.504Z INF/db:setup 22139 [*] Table "groups" already exists
2021-12-20T13:28:32.515Z INF/db:setup 22139 [*] Index "users"."adbKeys" already exists
2021-12-20T13:28:32.515Z INF/db:setup 22139 [*] Index "accessTokens"."email" already exists
2021-12-20T13:28:32.515Z INF/db:setup 22139 [*] Index "vncauth"."response" already exists
2021-12-20T13:28:32.515Z INF/db:setup 22139 [*] Index "vncauth"."responsePerDevice" already exists
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Index "devices"."owner" already exists
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Index "devices"."logs_enabled" already exists
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Index "devices"."present" already exists
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Index "devices"."providerChannel" already exists
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Index "devices"."group" already exists
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Index "groups"."privilege" already exists
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Waiting for index "users"."adbKeys"
2021-12-20T13:28:32.516Z INF/db:setup 22139 [*] Waiting for index "accessTokens"."email"
2021-12-20T13:28:32.517Z INF/db:setup 22139 [*] Waiting for index "vncauth"."response"
2021-12-20T13:28:32.517Z INF/db:setup 22139 [*] Waiting for index "vncauth"."responsePerDevice"
2021-12-20T13:28:32.517Z INF/db:setup 22139 [*] Waiting for index "devices"."owner"
2021-12-20T13:28:32.517Z INF/db:setup 22139 [*] Waiting for index "devices"."logs_enabled"
2021-12-20T13:28:32.518Z INF/db:setup 22139 [*] Waiting for index "devices"."present"
2021-12-20T13:28:32.518Z INF/db:setup 22139 [*] Waiting for index "devices"."providerChannel"
2021-12-20T13:28:32.518Z INF/db:setup 22139 [*] Waiting for index "devices"."group"
2021-12-20T13:28:32.518Z INF/db:setup 22139 [*] Waiting for index "groups"."privilege"
2021-12-20T13:28:32.520Z INF/db:setup 22139 [*] Index "groups"."owner" already exists
2021-12-20T13:28:32.520Z INF/db:setup 22139 [*] Index "groups"."startTime" already exists
2021-12-20T13:28:32.521Z INF/db:setup 22139 [*] Index "users"."adbKeys" is ready
2021-12-20T13:28:32.521Z INF/db:setup 22139 [*] Index "accessTokens"."email" is ready
2021-12-20T13:28:32.521Z INF/db:setup 22139 [*] Waiting for index "groups"."owner"
2021-12-20T13:28:32.521Z INF/db:setup 22139 [*] Waiting for index "groups"."startTime"
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "vncauth"."response" is ready
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "vncauth"."responsePerDevice" is ready
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "devices"."owner" is ready
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "devices"."logs_enabled" is ready
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "devices"."present" is ready
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "devices"."providerChannel" is ready
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "devices"."group" is ready
2021-12-20T13:28:32.523Z INF/db:setup 22139 [*] Index "groups"."privilege" is ready
2021-12-20T13:28:32.524Z INF/db:setup 22139 [*] Index "groups"."owner" is ready
2021-12-20T13:28:32.524Z INF/db:setup 22139 [*] Index "groups"."startTime" is ready
2021-12-20T13:28:33.546Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2021-12-20T13:28:33.548Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2021-12-20T13:28:33.550Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2021-12-20T13:28:33.551Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2021-12-20T13:28:33.553Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2021-12-20T13:28:33.565Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli provider --name example.com --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 7200 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never --no-cleanup --no-screen-reset"
2021-12-20T13:28:33.577Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli auth-mock --port 7120 --secret mySecretCode --app-url http://localhost:7100/"
2021-12-20T13:28:33.584Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli app --port 7105 --secret mySecretCode --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2021-12-20T13:28:33.594Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli api --port 7106 --secret mySecretCode --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2021-12-20T13:28:33.605Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli groups-engine --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2021-12-20T13:28:33.614Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli websocket --port 7110 --secret mySecretCode --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2021-12-20T13:28:33.633Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli storage-temp --port 7102"
2021-12-20T13:28:33.644Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2021-12-20T13:28:33.663Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2021-12-20T13:28:33.682Z INF/util:procutil 22132 [*] Forking "/home/siva/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                [string] [default: "example.com"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

No native build was found for platform=linux arch=x64 runtime=node abi=57 uv=1 libc=glibc node=8.17.0
    loaded from: /home/siva/stf/node_modules/zeromq

2021-12-20T13:28:34.272Z FTL/cli:local 22132 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/siva/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2021-12-20T13:28:34.272Z INF/cli:local 22132 [*] Shutting down all child processes
lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                [string] [default: "example.com"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

No native build was found for platform=linux arch=x64 runtime=node abi=57 uv=1 libc=glibc node=8.17.0
    loaded from: /home/siva/stf/node_modules/zeromq
```

Stf doctor output :

```
$ stf doctor
2021-12-20T13:46:01.304Z INF/cli:doctor 23274 [*] OS Arch: x64
2021-12-20T13:46:01.306Z INF/cli:doctor 23274 [*] OS Platform: linux
2021-12-20T13:46:01.306Z INF/cli:doctor 23274 [*] OS Platform: 3.10.0-1160.49.1.el7.x86_64
2021-12-20T13:46:01.307Z INF/cli:doctor 23274 [*] Using Node 8.17.0
2021-12-20T13:46:01.330Z ERR/cli:doctor 23274 [*] Unexpected error checking ZeroMQ: Error: No native build was found for platform=linux arch=x64 runtime=node abi=57 uv=1 libc=glibc node=8.17.0
    loaded from: /home/siva/stf/node_modules/zeromq

2021-12-20T13:46:01.331Z ERR/cli:doctor 23274 [*] ProtoBuf is not installed (`protoc` is missing)
2021-12-20T13:46:01.332Z INF/cli:doctor 23274 [*] Using ADB 1.0.41
2021-12-20T13:46:01.332Z INF/cli:doctor 23274 [*] Using GraphicsMagick 1.3.36
2021-12-20T13:46:01.332Z INF/cli:doctor 23274 [*] Using RethinkDB 2.4.1

```

Zeromq and protobuf installation details :
(Used **sudo yum** for installing all dependencies for stf)

```
$ rpm -qa | grep -E "zeromq|protobuf"
zeromq-devel-4.1.4-6.el7.x86_64
zeromq-4.1.4-6.el7.x86_64
protobuf-2.5.0-8.el7.x86_64

```

I could see that ZeroMQ and ProtoBuf is not detected by stf doctor. (but it is already installed ). Is that the issue for the above exception ?  how to identify the exception and get the application started ?

**Comment by denis99999** [comment]
difficult to answer you on this integration problem on this OS, I will nevertheless recommend you to use STF embedded in a docker image, it would be easier unless you want to do development on STF
