### ISSUE TITLE
Cannot install certain app using `App Upload` feature

### ISSUE THREAD

**Issue by jay0129** [DeviceFarmer/stf#392]
**What is the issue or idea you have?**
I cannot use `App Upload` feature
I cannot upload app, which is 243.7MB 
**Reproduction Ratio: 9/10**
*Picture when I cannot upload app:*
![image](https://user-images.githubusercontent.com/62974859/148922427-681099c2-3b69-4c76-a2bf-52cea9c4dd86.png)

**Note**
- By the way, I can upload app, which is 12MB and it is automatically installed (10/10)
- Installing the same app using adb command was successful
  - adb install ~/Downloads/apps/my_app.apk

**What is the expected behavior?**
- Can upload app, which is 243.7 MB, and it should be automatically installed.

**Please run `stf doctor` and paste the output here.**
```
stf@c41347bcc85a:/app$ stf doctor
2021-09-06T05:38:09.928Z INF/cli:doctor 31 [*] OS Arch: x64
2021-09-06T05:38:09.929Z INF/cli:doctor 31 [*] OS Platform: linux
2021-09-06T05:38:09.929Z INF/cli:doctor 31 [*] OS Platform: 5.11.0-27-generic
2021-09-06T05:38:09.929Z INF/cli:doctor 31 [*] Using Node 8.9.3
2021-09-06T05:38:09.938Z INF/cli:doctor 31 [*] Using ZeroMQ 4.1.4
2021-09-06T05:38:09.951Z ERR/cli:doctor 31 [*] RethinkDB is not installed (`rethinkdb` is missing)
2021-09-06T05:38:09.951Z ERR/cli:doctor 31 [*] ProtoBuf is not installed (`protoc` is missing)
2021-09-06T05:38:09.951Z ERR/cli:doctor 31 [*] ADB is not installed (`adb` is missing)
2021-09-06T05:38:09.951Z INF/cli:doctor 31 [*] Using GraphicsMagick 1.3.23
stf@c41347bcc85a:/app$ stf --version
3.6.1
```

**Provider-side log when installing was successful**
```
2022-01-11T10:14:51.846Z INF/device:plugins:install 36 [R3CN606HJXX] Installing package "my.app" from "/s/apk/b800b235-e95f-401b-a258-8cf4a1b7c560/31664875622a7fb125906a7d1xxxxxx"
2022-01-11T10:15:53.878Z INF/device:plugins:install 36 [R3CN606HJXX] Launching activity with action "android.intent.action.MAIN" on component "my.app/.activity.TemplateListActivity"
```
**Provider-side log when installing was stuck**
Nothing showed up

**Additional questions**
- Where can I see logs related to this symptom? 
- Is there debug mode to enable more logs?

**Comment by jay0129** [comment]
Not uploadable app:
https://www.apkmirror.com/apk/line-corporation/line/line-11-17-1-release/line-free-calls-messages-11-17-1-android-apk-download/

Uploadable app:
https://www.apkmirror.com/apk/line-corporation/line/line-11-16-2-release/line-free-calls-messages-11-16-2-android-apk-download/#uploadAPK

**Comment by denis99999** [comment]
@jay0129 ,

Can you run an `adb logcat` while the apk is loading to see if any errors occur?
Regards.

**Comment by koral--** [comment]
I've also noticed an error there.
Here is a log produced by stf-storage-plugin-apk unit:
```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```
Request to `/s/apk/<id>/<id>/manifest` fails with error 502.

**Comment by jay0129** [comment]
I think it occurs occasionally, and I cannot reproduce this today.

 it must be a compatibility problem between your application and the target Android mobile (eg. SDK level, etc.)
=> I don't think so, because I could install it with the adb install command

**Comment by denis99999** [comment]
@jay0129 ,

In this case, it could be a network level issue between `client`, `server `and `provider`, but either way until you provide detailed logs of what is happening at each level, I can't help you any further.

In addition, you can try to load your application directly with `ADB `but not through a local USB connection, but through the network from the `client `or `server `position, so by doing an a`db connect...` beforehand.

Regards.

**Comment by jay0129** [comment]
I have tried installing the app using ADB with 'ADB over WiFi' feature, and it worked well whereas installing via STF web console didn't work.

However, I cannot reproduce this issue these days, I will get back here with logs if it occurs again.
