### ISSUE TITLE
When I use "stf local" I find the follow error.

### ISSUE THREAD

**Issue by songfj** [DeviceFarmer/stf#410]
### stf local
Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_GROUPS_ENGINE_` .)

Could not locate the bindings file. Tried:
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/Debug/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/Release/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/out/Debug/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/Debug/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/out/Release/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/Release/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/default/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/compiled/16.12.0/darwin/arm64/zmq.node
2022-01-21T07:52:56.406Z FTL/cli:local 40074 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/test_mac/projects/github/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
2022-01-21T07:52:56.407Z INF/cli:local 40074 [*] Shutting down all child processes

### stf doctor
2022-01-21T07:58:10.270Z ERR/cli:doctor 58964 [*] Unexpected error checking ZeroMQ: Error: Could not locate the bindings file. Tried:
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/Debug/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/Release/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/out/Debug/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/Debug/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/out/Release/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/Release/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/build/default/zmq.node
 → /Users/test_mac/projects/github/stf/node_modules/zmq/compiled/16.12.0/darwin/arm64/zmq.node
    at bindings (/Users/test_mac/projects/github/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/test_mac/projects/github/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/test_mac/projects/github/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/test_mac/projects/github/stf/lib/cli/doctor/index.js:151:17
From previous event:
    at check (/Users/test_mac/projects/github/stf/lib/cli/doctor/index.js:103:23)
    at checkZeroMQ (/Users/test_mac/projects/github/stf/lib/cli/doctor/index.js:150:12)
    at Object.module.exports.handler (/Users/test_mac/projects/github/stf/lib/cli/doctor/index.js:179:5)
    at Object.self.runCommand (/Users/test_mac/projects/github/stf/node_modules/yargs/lib/command.js:170:22)
    at parseArgs (/Users/test_mac/projects/github/stf/node_modules/yargs/yargs.js:920:28)
    at Object.get [as argv] (/Users/test_mac/projects/github/stf/node_modules/yargs/yargs.js:860:16)
    at Object.<anonymous> (/Users/test_mac/projects/github/stf/lib/cli/index.js:47:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/test_mac/projects/github/stf/lib/cli/please.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  tries: [Array]
}

**Comment by denis99999** [comment]
@songfj 

Did you respect the [Requirements](https://github.com/DeviceFarmer/stf#requirements) ?
Regards.
