### ISSUE TITLE
rootDirectory not specified when running stf

### ISSUE THREAD

**Issue by gyjin20** [DeviceFarmer/stf#423]
I'm using ubutu 20, nodejs 8.17. After installing the dependencies I install the stf globally by 'npm install -g @devicefarmer/stf', then I can run stf successfully and connect one device.

Here is one question for build: in the readme it has one step to run 'npm install' for development.  Where should I run this command and what will this command do?

I also meet one issue if I install stf locally by 'npm install @devicefarmer/stf'. After installing I got such directories.

m@ubuntu:~/Desktop$ npm install @devicefarmer/stf
...
+ @devicefarmer/stf@3.6.1
added 106 packages from 92 contributors and audited 755 packages in 103.737s

15 packages are looking for funding
  run `npm fund` for details

found 124 vulnerabilities (21 low, 45 moderate, 42 high, 16 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

m@ubuntu:~/Desktop$ ls
node_modules
m@ubuntu:~/Desktop$ ls node_modules/
accepts                                   escape-string-regexp        lodash._isnative            require-directory
acorn                                     esprima                     lodash.isobject             require-main-filename
acorn-globals                             esutils                     lodash.keys                 requires-port
after                                     etag                        lodash._maxpoolsize         resolve
....
m@ubuntu:~/Desktop/node_modules/@devicefarmer$ ls
adbkit            adbkit-logcat  minicap-prebuilt    stf              stf-browser-db  stf-syrup
adbkit-apkreader  adbkit-monkey  minitouch-prebuilt  stf-appstore-db  stf-device-db   stf-wiki
m@ubuntu:~/Desktop/node_modules/@devicefarmer/stf$ bin/stf local
...
2022-02-04T18:09:47.623Z INF/db 82320 [*] Connecting to 127.0.0.1:28015
lib/cli app

Options:
  -h, --help           Show help.                                      [boolean]
  -V, --version        Show version.                                   [boolean]
  --auth-url, -a       URL to the auth unit.                 [string] [required]
  --port, -p           The port to bind to.             [number] [default: 7105]
  --secret, -s         The secret to use for auth JSON Web Tokens. Anyone who
                       knows this token can freely enter the system if they
                       want, so keep it safe.                [string] [required]
  --ssid, -i           The name of the session ID cookie.
                                                      [string] [default: "ssid"]
  --user-profile-url   URL to an external user profile page.            [string]
  --websocket-url, -w  URL to the websocket unit.            [string] [required]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_APP_` (e.g. `STF_APP_AUTH_URL`).

"rootDirectory" not specified or is invalid
2022-02-04T18:09:48.028Z FTL/cli:local 82280 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/mc/Desktop/node_modules/@devicefarmer/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

Has someone met such issue and how to fix it? Thanks!

**Comment by qianmianyao** [comment]
This problem has been solved, it should be a nodejs version issue
#707

**Comment by discord-iecheruo** [comment]
This looks like a regression from openstf. See https://github.com/openstf/stf/issues/673

**Comment by discord-iecheruo** [comment]
I've got a pull request to fix it, hopefully it gets picked up soon.

https://github.com/DeviceFarmer/stf/pull/800
