### ISSUE TITLE
error: no matching function for call to ‘v8::Value::Uint32Value()

### ISSUE THREAD

**Issue by batara666** [DeviceFarmer/stf#43]
OS: Ubuntu 20.04
Source: master

[2020-07-20T06_30_39_111Z-debug.log](https://github.com/DeviceFarmer/stf/files/4945885/2020-07-20T06_30_39_111Z-debug.log)

```sh
/home/ken/.cache/node-gyp/12.18.2/include/node/v8.h:2707:41: note: candidate: ‘v8::Maybe<unsigned[41/358$
::Value::Uint32Value(v8::Local<v8::Context>) const’                                                      
 2707 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(                                             
      |                                         ^~~~~~~~~~~                                              
/home/ken/.cache/node-gyp/12.18.2/include/node/v8.h:2707:41: note:   candidate expects 1 argument, 0 prov
ided                                                                                                     
../src/buffersize.cc:86:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*
) const’ is deprecated [-Wdeprecated-declarations]                                                       
   86 |     callback->Call(2, argv);                                                                     
      |                           ^                                                                      
In file included from ../src/exports.h:4,                                                                
                 from ../src/buffersize.cc:1:                                                            
../../../nan/nan.h:1742:3: note: declared here                                                           
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {                                            
      |   ^~~~                                                                                           
../src/buffersize.cc:102:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>
*) const’ is deprecated [-Wdeprecated-declarations]                                                      
  102 |       callback->Call(1, argv);                                                                   
      |                             ^                                                                    
In file included from ../src/exports.h:4,                                                                
                 from ../src/buffersize.cc:1:                                                            
../../../nan/nan.h:1742:3: note: declared here                                                           
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {                                            
      |   ^~~~                                                                                           
In file included from ../src/buffersize.cc:1:                                                            
../src/exports.h: At global scope:                                                                       
../src/exports.h:18:12: warning: ‘NJT_DEFAULT_FORMAT’ defined but not used [-Wunused-variable]           
   18 | static int NJT_DEFAULT_FORMAT = TJPF_RGBA;                                                       
      |            ^~~~~~~~~~~~~~~~~~                                                                    
../src/exports.h:16:12: warning: ‘NJT_DEFAULT_QUALITY’ defined but not used [-Wunused-variable]          
   16 | static int NJT_DEFAULT_QUALITY = 80;                                                             
      |            ^~~~~~~~~~~~~~~~~~~                                                                   
make: *** [jpegturbo.target.mk:119: Release/obj.target/jpegturbo/src/buffersize.o] Error 1               
make: Leaving directory '/home/ken/Documents/learn/stf-test/stf/node_modules/@devicefarmer/jpeg-turbo/bui
ld'                                                                                                      
gyp ERR! build error                                                                                     
gyp ERR! stack Error: `make` failed with exit code: 2                                                    
gyp ERR! stack     at ChildProcess.onExit (/home/ken/.nvm/versions/node/v12.18.2/lib/node_modules/npm/nod
e_modules/node-gyp/lib/build.js:194:23)                                                                  
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)                                               
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)             
gyp ERR! System Linux 5.4.0-40-generic                                                                   
gyp ERR! command "/home/ken/.nvm/versions/node/v12.18.2/bin/node" "/home/ken/.nvm/versions/node/v12.18.2/
lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                    
gyp ERR! cwd /home/ken/Documents/learn/stf-test/stf/node_modules/@devicefarmer/jpeg-turbo                
gyp ERR! node -v v12.18.2                                                                                
gyp ERR! node-gyp -v v5.1.0                                                                              
gyp ERR! not ok                                                                                          

```

**Comment by denis99999** [comment]
@batara666 ,
Version 12 of node is not supported actually, try to use a v8.17.x version.

**Comment by koral--** [comment]
Node 12 support is tracked here: https://github.com/DeviceFarmer/stf/issues/37
So closing this issue.
