### ISSUE TITLE
armhf docker file does not build

### ISSUE THREAD

**Issue by gounthar** [DeviceFarmer/stf#459]
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

Does the armhf docker image still works for you in the CI?
I tried to build it on an armv7 machine and got this error:

```bash

added 2069 packages from 1933 contributors and audited 2090 packages in 2813.53s

30 packages are looking for funding
  run `npm fund` for details

found 206 vulnerabilities (32 low, 73 moderate, 78 high, 23 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
+ echo --- Assembling app
+ echo npm pack
+ su stf -s /bin/bash
--- Assembling app
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> @devicefarmer/stf@3.6.1 prepublish /tmp/build
> bower install && not-in-install && gulp build || in-install

{ AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/tmp/build/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/tmp/build/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/tmp/build/gulpfile.js:79:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at requireOrImport (/tmp/build/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/tmp/build/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/tmp/build/node_modules/gulp/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/tmp/build/node_modules/liftoff/index.js:201:12)
    at module.exports (/tmp/build/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/tmp/build/node_modules/liftoff/index.js:191:5)
    at /tmp/build/node_modules/liftoff/index.js:149:9
    at /tmp/build/node_modules/v8flags/index.js:145:14
    at /tmp/build/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqWrap.oncomplete (fs.js:135:15)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @devicefarmer/stf@3.6.1 prepublish: `bower install && not-in-install && gulp build || in-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @devicefarmer/stf@3.6.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stf/.npm/_logs/2022-03-03T22_01_21_932Z-debug.log
The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&     echo '--- Updating repositories' &&     apt-get update &&     echo '--- Building node' &&     apt-get -y install wget python build-essential cmake &&     cd /tmp &&     wget --progress=dot:mega       https://nodejs.org/dist/v8.9.3/node-v8.9.3-linux-armv7l.tar.xz &&     tar -xJf node-v*.tar.xz --strip-components 1 -C /usr/local &&     rm node-v*.tar.xz &&     useradd --system       --create-home       --shell /usr/sbin/nologin       stf &&     su stf -s /bin/bash -c '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js install' &&     apt-get -y install --no-install-recommends libzmq3-dev libprotobuf-dev git graphicsmagick yasm &&     echo '--- Building app' &&     mkdir -p /app &&     chown -R stf:stf /tmp/build &&     set -x &&     cd /tmp/build &&     export PATH=$PWD/node_modules/.bin:$PATH &&     sed -i'' -e '/phantomjs/d' package.json &&     npm config set unsafe-perm true &&     echo 'npm cache clean --force' | su stf -s /bin/bash &&     echo 'npm install --no-optional --legacy-peer-deps --loglevel http' | su stf -s /bin/bash &&     echo '--- Assembling app' &&     echo 'npm pack' | su stf -s /bin/bash &&     tar xzf devicefarmer-stf-*.tgz --strip-components 1 -C /app &&     echo '/tmp/build/node_modules/.bin/bower cache clean' | su stf -s /bin/bash &&     echo 'npm prune --production' | su stf -s /bin/bash &&     mv node_modules /app &&     chown -R root:root /app &&     echo '--- Cleaning up' &&     echo 'npm cache clean --force' | su stf -s /bin/bash &&     rm -rf ~/.node-gyp &&     apt-get -y purge wget python build-essential &&     apt-get -y clean &&     apt-get -y autoremove &&     rm -rf /var/cache/apt/* /var/lib/apt/lists/* &&     cd /app &&     rm -rf /tmp/*' returned a non-zero code: 1
```

Am I the only one?

Thanks.

**Comment by denis99999** [comment]
@gounthar ,

I recently built a `3.6.1` without issue on a Raspberry Pi4, using the Dockerfile `Dockerfile-debian-armhf`, is this your case?
Regards.

**Comment by gounthar** [comment]
Thank you @denis99999 .
My `Raspberry Pi 3B+` are running [Armbian](https://www.armbian.com/rpi4b/), so 64 bits.
I'm building on an Orange Pi Zero, so a true 32 bits arm machine.
Did you build from master, or from the `3.6.1` source file release?

**Comment by denis99999** [comment]
@gounthar ,

I just built from master and it works well, I recommend using a Raspberry Pi4 for the build because it's much more powerful, it only takes a few minutes to build the docker image, on my side I use a `Raspbian lite OS` on my Pi whether for construction or production and everything is very stable, but it's true slightly more expensive than a Pi Zero, even if this cost is ridiculous compared to the purchase of mobiles that you have to connect to it, with the advantage that the Pi4 has 32 USB channels against only 8 for a Pi3.

Regards.

**Comment by gounthar** [comment]
@denis99999 what is the command you're using? 
Any parameter?

**Comment by denis99999** [comment]
@gounthar ,

Docker version: `20.10.12 build e91ed57`
Kernel: `5.10.63-v7l+` under  RaspiOS `Buster `updated
Command line for STF: `docker build -f Dockerfile-debian-armhf -t stf-armv7l:latest .`

**Comment by gounthar** [comment]
If you're using an aarch64 machine, it's not an armhf (32-bit) machine. I'm not sure about the extent of their compatibility for this Docker imaeg.

**Comment by denis99999** [comment]
@chiquilindebachinar , I didn't try with a RaspiOS bullseye, but using a Buster on Raspberry Pi4 it works well, let me some time to investigate about that!

**Comment by chiquilindebachinar** [comment]
Thanks @denis99999 . I was able to build the STF image with Buster, but now Im getting other errors with ADB and Rethinkdb images. I will spend some time analyzing the issues and will share here the outcome.

**Comment by denis99999** [comment]
@chiquilindebachinar , I successed to build a docker image of STF using raspberry PI OS Lite (64 bits) based on Debian Bullseye, so the same of yours! Are you behind a proxy ?

**Comment by chiquilindebachinar** [comment]
Hi @denis99999 I tried using Pi OS Lite (64 bits) based on Debian Bullseye, and now I'm able to build STF. I'm not behind a proxy, so maybe it was a timeout or something related to the other Pi OS. Now, I have an issue with the ADB container which keeps restarting. Have you encountered this issue? It seems there is a compatibility issue with the Raspberry Pi's architecture.

First, I built the STF image, and then I updated the docker-compose to use it.

@raspberrypi:~/stf $docker build -t stf-arm:latest -f Dockerfile-stf-debian9-armhf .

raspberrypi:~/stf $ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                          PORTS                                                                              NAMES
92eaae1aac71   stf-armv7l:latest         "stf local --adb-hos…"   5 minutes ago    Up 5 minutes                    0.0.0.0:7100->7100/tcp, 0.0.0.0:7110->7110/tcp, 0.0.0.0:7400-7500->7400-7500/tcp   stf
66287380fc1e   devicefarmer/adb:latest   "/sbin/tini -- adb -…"   47 minutes ago   Restarting (1) 23 seconds ago                                                                                      adb
fea1b3ee8c5f   rethinkdb:2.4.2           "rethinkdb --bind al…"   2 hours ago      Up 31 minutes                   8080/tcp, 28015/tcp, 29015/tcp     

@raspberrypi:~/stf $ docker logs adb
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error

@raspberrypi:~/stf $ cat docker-compose.yaml
version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4.2
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true

  stf:
    container_name: stf
    image: stf-armv7l:latest
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=
      - STF_ADMIN_NAME=
    restart: unless-stopped
    command: stf local --adb-host adb --public-ip 192.168.0.49 --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}



@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by chiquilindebachinar** [comment]
Maybe not relevant, but I tried using gounthar/docker-adb:docker-adb-aarch64 image, and it's working okay.  @raspberrypi:~ $ docker ps
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS         PORTS                                                                              NAMES
df4e5fa1c93d   gounthar/docker-adb:docker-adb-aarch64   "/sbin/tini -- adb -…"   9 minutes ago    Up 3 minutes   5037/tcp                                                                           adb
92eaae1aac71   stf-armv7l:latest                        "stf local --adb-hos…"   53 minutes ago   Up 3 minutes   0.0.0.0:7100->7100/tcp, 0.0.0.0:7110->7110/tcp, 0.0.0.0:7400-7500->7400-7500/tcp   stf
fea1b3ee8c5f   rethinkdb:2.4.2                          "rethinkdb --bind al…"   3 hours ago      Up 3 minutes   8080/tcp, 28015/tcp, 29015/tcp                                                     rethinkdb

**Comment by denis99999** [comment]
@chiquilindebachinar , what rethinkdb image do you use ? Or how did you build it (Dockerfile) ?

**Comment by im-0** [comment]
At least partially fixed by https://github.com/DeviceFarmer/stf/pull/712.

@chiquilindebachinar, @denis99999, just to share my experience with similar issues:

I am using stf on a Raspberry Pi 4 with Fedora. In my case, it was much easier to install adb on the host system from a standard Fedora repository.

RethinkDB is trickier, but I was able to package it for Fedora: https://github.com/im-0/fedora-rpm.rethinkdb. Though I do not recommend this if you do not have any experience in creating new packages for your preferred Linux distro, just modifying someone else's Dockerfile might be easier =).

**Comment by denis99999** [comment]
@im-0 , there is no problem for building an ARM 32/64 bit binaries of rethinkDB as docker images, but I meet an issue on running such images on the latest Raspberry PI OS (Bullseye Kernel version 6.1, 32 or 64 bit, Aarch64 architecture), see [#7126](https://github.com/rethinkdb/rethinkdb/issues/7126) for details

**Comment by im-0** [comment]
@denis99999 I see `armv7l` in your log. It is a 32-bit ARM ISA.

Have you verified that your rethinkdb binary is actually 64-bit?

Also, try to build RethinkDB natively, without docker. It should be relatively easy as it does not have that many dependencies. As I said, I use natively built aarch64 RethinkDB running on aarch64 Linux and everything works just fine.

**Comment by denis99999** [comment]
@im-0 , I closed the rethinkdb ticket, it works well now with 64-bit rethinkdb binaries (my docker installation on Raspberry Pi OS was not adequate)
