### ISSUE TITLE
Redmi Note 8 unable to display

### ISSUE THREAD

**Issue by s2339956** [DeviceFarmer/stf#50]
## Infinite loop
Manual installation of STFService.apk remains the same
MIUI: 11.0.6
AndroidOS: 9
```
stf_1        | 2020-07-23T05:35:24.245Z IMP/device:plugins:group 240 [1291d4df] Now owned by "s2339956@gmail.com"
stf_1        | 2020-07-23T05:35:24.247Z INF/device:plugins:group 240 [1291d4df] Subscribing to group channel "84lE13ejTSepiHnmQ4bavg=="
stf_1        | 2020-07-23T05:35:24.553Z INF/device:plugins:screen:stream 240 [1291d4df] Setting frame producer projection to 753x1175
stf_1        | 2020-07-23T05:35:24.556Z INF/device:plugins:screen:stream 240 [1291d4df] Requesting frame producer to start
stf_1        | 2020-07-23T05:35:24.558Z INF/device:plugins:screen:stream 240 [1291d4df] Launching screen service
stf_1        | 2020-07-23T05:35:24.648Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "PID: 13485"
stf_1        | 2020-07-23T05:35:24.649Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: Using projection 1080x2340@542x1175/0"
stf_1        | 2020-07-23T05:35:24.651Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient"
stf_1        | 2020-07-23T05:35:24.653Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check"
stf_1        | 2020-07-23T05:35:24.656Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display"
stf_1        | 2020-07-23T05:35:24.658Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue"
stf_1        | 2020-07-23T05:35:24.660Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options"
stf_1        | 2020-07-23T05:35:24.666Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer"
stf_1        | 2020-07-23T05:35:24.669Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter"
stf_1        | 2020-07-23T05:35:24.671Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display"
stf_1        | 2020-07-23T05:35:24.673Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "Vector<> have different types (this=0x7ff7fc1c80, rhs=0x7ff7fc1da0)"
stf_1        | 2020-07-23T05:35:24.675Z INF/device:plugins:screen:stream 240 [1291d4df] Connecting to minicap service
stf_1        | 2020-07-23T05:35:24.754Z WRN/device:plugins:screen:stream 240 [1291d4df] Shell keeping minicap running ended unexpectedly
stf_1        | 2020-07-23T05:35:25.124Z INF/device:plugins:connect 240 [1291d4df] Listening on port 7433
stf_1        | 2020-07-23T05:35:25.131Z IMP/device:plugins:connect 240 [1291d4df] Remote Connect Started for device "1291d4df" at "202.39.9.120:7433"
stf_1        | 2020-07-23T05:35:26.239Z INF/device:plugins:screen:stream 240 [1291d4df] Disconnecting from minicap service
stf_1        | 2020-07-23T05:35:26.241Z INF/device:plugins:screen:stream 240 [1291d4df] Stopping minicap service
stf_1        | 2020-07-23T05:35:26.243Z FTL/device:plugins:screen:stream 240 [1291d4df] Frame producer had an error FailError: Failure: 'closed'
stf_1        |     at /app/node_modules/@devicefarmer/adbkit/lib/adb/parser.js:183:29
stf_1        |     at runCallback (timers.js:789:20)
stf_1        |     at tryOnImmediate (timers.js:751:5)
stf_1        |     at processImmediate [as _immediateCallback] (timers.js:722:5)
stf_1        | 2020-07-23T05:35:26.244Z FTL/util:lifecycle 240 [1291d4df] Shutting down due to fatal error
stf_1        | 2020-07-23T05:35:26.251Z INF/provider 44 [*] Cleaning up device worker "1291d4df"
stf_1        | 2020-07-23T05:35:26.252Z ERR/provider 44 [*] Device worker "1291d4df" died with code 1
stf_1        | 2020-07-23T05:35:26.252Z INF/provider 44 [*] Restarting device worker "1291d4df"
stf_1        | 2020-07-23T05:35:27.243Z INF/device:support:push 252 [1291d4df] Sending output to "tcp://127.0.0.1:7116"
stf_1        | 2020-07-23T05:35:27.248Z INF/device 252 [1291d4df] Preparing device
stf_1        | 2020-07-23T05:35:27.816Z INF/device:support:sub 252 [1291d4df] Receiving input from "tcp://127.0.0.1:7114"
stf_1        | 2020-07-23T05:35:27.817Z INF/device:support:sub 252 [1291d4df] Subscribing to permanent channel "*ALL"
stf_1        | 2020-07-23T05:35:27.907Z INF/device:support:properties 252 [1291d4df] Loading properties
stf_1        | 2020-07-23T05:35:27.984Z INF/device:support:sdk 252 [1291d4df] Supports SDK 28
stf_1        | 2020-07-23T05:35:27.987Z INF/device:support:abi 252 [1291d4df] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
stf_1        | 2020-07-23T05:35:28.232Z INF/device:resources:minicap 252 [1291d4df] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
stf_1        | 2020-07-23T05:35:28.235Z INF/device:resources:minicap 252 [1291d4df] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-28/minicap.so" as "/data/local/tmp/minicap.so"
stf_1        | 2020-07-23T05:35:28.406Z INF/device:resources:service 252 [1291d4df] Checking whether we need to install STFService
stf_1        | 2020-07-23T05:35:28.494Z INF/device:resources:service 252 [1291d4df] Running version check
stf_1        | 2020-07-23T05:35:28.900Z INF/device:resources:service 252 [1291d4df] STFService up to date
stf_1        | 2020-07-23T05:35:28.902Z INF/device:plugins:service 252 [1291d4df] Launching agent
stf_1        | 2020-07-23T05:35:29.608Z INF/device:plugins:service 252 [1291d4df] Agent says: "Listening on @stfagent"
stf_1        | 2020-07-23T05:35:29.638Z INF/device:plugins:service 252 [1291d4df] Launching service
stf_1        | 2020-07-23T05:35:29.641Z INF/device:plugins:service 252 [1291d4df] using 'start-foreground-service' command for API 28
stf_1        | 2020-07-23T05:35:29.646Z INF/device:plugins:service 252 [1291d4df] Agent says: "InputClient started"
stf_1        | 2020-07-23T05:35:29.793Z INF/device:plugins:display 252 [1291d4df] Reading display info
stf_1        | 2020-07-23T05:35:29.845Z INF/device:plugins:phone 252 [1291d4df] Fetching phone info
stf_1        | 2020-07-23T05:35:29.898Z INF/device:plugins:identity 252 [1291d4df] Solving identity
stf_1        | 2020-07-23T05:35:29.926Z INF/device:plugins:solo 252 [1291d4df] Subscribing to permanent channel "+AU4+eTn4OUDnfMucaaUztzTR7k="
stf_1        | 2020-07-23T05:35:29.932Z INF/device:plugins:screen:stream 252 [1291d4df] Starting WebSocket server on port 7436
stf_1        | 2020-07-23T05:35:30.177Z INF/device:resources:minitouch 252 [1291d4df] Installing "/app/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
stf_1        | 2020-07-23T05:35:30.280Z WRN/device:plugins:data 252 [1291d4df] Unable to find device data { serial: '1291d4df',
stf_1        |   platform: 'Android',
stf_1        |   manufacturer: 'XIAOMI',
stf_1        |   operator: ',中國移動',
stf_1        |   model: 'Redmi Note 8',
stf_1        |   version: '9',
stf_1        |   abi: 'arm64-v8a',
stf_1        |   sdk: '28',
stf_1        |   product: 'ginkgo',
stf_1        |   cpuPlatform: 'trinket',
stf_1        |   openGLESVersion: '3.2',
stf_1        |   marketName: 'Redmi Note 8',
stf_1        |   display:
stf_1        |    { id: 0,
stf_1        |      width: 1080,
stf_1        |      height: 2340,
stf_1        |      xdpi: 409.4320068359375,
stf_1        |      ydpi: 409.90301513671875,
stf_1        |      fps: 60.000003814697266,
stf_1        |      density: 2.75,
stf_1        |      rotation: 0,
stf_1        |      secure: true,
stf_1        |      size: 6.288630704837173,
stf_1        |      url: 'ws://202.39.9.120:7436' },
stf_1        |   phone: { network: 'LTE' } }
stf_1        | 2020-07-23T05:35:30.305Z INF/device:plugins:touch 252 [1291d4df] Touch origin is top left
stf_1        | 2020-07-23T05:35:30.307Z INF/device:plugins:touch 252 [1291d4df] Requesting touch consumer to start
stf_1        | 2020-07-23T05:35:30.310Z INF/device:plugins:touch 252 [1291d4df] Launching touch service
stf_1        | 2020-07-23T05:35:30.332Z INF/device:plugins:touch 252 [1291d4df] Connecting to minitouch service
stf_1        | 2020-07-23T05:35:30.372Z INF/device:plugins:touch 252 [1291d4df] minitouch says: "Type B touch device NVTCapacitiveTouchScreen (1079x2339 with 10 contacts) detected on /dev/input/event2 (score 22597)"
stf_1        | 2020-07-23T05:35:30.454Z INF/device:plugins:touch 252 [1291d4df] Reading minitouch banner
stf_1        | 2020-07-23T05:35:30.459Z INF/device:plugins:touch 252 [1291d4df] minitouch says: "Connection established"
stf_1        | 2020-07-23T05:35:30.511Z INF/device:plugins:vnc 252 [1291d4df] Starting VNC server on port 7438
stf_1        | 2020-07-23T05:35:30.519Z INF/device:plugins:browser 252 [1291d4df] Loading browser list
stf_1        | 2020-07-23T05:35:30.554Z INF/device:plugins:browser 252 [1291d4df] Updating browser list
stf_1        | 2020-07-23T05:35:30.562Z INF/device:plugins:mute 252 [1291d4df] Will not mute master volume
stf_1        | 2020-07-23T05:35:30.833Z INF/device:resources:minirev 252 [1291d4df] Installing "/app/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
stf_1        | 2020-07-23T05:35:30.944Z INF/device:plugins:forward 252 [1291d4df] Launching reverse port forwarding service
stf_1        | 2020-07-23T05:35:30.973Z INF/device:plugins:forward 252 [1291d4df] Connecting to reverse port forwarding service
stf_1        | 2020-07-23T05:35:31.229Z INF/device 252 [1291d4df] Fully operational
```

**Comment by bahadirh** [comment]
I'm having the same issue with Redmi Note 8 Pro with STF running on Catalina 10.15.6. Here's the log displayed when the device is connected through USB. I've replaced the device ID with `SOMEDEVICEID`.

```
2020-07-26T14:18:07.118Z INF/provider 80394 [*] Found device "SOMEDEVICEID" (offline)                                                            [47/1574]
2020-07-26T14:18:07.137Z INF/provider 80394 [*] Registered device "SOMEDEVICEID"
2020-07-26T14:18:07.137Z INF/provider 80394 [*] Device "SOMEDEVICEID" is now "device" (was "offline")
2020-07-26T14:18:07.137Z INF/reaper 80393 [reaper001] Device "SOMEDEVICEID" is present
2020-07-26T14:18:07.927Z INF/device:support:push 80412 [SOMEDEVICEID] Sending output to "tcp://127.0.0.1:7116"
2020-07-26T14:18:07.931Z INF/device 80412 [SOMEDEVICEID] Preparing device
2020-07-26T14:18:08.824Z INF/device:support:sub 80412 [SOMEDEVICEID] Receiving input from "tcp://127.0.0.1:7114"
2020-07-26T14:18:08.827Z INF/device:support:sub 80412 [SOMEDEVICEID] Subscribing to permanent channel "*ALL"
2020-07-26T14:18:08.858Z INF/device:support:properties 80412 [SOMEDEVICEID] Loading properties
2020-07-26T14:18:08.884Z INF/device:support:sdk 80412 [SOMEDEVICEID] Supports SDK 29
2020-07-26T14:18:08.884Z INF/device:support:abi 80412 [SOMEDEVICEID] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2020-07-26T14:18:08.988Z INF/device:resources:minicap 80412 [SOMEDEVICEID] Installing "/Users/bahadirh/.n/lib/node_modules/@devicefarmer/stf/node_modules/
@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2020-07-26T14:18:08.989Z INF/device:resources:minicap 80412 [SOMEDEVICEID] Installing "/Users/bahadirh/.n/lib/node_modules/@devicefarmer/stf/node_modules/
@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-29/minicap.so" as "/data/local/tmp/minicap.so"
2020-07-26T14:18:09.059Z INF/device:resources:service 80412 [SOMEDEVICEID] Checking whether we need to install STFService
2020-07-26T14:18:09.092Z INF/device:resources:service 80412 [SOMEDEVICEID] Running version check
2020-07-26T14:18:09.398Z INF/device:resources:service 80412 [SOMEDEVICEID] STFService up to date
2020-07-26T14:18:09.404Z INF/device:plugins:service 80412 [SOMEDEVICEID] Launching agent
2020-07-26T14:18:09.846Z INF/device:plugins:service 80412 [SOMEDEVICEID] Agent says: "Starting minitouch agent"
2020-07-26T14:18:09.856Z INF/device:plugins:service 80412 [SOMEDEVICEID] Agent says: "Listening on @stfagent"
2020-07-26T14:18:09.886Z INF/device:plugins:service 80412 [SOMEDEVICEID] Launching service
2020-07-26T14:18:09.887Z INF/device:plugins:service 80412 [SOMEDEVICEID] using 'start-foreground-service' command for API 29
2020-07-26T14:18:09.898Z INF/device:plugins:service 80412 [SOMEDEVICEID] Agent says: "InputClient started"
2020-07-26T14:18:09.935Z INF/device:plugins:display 80412 [SOMEDEVICEID] Reading display info
2020-07-26T14:18:09.961Z INF/device:plugins:phone 80412 [SOMEDEVICEID] Fetching phone info
2020-07-26T14:18:09.973Z INF/device:plugins:identity 80412 [SOMEDEVICEID] Solving identity
2020-07-26T14:18:09.977Z INF/device:plugins:solo 80412 [SOMEDEVICEID] Subscribing to permanent channel "ojitMimUqq2vyhtvEQJcFvuQZ4Y="
2020-07-26T14:18:09.979Z INF/device:plugins:screen:stream 80412 [SOMEDEVICEID] Starting WebSocket server on port 7404
2020-07-26T14:18:10.110Z INF/device:resources:minitouch 80412 [SOMEDEVICEID] Installing "/Users/bahadirh/.n/lib/node_modules/@devicefarmer/stf/node_module
s/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
2020-07-26T14:18:10.145Z WRN/device:plugins:data 80412 [SOMEDEVICEID] Unable to find device data { serial: 'SOMEDEVICEID',
  platform: 'Android',                                                                                                                              
  manufacturer: 'XIAOMI',
  operator: 'Vodafone',
  model: ' Note 8 Pro',
  version: '10',
  abi: 'arm64-v8a',
  sdk: '29',
  product: 'begonia',
  cpuPlatform: 'mt6785',
  openGLESVersion: '3.2',
  marketName: 'Redmi Note 8 Pro',
  display:
   { id: 0,
     width: 1080,
     height: 2340,
     xdpi: 394.71600341796875,
     ydpi: 394.71600341796875,
     fps: 59.9900016784668,
     density: 2.75,
     rotation: 0,
     secure: true,
     size: 6.529271093831765,
     url: 'ws://localhost:7404' },
  phone: { network: 'UNKNOWN' } }
2020-07-26T14:18:10.152Z INF/device:plugins:touch 80412 [SOMEDEVICEID] Touch origin is top left
2020-07-26T14:18:10.153Z INF/device:plugins:touch 80412 [SOMEDEVICEID] Requesting touch consumer to start
2020-07-26T14:18:10.154Z INF/device:plugins:touch 80412 [SOMEDEVICEID] Launching touch service
2020-07-26T14:18:10.174Z INF/device:plugins:touch 80412 [SOMEDEVICEID] Connecting to minitouch service
2020-07-26T14:18:10.184Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "open: Permission denied"
2020-07-26T14:18:10.184Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "Unable to open device /dev/input/event4 for inspectionopen: Permis
sion denied"
2020-07-26T14:18:10.184Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permis
sion denied"
2020-07-26T14:18:10.185Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "Unable to open device /dev/input/event3 for inspectionopen: Permis
sion denied"
2020-07-26T14:18:10.186Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permis
sion denied"
2020-07-26T14:18:10.186Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to fi
nd a suitable touch device"
2020-07-26T14:18:10.187Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "using Android InputManager"
2020-07-26T14:18:10.286Z INF/device:plugins:touch 80412 [SOMEDEVICEID] minitouch says: "Connection established"
2020-07-26T14:18:10.287Z INF/device:plugins:touch 80412 [SOMEDEVICEID] Reading minitouch banner
2020-07-26T14:18:10.293Z INF/device:plugins:vnc 80412 [SOMEDEVICEID] Starting VNC server on port 7406
2020-07-26T14:18:10.296Z INF/device:plugins:browser 80412 [SOMEDEVICEID] Loading browser list
2020-07-26T14:18:10.337Z INF/device:plugins:browser 80412 [SOMEDEVICEID] Updating browser list
2020-07-26T14:18:10.342Z INF/device:plugins:mute 80412 [SOMEDEVICEID] Will not mute master volume
2020-07-26T14:18:10.457Z INF/device:resources:minirev 80412 [SOMEDEVICEID] Installing "/Users/bahadirh/.n/lib/node_modules/@devicefarmer/stf/vendor/minire
v/arm64-v8a/minirev" as "/data/local/tmp/minirev"
2020-07-26T14:18:10.505Z INF/device:plugins:forward 80412 [SOMEDEVICEID] Launching reverse port forwarding service
2020-07-26T14:18:10.515Z INF/device:plugins:forward 80412 [SOMEDEVICEID] Connecting to reverse port forwarding service
2020-07-26T14:18:10.706Z INF/device 80412 [SOMEDEVICEID] Fully operational
```

**Comment by koral--** [comment]
This seems to be already reported here: https://github.com/DeviceFarmer/minicap/issues/2
Closing this as a duplicate. Please continue discussion at https://github.com/DeviceFarmer/minicap/issues/2
