### ISSUE TITLE
Runtime errors due to adbkit on the master line

### ISSUE THREAD

**Issue by denis99999** [DeviceFarmer/stf#527]
**What is the issue or idea you have?**
Execution errors
It seems that the last modifications on `adbkit `bring errors, it would be necessary to go back, and test first that the new functionalities of `adbkit `work before the addition in the master line

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
on any device

**Please provide the steps to reproduce the issue.**
// connect a device
`# stf local`

**What is the expected behavior?**
no error

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
// first error type : _DeviceClient cannot be invoked without "new"_
```
2022-05-11T09:17:38.120Z FTL/device 17677 [FA6A90303673] Setup had an error TypeError: Class constructor DeviceClient cannot be invoked without 'new'
    at ensureBootComplete (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/lib/units/device/support/adb.js:19:20)
    at /home/debian/GITHUB/stf-upgrade-nodejs-3/stf/lib/units/device/support/adb.js:30:12
    at SerialSyrup.ParallelSyrup.invoke (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
    at /home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
2022-05-11T09:17:38.130Z FTL/util:lifecycle 17677 [FA6A90303673] Shutting down due to fatal error
```

// fixing this error in many files replacing "deviceClient" by "new deviceClient"
// second error type: _client.uninstall(...).timeout(...).then(...).progressed is not a function_
```
2022-05-11T13:14:42.445Z FTL/device 26225 [FA6A90303673] Setup had an error TypeError: client.uninstall(...).timeout(...).then(...).progressed is not a function
    at /home/debian/GITHUB/stf-upgrade-nodejs-3/stf/lib/units/device/resources/service.js:91:14
    at tryCatcher (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/debian/GITHUB/stf-upgrade-nodejs-3/stf/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
2022-05-11T13:14:42.447Z FTL/util:lifecycle 26225 [FA6A90303673] Shutting down due to fatal error
```

// I didn't go any further...

**Please run `stf doctor` and paste the output here.**
```
debian@debian:~/GITHUB/stf-upgrade-nodejs-3/stf$ ./bin/stf doctor
2022-05-11T13:06:26.549Z INF/cli:doctor 18766 [*] OS Arch: x64
2022-05-11T13:06:26.551Z INF/cli:doctor 18766 [*] OS Platform: linux
2022-05-11T13:06:26.551Z INF/cli:doctor 18766 [*] OS Platform: 4.19.0-19-amd64
2022-05-11T13:06:26.552Z INF/cli:doctor 18766 [*] Using Node 17.9.0
2022-05-11T13:06:26.568Z INF/cli:doctor 18766 [*] Using ZeroMQ 4.2.2
2022-05-11T13:06:26.584Z ERR/cli:doctor 18766 [*] RethinkDB is not installed (`rethinkdb` is missing)
2022-05-11T13:06:26.584Z ERR/cli:doctor 18766 [*] ProtoBuf is not installed (`protoc` is missing)
2022-05-11T13:06:26.585Z INF/cli:doctor 18766 [*] Using ADB 1.0.39
2022-05-11T13:06:26.601Z INF/cli:doctor 18766 [*] Using GraphicsMagick 1.3.35
```

**Comment by sirmordred** [comment]
i had exactly same error +1000
