### ISSUE TITLE
MI8SE can't see anything, but can touch or swipe

### ISSUE THREAD

**Issue by Affty** [DeviceFarmer/stf#61]
DeviceFarmer/stf:
Run in docker (Ubuntu ~16.04.5)
device:Xiao Mi  MI 8 SE (other devices is normal)
MI 8SE SDK API 29, android-os 10, MIUI 11.0.3（This mi8 is upgraded system）
the command what I used is 'docker run -d --name stf --net host deviceFarmer/stf stf local --public-ip 192.168.x.xxx'
**What is the issue or idea you have?**
Then the device screen is grey, but it can touch or swipe:
![捕获](https://user-images.githubusercontent.com/58965346/89770982-2727f800-db32-11ea-9579-611e8f53c022.jpg)

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
![image](https://user-images.githubusercontent.com/58965346/89769185-4ec99100-db2f-11ea-94f5-2a696cf615e0.png)

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
2020-08-10T09:42:19.265Z INF/util:procutil 289 [*] Forking "/app/lib/cli migrate"
2020-08-10T09:42:19.598Z INF/db 295 [*] Connecting to 127.0.0.1:28015
2020-08-10T09:42:19.618Z INF/db:setup 295 [*] Database "stf" already exists
2020-08-10T09:42:19.625Z INF/db:setup 295 [*] Table "users" already exists
2020-08-10T09:42:19.625Z INF/db:setup 295 [*] Table "accessTokens" already exists
2020-08-10T09:42:19.625Z INF/db:setup 295 [*] Table "vncauth" already exists
2020-08-10T09:42:19.625Z INF/db:setup 295 [*] Table "devices" already exists
2020-08-10T09:42:19.626Z INF/db:setup 295 [*] Table "logs" already exists
2020-08-10T09:42:19.626Z INF/db:setup 295 [*] Table "groups" already exists
2020-08-10T09:42:19.650Z INF/db:setup 295 [*] Index "users"."adbKeys" already exists
2020-08-10T09:42:19.653Z INF/db:setup 295 [*] Index "accessTokens"."email" already exists
2020-08-10T09:42:19.653Z INF/db:setup 295 [*] Index "vncauth"."response" already exists
2020-08-10T09:42:19.654Z INF/db:setup 295 [*] Index "vncauth"."responsePerDevice" already exists
2020-08-10T09:42:19.657Z INF/db:setup 295 [*] Index "devices"."owner" already exists
2020-08-10T09:42:19.658Z INF/db:setup 295 [*] Index "devices"."logs_enabled" already exists
2020-08-10T09:42:19.660Z INF/db:setup 295 [*] Index "devices"."present" already exists
2020-08-10T09:42:19.660Z INF/db:setup 295 [*] Index "devices"."providerChannel" already exists
2020-08-10T09:42:19.661Z INF/db:setup 295 [*] Index "devices"."group" already exists
2020-08-10T09:42:19.661Z INF/db:setup 295 [*] Index "groups"."privilege" already exists
2020-08-10T09:42:19.664Z INF/db:setup 295 [*] Index "groups"."owner" already exists
2020-08-10T09:42:19.664Z INF/db:setup 295 [*] Index "groups"."startTime" already exists
2020-08-10T09:42:19.665Z INF/db:setup 295 [*] Waiting for index "users"."adbKeys"
2020-08-10T09:42:19.667Z INF/db:setup 295 [*] Waiting for index "accessTokens"."email"
2020-08-10T09:42:19.667Z INF/db:setup 295 [*] Waiting for index "vncauth"."response"
2020-08-10T09:42:19.667Z INF/db:setup 295 [*] Waiting for index "vncauth"."responsePerDevice"
2020-08-10T09:42:19.668Z INF/db:setup 295 [*] Waiting for index "devices"."owner"
2020-08-10T09:42:19.669Z INF/db:setup 295 [*] Waiting for index "devices"."logs_enabled"
2020-08-10T09:42:19.669Z INF/db:setup 295 [*] Waiting for index "devices"."present"
2020-08-10T09:42:19.669Z INF/db:setup 295 [*] Waiting for index "devices"."providerChannel"
2020-08-10T09:42:19.669Z INF/db:setup 295 [*] Waiting for index "devices"."group"
2020-08-10T09:42:19.670Z INF/db:setup 295 [*] Waiting for index "groups"."privilege"
2020-08-10T09:42:19.670Z INF/db:setup 295 [*] Waiting for index "groups"."owner"
2020-08-10T09:42:19.670Z INF/db:setup 295 [*] Waiting for index "groups"."startTime"
2020-08-10T09:42:19.713Z INF/db:setup 295 [*] Index "users"."adbKeys" is ready
2020-08-10T09:42:19.714Z INF/db:setup 295 [*] Index "accessTokens"."email" is ready
2020-08-10T09:42:19.722Z INF/db:setup 295 [*] Index "vncauth"."response" is ready
2020-08-10T09:42:19.735Z INF/db:setup 295 [*] Index "vncauth"."responsePerDevice" is ready
2020-08-10T09:42:19.735Z INF/db:setup 295 [*] Index "devices"."owner" is ready
2020-08-10T09:42:19.736Z INF/db:setup 295 [*] Index "devices"."logs_enabled" is ready
2020-08-10T09:42:19.736Z INF/db:setup 295 [*] Index "devices"."present" is ready
2020-08-10T09:42:19.736Z INF/db:setup 295 [*] Index "devices"."providerChannel" is ready
2020-08-10T09:42:19.736Z INF/db:setup 295 [*] Index "devices"."group" is ready
2020-08-10T09:42:19.736Z INF/db:setup 295 [*] Index "groups"."privilege" is ready
2020-08-10T09:42:19.736Z INF/db:setup 295 [*] Index "groups"."owner" is ready
2020-08-10T09:42:19.736Z INF/db:setup 295 [*] Index "groups"."startTime" is ready
2020-08-10T09:42:20.749Z INF/util:procutil 289 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2020-08-10T09:42:20.752Z INF/util:procutil 289 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2020-08-10T09:42:20.753Z INF/util:procutil 289 [*] Forking "/app/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2020-08-10T09:42:20.760Z INF/util:procutil 289 [*] Forking "/app/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2020-08-10T09:42:20.790Z INF/util:procutil 289 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2020-08-10T09:42:20.800Z INF/util:procutil 289 [*] Forking "/app/lib/cli provider --name myroot-virtual-machine --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2020-08-10T09:42:20.809Z INF/util:procutil 289 [*] Forking "/app/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2020-08-10T09:42:20.839Z INF/util:procutil 289 [*] Forking "/app/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2020-08-10T09:42:20.843Z INF/util:procutil 289 [*] Forking "/app/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2020-08-10T09:42:20.860Z INF/util:procutil 289 [*] Forking "/app/lib/cli groups-engine --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2020-08-10T09:42:20.872Z INF/util:procutil 289 [*] Forking "/app/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2020-08-10T09:42:20.911Z INF/util:procutil 289 [*] Forking "/app/lib/cli storage-temp --port 7102"
2020-08-10T09:42:20.919Z INF/util:procutil 289 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2020-08-10T09:42:20.935Z INF/util:procutil 289 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2020-08-10T09:42:20.944Z INF/util:procutil 289 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                    [string] [default: "myroot-virtual-machine"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Address already in use
2020-08-10T09:42:22.363Z FTL/cli:local 289 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2020-08-10T09:42:22.364Z INF/cli:local 289 [*] Shutting down all child processes
lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                    [string] [default: "myroot-virtual-machine"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Address already in use

**Please run `stf doctor` and paste the output here.**
run in docker:
root@myroot-virtual-machine:/home/myroot# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
ceec0e333d        devicefarmer/stf    "stf local --public-…"   8 hours ago        Up 9 minutes                            stf2
f28131ef3d        sorccu/adb:latest   "/sbin/tini -- adb -…"   3 days ago          Up 9 minutes                            adbd
325218acfb        rethinkdb           "rethinkdb --bind al…"   3 days ago          Up 9 minutes                            rethinkdb

$ stf doctor
2020-08-10T09:49:32.857Z INF/cli:doctor 516 [*] OS Arch: x64
2020-08-10T09:49:32.859Z INF/cli:doctor 516 [*] OS Platform: linux
2020-08-10T09:49:32.859Z INF/cli:doctor 516 [*] OS Platform: 4.4.0-104-generic
2020-08-10T09:49:32.859Z INF/cli:doctor 516 [*] Using Node 8.9.3
2020-08-10T09:49:32.883Z INF/cli:doctor 516 [*] Using ZeroMQ 4.1.4
2020-08-10T09:49:32.906Z ERR/cli:doctor 516 [*] RethinkDB is not installed (`rethinkdb` is missing)
2020-08-10T09:49:32.906Z ERR/cli:doctor 516 [*] ProtoBuf is not installed (`protoc` is missing)
2020-08-10T09:49:32.907Z ERR/cli:doctor 516 [*] ADB is not installed (`adb` is missing)
2020-08-10T09:49:33.401Z INF/cli:doctor 516 [*] Using GraphicsMagick 1.3.23

**Comment by denis99999** [comment]
@Affty , verify your network configuration because your logs show an error: `address already in use`

**Comment by Affty** [comment]
> @Affty , verify your network configuration because your logs show an error: `address already in use`

But there is no problem with other devices, and the network is the same ,What is the specific cause of the problem?

**Comment by denis99999** [comment]
Your triproxies units are not launched because the mentioned error, so the provider unit cannot communicate with the master units which explains why you have a grey screen, this is the only thing I can say with the formal information you provided.
You can list the running processus and list the listen ports on your Linux machine to see if there are some applications in conflicts ?

**Comment by ii958** [comment]
I have the same problem with mi 10
