### ISSUE TITLE
Failed to ''Setup had an error Error: Cannot find module '@devicefarmer/jpeg-turbo''' by using docker-compose

### ISSUE THREAD

**Issue by chaooe** [DeviceFarmer/stf#64]
Log as below:

android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.073Z INF/provider 1 [*] Tracking devices
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.105Z INF/provider 1 [*] Found device "35fbffe7" (device)
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.109Z INF/provider 1 [*] Found device "5DQOWSB6AQTK79C6" (device)
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.121Z INF/provider 1 [*] Registered device "35fbffe7"
reaper_1_973795d269b5   | 2020-08-20T01:19:58.121Z INF/reaper 1 [dev] Device "35fbffe7" is present
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.144Z INF/provider 1 [*] Registered device "5DQOWSB6AQTK79C6"
reaper_1_973795d269b5   | 2020-08-20T01:19:58.145Z INF/reaper 1 [dev] Device "5DQOWSB6AQTK79C6" is present
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.556Z INF/device:support:push 13 [35fbffe7] Sending output to "tcp://dev-triproxy:7270"
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.560Z INF/device 13 [35fbffe7] Preparing device
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.563Z INF/device:support:push 19 [5DQOWSB6AQTK79C6] Sending output to "tcp://dev-triproxy:7270"
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.568Z INF/device 19 [5DQOWSB6AQTK79C6] Preparing device
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.942Z FTL/device 13 [35fbffe7] Setup had an error Error: Cannot find module '@devicefarmer/jpeg-turbo'
android-provider2_1_9f78623d87eb |     at Function.Module._resolveFilename (module.js:548:15)
android-provider2_1_9f78623d87eb |     at Function.Module._load (module.js:475:25)
android-provider2_1_9f78623d87eb |     at Module.require (module.js:597:17)
android-provider2_1_9f78623d87eb |     at require (internal/module.js:11:18)
android-provider2_1_9f78623d87eb |     at Object.<anonymous> (/app/lib/units/device/plugins/vnc/index.js:8:12)
android-provider2_1_9f78623d87eb |     at Module._compile (module.js:653:30)
android-provider2_1_9f78623d87eb |     at Object.Module._extensions..js (module.js:664:10)
android-provider2_1_9f78623d87eb |     at Module.load (module.js:566:32)
android-provider2_1_9f78623d87eb |     at tryModuleLoad (module.js:506:12)
android-provider2_1_9f78623d87eb |     at Function.Module._load (module.js:498:3)
android-provider2_1_9f78623d87eb |     at Module.require (module.js:597:17)
android-provider2_1_9f78623d87eb |     at require (internal/module.js:11:18)
android-provider2_1_9f78623d87eb |     at /app/lib/units/device/index.js:23:21
android-provider2_1_9f78623d87eb |     at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
android-provider2_1_9f78623d87eb |     at /app/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
android-provider2_1_9f78623d87eb |     at tryCatch1 (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
android-provider2_1_9f78623d87eb |     at Promise$_callHandler [as _callHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
android-provider2_1_9f78623d87eb |     at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
android-provider2_1_9f78623d87eb |     at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
android-provider2_1_9f78623d87eb |     at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
android-provider2_1_9f78623d87eb |     at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
android-provider2_1_9f78623d87eb |     at Async$consumeFunctionBuffer (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.943Z FTL/device 19 [5DQOWSB6AQTK79C6] Setup had an error Error: Cannot find module '@devicefarmer/jpeg-turbo'
android-provider2_1_9f78623d87eb |     at Function.Module._resolveFilename (module.js:548:15)
android-provider2_1_9f78623d87eb |     at Function.Module._load (module.js:475:25)
android-provider2_1_9f78623d87eb |     at Module.require (module.js:597:17)
android-provider2_1_9f78623d87eb |     at require (internal/module.js:11:18)
android-provider2_1_9f78623d87eb |     at Object.<anonymous> (/app/lib/units/device/plugins/vnc/index.js:8:12)
android-provider2_1_9f78623d87eb |     at Module._compile (module.js:653:30)
android-provider2_1_9f78623d87eb |     at Object.Module._extensions..js (module.js:664:10)
android-provider2_1_9f78623d87eb |     at Module.load (module.js:566:32)
android-provider2_1_9f78623d87eb |     at tryModuleLoad (module.js:506:12)
android-provider2_1_9f78623d87eb |     at Function.Module._load (module.js:498:3)
android-provider2_1_9f78623d87eb |     at Module.require (module.js:597:17)
android-provider2_1_9f78623d87eb |     at require (internal/module.js:11:18)
android-provider2_1_9f78623d87eb |     at /app/lib/units/device/index.js:23:21
android-provider2_1_9f78623d87eb |     at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
android-provider2_1_9f78623d87eb |     at /app/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
android-provider2_1_9f78623d87eb |     at tryCatch1 (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
android-provider2_1_9f78623d87eb |     at Promise$_callHandler [as _callHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
android-provider2_1_9f78623d87eb |     at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
android-provider2_1_9f78623d87eb |     at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
android-provider2_1_9f78623d87eb |     at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
android-provider2_1_9f78623d87eb |     at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
android-provider2_1_9f78623d87eb |     at Async$consumeFunctionBuffer (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.943Z FTL/util:lifecycle 19 [5DQOWSB6AQTK79C6] Shutting down due to fatal error
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.948Z FTL/util:lifecycle 13 [35fbffe7] Shutting down due to fatal error
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.957Z INF/provider 1 [*] Cleaning up device worker "5DQOWSB6AQTK79C6"
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.958Z ERR/provider 1 [*] Device worker "5DQOWSB6AQTK79C6" died with code 1
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.958Z INF/provider 1 [*] Restarting device worker "5DQOWSB6AQTK79C6"
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.959Z INF/provider 1 [*] Cleaning up device worker "35fbffe7"
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.959Z ERR/provider 1 [*] Device worker "35fbffe7" died with code 1
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:58.959Z INF/provider 1 [*] Restarting device worker "35fbffe7"
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:59.766Z INF/device:support:push 30 [35fbffe7] Sending output to "tcp://dev-triproxy:7270"
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:59.769Z INF/device 30 [35fbffe7] Preparing device
android-provider2_1_9f78623d87eb | 2020-08-20T01:19:59.768Z INF/device:support:push 29 [5DQOWSB6AQTK79C6] Sending output to "tcp://dev-triproxy:7270"

**Comment by chaooe** [comment]
docker-compose file
`version: '2'

volumes:
  rethinkdb:
  storage-temp:

services:
  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # You'll need to set the paths below to where your certs actually are
      - ./cert/server.crt:/etc/nginx/ssl/cert.crt
      - ./cert/server.key:/etc/nginx/ssl/cert.key
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
  rethinkdb:
    image: rethinkdb:2.3.6
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - rethinkdb:/data
  app:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: >
      node runcli.js app 
      --auth-url https://${HOSTNAME}/auth/mock/
      --websocket-url wss://${HOSTNAME}/ --port 3000
    volumes:
      - ./runcli.js:/app/runcli.js
    ports:
      - 10006:9229
    depends_on:
      - rethinkdb
      - auth
      - websocket
  auth:
    image: ${STF_IMAGE}
    restart: unless-stopped
    volumes:
      - ./runcli.js:/app/runcli.js
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: node runcli.js auth-mock --app-url http://${HOSTNAME}/ --port 3000
  processor:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: >
      node runcli.js processor
      --connect-app-dealer tcp://triproxy:7160
      --connect-dev-dealer tcp://dev-triproxy:7260
    volumes:
      - ./runcli.js:/app/runcli.js
    ports:
      - 10002:9229
    depends_on:
      - rethinkdb
      - triproxy
      - dev-triproxy
  triproxy:
    image: ${STF_IMAGE}
    restart: unless-stopped
    command: >
      node runcli.js triproxy app
      --bind-pub "tcp://*:7150"
      --bind-dealer "tcp://*:7160"
      --bind-pull "tcp://*:7170"
    volumes:
      - ./runcli.js:/app/runcli.js  
    ports:
      - 10005:9229
  dev-triproxy:
    image: ${STF_IMAGE}
    restart: unless-stopped
    command: >
      node runcli.js triproxy dev
      --bind-pub "tcp://*:7250"
      --bind-dealer "tcp://*:7260"
      --bind-pull "tcp://*:7270"
    volumes:
      - ./runcli.js:/app/runcli.js
    ports:
      - 7250:7250
      - 7270:7270
      - 10003:9229
  migrate:
    image: ${STF_IMAGE}
    environment:
      - RETHINKDB_PORT_28015_TCP
    volumes:
      - ./runcli.js:/app/runcli.js
    command: node runcli.js migrate
    depends_on:
      - rethinkdb
  reaper:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    depends_on:
      - migrate
      - rethinkdb
      - dev-triproxy
      - triproxy
    volumes:
      - ./runcli.js:/app/runcli.js
    command: >
      node runcli.js reaper dev
      --connect-push tcp://dev-triproxy:7270
      --connect-sub tcp://triproxy:7150
      --heartbeat-timeout 30000
  storage-plugin-apk:
    image: ${STF_IMAGE}
    restart: unless-stopped
    volumes:
      - ./runcli.js:/app/runcli.js
    command: node runcli.js storage-plugin-apk --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-plugin-image:
    image: ${STF_IMAGE}
    restart: unless-stopped
    volumes:
      - ./runcli.js:/app/runcli.js
    command: node runcli.js storage-plugin-image --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
      - ./runcli.js:/app/runcli.js
    command: node runcli.js storage-temp --port 3000 --save-dir /app/data
  websocket:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: >
      node runcli.js
      websocket
      --port 3000
      --storage-url "http://${PUBLIC_IP}/"
      --connect-sub "tcp://triproxy:7150"
      --connect-push "tcp://triproxy:7170"
    volumes:
      - ./runcli.js:/app/runcli.js
    ports:
      - 10004:9229
    depends_on:
      - migrate
      - rethinkdb
      - storage-temp
      - triproxy
      - dev-triproxy
  api:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: >
      node runcli.js
      api
      --port 3000
      --connect-sub tcp://triproxy:7150
      --connect-push tcp://triproxy:7170
      --connect-sub-dev tcp://dev-triproxy:7250
      --connect-push-dev tcp://dev-triproxy:7270
    ports:
      - 10001:9229
    volumes:
      - ./runcli.js:/app/runcli.js
    ports:
      - 9229:9229
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
      - dev-triproxy
  android-provider1:
    image: ${STF_IMAGE}
    restart: unless-stopped
    command: >
      node runcli.js provider --name provider1
      --connect-sub tcp://dev-triproxy:7250 
      --connect-push tcp://dev-triproxy:7270
      --storage-url "http://${PUBLIC_IP}/" 
      --public-ip ${PUBLIC_IP} 
      --min-port=7400 
      --max-port=7410 
      --heartbeat-interval 30000 
      --adb-host 192.168.33.115
      --adb-port 5037
      --group-timeout 20000
      --allow-remote 
      --screen-ws-url-pattern "ws://${HOSTNAME}/d/provider1/<%= serial %>/<%= publicPort %>/"
    volumes:
      - ./runcli.js:/app/runcli.js
    ports:
      - "7400-7410:7400-7410"
    depends_on:
      - migrate
      - storage-temp
      - dev-triproxy
  android-provider2:
    image: ${STF_IMAGE}
    restart: unless-stopped
    command: >
      node runcli.js provider --name provider2
      --connect-sub tcp://dev-triproxy:7250 
      --connect-push tcp://dev-triproxy:7270
      --storage-url "http://${PUBLIC_IP}/" 
      --public-ip ${PUBLIC_IP} 
      --min-port=7411 
      --max-port=7700 
      --heartbeat-interval 30000 
      --adb-host 192.168.33.100
      --adb-port 5037
      --group-timeout 20000
      --allow-remote 
      --screen-ws-url-pattern "ws://${HOSTNAME}/d/provider2/<%= serial %>/<%= publicPort %>/"
    volumes:
        - ./runcli.js:/app/runcli.js
    ports:
      - "7411-7700:7411-7700"
    depends_on:
      - migrate
      - storage-temp
      - dev-triproxy`

**Comment by chaooe** [comment]
.env file
PUBLIC_IP=192.168.63.107
SECRET=secret
RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
HOSTNAME=192.168.63.107
STF_IMAGE=livxtrm/devicefarmer:latest

**Comment by chaooe** [comment]
It is ok to use openstf/stf:v3.4.2 to start

**Comment by chaooe** [comment]
close it as i am using livxtrm/devicefarmer ,  it is ok to use devicefarmer/stf:latest
