### ISSUE TITLE
Device stuck in "Preparing" state

### ISSUE THREAD

**Issue by testifyqa** [DeviceFarmer/stf#640]
**What is the issue or idea you have?**

I have followed the deployment docs for STF device farm. I finally got my STF provider in k8s connected to my ADB server on another machine outside of k8s successfully via a tool called ktunnel.

The device shows up now in STF web UI but is stuck in a "Preparing state" and I do not know why, any ideas would be appreciated here.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

All devices show up correctly with adb devices. It is just the one device.

**Please provide the steps to reproduce the issue.**

Run ADB server. 

Run STF provider and related services etc.

**What is the expected behavior?**

Device is shown as available/connected in STF

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

I am not using STF local.

**Please run `stf doctor` and paste the output here.**

Not sure where to run this when deploying all the separate services etc.

**Comment by testifyqa** [comment]
Some logs from `stf-provider` ...

```
2023-02-17T18:33:09.419Z INF/provider 8 [*] Subscribing to permanent channel "BkUnJHbcTgC2gsVdyInbtA=="
2023-02-17T18:33:09.425Z INF/provider 8 [*] Sending output to "tcp://openstf-triproxy-dev:7270"
2023-02-17T18:33:09.426Z INF/provider 8 [*] Receiving input from "tcp://openstf-triproxy-dev:7250"
2023-02-17T18:33:09.442Z INF/provider 8 [*] Tracking devices
2023-02-17T18:33:09.443Z INF/provider 8 [*] Found device "0822382308" (device)
2023-02-17T18:33:09.467Z INF/provider 8 [*] Registered device "0822382308"
2023-02-17T18:33:09.785Z INF/device:support:push 18 [0822382308] Sending output to "tcp://openstf-triproxy-dev:7270"
2023-02-17T18:33:09.788Z INF/device 18 [0822382308] Preparing device
2023-02-17T18:33:10.103Z INF/device:support:sub 18 [0822382308] Receiving input from "tcp://openstf-triproxy-dev:7250"
2023-02-17T18:33:10.104Z INF/device:support:sub 18 [0822382308] Subscribing to permanent channel "*ALL"
2023-02-17T18:33:11.108Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:12.109Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:13.110Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:14.112Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:15.113Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:16.115Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:17.117Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:18.117Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:19.119Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:19.448Z INF/provider 8 [*] Providing 0 of 1 device(s); waiting for "0822382308"
2023-02-17T18:33:20.119Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:21.120Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:22.121Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:23.122Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:24.123Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:25.124Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:26.125Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:27.126Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:28.127Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:29.128Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:29.457Z INF/provider 8 [*] Providing 0 of 1 device(s); waiting for "0822382308"
2023-02-17T18:33:30.128Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:31.129Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:32.131Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:33.133Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:34.134Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:35.137Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:36.138Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:37.139Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:38.140Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:39.141Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:39.458Z INF/provider 8 [*] Providing 0 of 1 device(s); waiting for "0822382308"
2023-02-17T18:33:40.142Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:41.143Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:42.144Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:43.145Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:44.147Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:45.148Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:46.149Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:47.150Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:48.152Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:49.154Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:49.468Z INF/provider 8 [*] Providing 0 of 1 device(s); waiting for "0822382308"
2023-02-17T18:33:50.153Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:51.154Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:52.156Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:53.157Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:54.158Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:55.159Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:56.160Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:57.162Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:58.163Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:59.164Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:33:59.478Z INF/provider 8 [*] Providing 0 of 1 device(s); waiting for "0822382308"
2023-02-17T18:34:00.166Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:01.168Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:02.168Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:03.169Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:04.171Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:05.173Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:06.175Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:07.177Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:08.178Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:09.179Z INF/device:support:adb 18 [0822382308] Waiting for boot to complete
2023-02-17T18:34:09.488Z INF/provider 8 [*] Providing 0 of 1 device(s); waiting for "0822382308"
2023-02-17T18:34:10.110Z FTL/device 18 [0822382308] Setup had an error TimeoutError: operation timed out
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
From previous event:
    at ensureBootComplete (/app/lib/units/device/support/adb.js:25:10)
    at /app/lib/units/device/support/adb.js:28:12
    at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
    at /app/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
2023-02-17T18:34:10.111Z FTL/util:lifecycle 18 [0822382308] Shutting down due to fatal error
2023-02-17T18:34:10.117Z INF/provider 8 [*] Cleaning up device worker "0822382308"
2023-02-17T18:34:10.118Z ERR/provider 8 [*] Device worker "0822382308" died with code 1
2023-02-17T18:34:10.118Z INF/provider 8 [*] Restarting device worker "0822382308"
2023-02-17T18:34:10.858Z INF/device:support:push 27 [0822382308] Sending output to "tcp://openstf-triproxy-dev:7270"
2023-02-17T18:34:10.861Z INF/device 27 [0822382308] Preparing device
2023-02-17T18:34:11.165Z INF/device:support:sub 27 [0822382308] Receiving input from "tcp://openstf-triproxy-dev:7250"
2023-02-17T18:34:11.166Z INF/device:support:sub 27 [0822382308] Subscribing to permanent channel "*ALL"
2023-02-17T18:34:12.171Z INF/device:support:adb 27 [0822382308] Waiting for boot to complete
```

**Comment by testifyqa** [comment]
If I run `adb shell getprop | grep completed` I see...

`sys.boot_completed: 1`

**Comment by testifyqa** [comment]
Closing this actually as I think the issue is because I'm on a special device with extra security that does not allow using insecure ADB keys
