### ISSUE TITLE
STF Port number selection

### ISSUE THREAD

**Issue by esawyja** [DeviceFarmer/stf#647]
Port scanning take a long time to find a free port and we would like to find out where in the code this is defined.
It looks like it increments the port to use by 4, see stf provider logs below
The idea is to change it to a random port in a specific range or look up the last port in use and increment that.
Could someone indicate where this selection happens in the code?

2023-03-27T23:35:24.815Z INF/device:plugins:screen:stream 14503 [R3CN30YC3KZ] Starting WebSocket server on port 7536
2023-03-27T23:35:24.821Z FTL/device 14503 [R3CN30YC3KZ] Setup had an error **Error: listen EADDRINUSE :::7536**
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at new WebSocketServer (/usr/lib/node_modules/stf/node_modules/ws/lib/WebSocketServer.js:76:20)
    at createServer (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:427:17)
From previous event:
    at createServer (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:433:14)
    at /usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:451:12
    at SerialSyrup.ParallelSyrup.invoke (/usr/lib/node_modules/stf/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
    at /usr/lib/node_modules/stf/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2023-03-27T23:35:24.822Z FTL/util:lifecycle 14503 [R3CN30YC3KZ] Shutting down due to fatal error
.......
2023-03-27T23:35:30.713Z FTL/device 14787 [R3CN30YC3KZ] Setup had an error **Error: listen EADDRINUSE :::7540**
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at new WebSocketServer (/usr/lib/node_modules/stf/node_modules/ws/lib/WebSocketServer.js:76:20)
    at createServer (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:427:17)
From previous event:
    at createServer (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:433:14)
    at /usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:451:12
    at SerialSyrup.ParallelSyrup.invoke (/usr/lib/node_modules/stf/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
    at /usr/lib/node_modules/stf/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2023-03-27T23:35:30.714Z FTL/util:lifecycle 14787 [R3CN30YC3KZ] Shutting down due to fatal error
......
2023-03-27T23:35:37.435Z INF/device:plugins:screen:stream 14988 [R3CN30YC3KZ] Starting WebSocket server on port 7544
2023-03-27T23:35:37.442Z FTL/device 14988 [R3CN30YC3KZ] Setup had an error **Error: listen EADDRINUSE :::7544**
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at new WebSocketServer (/usr/lib/node_modules/stf/node_modules/ws/lib/WebSocketServer.js:76:20)
    at createServer (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:427:17)
From previous event:
    at createServer (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:433:14)
    at /usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:451:12
    at SerialSyrup.ParallelSyrup.invoke (/usr/lib/node_modules/stf/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
    at /usr/lib/node_modules/stf/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2023-03-27T23:35:37.443Z FTL/util:lifecycle 14988 [R3CN30YC3KZ] Shutting down due to fatal error

This happens on all devices when connecting, the extract is from the stf provider logs
It does eventually find an open port, but it does take a long time to find a free port, in this installation we have 100 devices connected.

When it fails on ADDRESS in USE, it appears to restart the connection process from scratch, it checks APK version, device capabilities etc, this causes the extended delay before the device goes online. Any help or information would be appreciated.

**Comment by denis99999** [comment]
@esawyja, @DevlinGriggs, please fill in the issue template correctly because what I see in your logs are `EADDRINUSE` errors and therefore a priori it is not an `STF` problem (i.e. many users manage many devices like you), did you configure the port range correctly at device provider side ? Please provide your full systemd files or docker compose file? Are you trying to connect around 100 devices through a single provider? On which physical machine?

**Comment by esawyja** [comment]
please fill in the issue template correctly because what I see in your logs are EADDRINUSE errors and therefore a priori it is not an STF problem (i.e. many users manage many devices like you), did you configure the port range correctly at device provider side ? 

Hi Dennis, I do configure the port range in the systemctl file, see below
```
[root@ httpd]# systemctl status stf
● stf.service - SmartPhone Test Farm
   Loaded: loaded (/usr/lib/systemd/system/stf.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-03-16 02:25:21 CDT; 1 months 16 days ago
 Main PID: 1921 (start_stf.sh)
   CGroup: /system.slice/stf.service
           ├─1921 /bin/bash /usr/lib/node_modules/stf/bin/start_stf.sh &
           ├─2066 node /usr/local/bin/stf local --public-ip xxx.xxx.xxx.xxx --bind-dev-pull tcp://0.0.0.0:7116 --bind-dev-pub tcp://0.0.0.0:7114
           ├─2079 /usr/bin/node /usr/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113
           ├─2080 /usr/bin/node /usr/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://0.0.0.0:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://0.0.0.0:7116
           ├─2085 /usr/bin/node /usr/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115
           ├─2090 /usr/bin/node /usr/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115
           ├─2103 /usr/bin/node /usr/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://0.0.0.0:7116 --connect-sub tcp://127.0.0.1:7111
           ├─2109 /usr/bin/node /usr/lib/node_modules/stf/lib/cli provider --name xxxxxxx --min-port 7400 --max-port 7700 --connect-sub tcp://0.0.0.0:7114 --connect-push tcp://0.0.0.0:7116 --group-timeout 900 --pu...
           ├─2115 /usr/bin/node /usr/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://xxx.xxx.xxx.xxx:7100/
           ├─2121 /usr/bin/node /usr/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://10.119.102.86:7100/auth/mock/ --websocket-url http://10.119.102.86:7110/
           ├─2127 /usr/bin/node /usr/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://0.0.0.0:7116 --connect-sub-dev t...
           ├─2133 /usr/bin/node /usr/lib/node_modules/stf/lib/cli groups-engine --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://0.0.0.0:7116 --connect-sub-dev tcp://0.0.0.0:7114
           ├─2138 /usr/bin/node /usr/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113
           ├─2140 /usr/bin/node /usr/lib/node_modules/stf/lib/cli storage-temp --port 7102
           ├─2145 /usr/bin/node /usr/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/
           ├─2154 /usr/bin/node /usr/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/
           ├─2163 /usr/bin/node /usr/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage...
           └─2185 adb -P 5037 fork-server server

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[root@ilscha03-netcss-02 httpd]#
``` 

Please provide your full systemd files or docker compose file? 
The systemctl file runs a script and in the script is this below
`/usr/local/bin/stf local --public-ip $ownip --bind-dev-pull tcp://0.0.0.0:7116 --bind-dev-pub tcp://0.0.0.0:7114 &> /var/log/stf/stf.log`

Are you trying to connect around 100 devices through a single provider? 
Each device has a small computer connected to it and on the main server I would start it as below

`node /usr/local/bin/stf provider --name xxxxxxxxxxxxxx --no-cleanup --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip xxx.xxx.xxx --storage-url http://127.0.0.1:7100/ --adb-host 127.0.0.1 --adb-port 5105 --vnc-initial-size 600x800 --mute-master never --allow-remote`

On which physical machine?
Yes, running Centos, 64G RAM

**Comment by denis99999** [comment]
@esawyja , I am not sure to well understand your architecture, it seems you run all units on a single big machine (which may explain the` EADDRINUSE` error) and this is not the good way you should deploy STF, in fact `stf local` is not supported in production mode, it is a deployment model reserved for STF development, you should instead follow the full deployment model described in `DEPLOYMENT.md` file in which the `provider` unit as well as `ADB` unit are started on each machine on which some devices are connected, or else you have only to deploy only one `provider` unit on your big main machine if all devices are connected to it.

**Comment by esawyja** [comment]
Thanks Denis, I have tried the docker way before, but I could not get it working, I'll try again...
So the way that we do it, is to have a single board computer (SBC) that connect to the main server that runs stf via TCP/IP. There are multiple of these SBCs in different places. We then connect the Android phones to these SBCs and set up tunnels for them to do the adb functions on the main server, so adb is started on these SBCs, the stf provider is started on the main server and points to the tunnel that was setup for the SBC.
So what you are saying is to run the 
```
adbd.service
You need to have a single adbd.service unit running on each host where you have devices connected.
```
on each of the SBCs? In docker?

**Comment by denis99999** [comment]
yes on each SBC you have to run a `ADB` unit and a `provider` unit, and the last communicates with the main server in which no `ADB/provider` units are running, with or without docker it is your choice, all necessary information are provided in `DEPLOYMENT.md` file.
