### ISSUE TITLE
npm install command failling

### ISSUE THREAD

**Issue by Nouxx** [DeviceFarmer/stf#65]
**What is the issue or idea you have?**

running `npm i @devicefarmer/stf` returns an error

It seems that there this an issue with `jpeg-turbo@0.4.1`. I searched for this version but couldn't find it in [npmjs](https://www.npmjs.com/package/jpeg-turbo) nor in [github](https://github.com/sorccu/node-jpeg-turbo/releases), the latest version seems to be 0.4.0

**Logs**

```
> @devicefarmer/jpeg-turbo@0.4.1 install /usr/local/lib/node_modules/@devicefarmer/stf/node_modules/@devicefarmer/jpeg-turbo
> node ./prebuilt-bindings install

[prebuilt-bindings] => Testing '/usr/local/lib/node_modules/@devicefarmer/stf/node_modules/@devicefarmer/jpeg-turbo/build/Release/jpegturbo.node'...
[prebuilt-bindings] => Binding not found or incompatible
[prebuilt-bindings] => Downloading 'https://github.com/sorccu/node-jpeg-turbo/releases/download/v0.4.1/jpegturbo-83-darwin-x64.node.gz'...
[prebuilt-bindings] => Server responded with '404 Not Found'
[prebuilt-bindings] => Downloading 'https://github.com/sorccu/node-jpeg-turbo/releases/download/v0.4.1/jpegturbo-83-darwin-x64.node'...
[prebuilt-bindings] => Server responded with '404 Not Found'
[prebuilt-bindings] => Unable to download prebuilt bindings: No compatible bindings found
[prebuilt-bindings] => Building from source...
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@devicefarmer/stf/node_modules/@devicefarmer/jpeg-turbo
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
Usage: prebuilt-bindings [command...] [options]

Commands:
  build     Builds bindings locally.
  clean     Removes installed bindings.
  config    Prints out the resolved config. Can be useful to understand what
            prebuilt-bindings sees.
  install   Installs prebuilt bindings or builds them if none can be found.
            Default command if none is given.
  pack      Packs configured bindings into properly named individual archives
            for easy deployment.

Options:
  --no-download   Don't download prebuilt bindings. (PREBUILT_BINDINGS=0)
  --no-build      Don't build if prebuilt bindings can't be found.
  -h, --help      Show usage.

Error: node-gyp failed with status 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @devicefarmer/jpeg-turbo@0.4.1 install: `node ./prebuilt-bindings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @devicefarmer/jpeg-turbo@0.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Let me know if you need the complete log file

**Comment by koral--** [comment]
0.4.1 is there: https://www.npmjs.com/package/@devicefarmer/jpeg-turbo

> No Xcode or CLT version detected!
This seems to be a real cause
You can try invoking: `xcode-select --install`

Anyway we're going to replace the current jpeg-turbo with https://github.com/Julusian/node-jpeg-turbo which publishes prebuilt files.

**Comment by abdulrahman5** [comment]
@Nouxx running into a similar issue, how were you able to resolve this? xcode-select didnt resolve the issue for me

**Comment by koral--** [comment]
Current code on master branch already uses `@julusian/jpeg-turbo` which have prebuilt binaries for macOS  available.

**Comment by Nouxx** [comment]
Hi,

Sorry to get back to you lately
Installing properly the Command Line Tools and running the same npm install command is still returning an error:

```
npm install -g @devicefarmer/stf
npm WARN deprecated @slack/client@3.16.0: v3.x and lower are no longer supported. see migration guide: https://github.com/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.76.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/stf -> /usr/local/lib/node_modules/@devicefarmer/stf/bin/stf

> dtrace-provider@0.8.8 install /usr/local/lib/node_modules/@devicefarmer/stf/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> @devicefarmer/jpeg-turbo@0.4.1 install /usr/local/lib/node_modules/@devicefarmer/stf/node_modules/@devicefarmer/jpeg-turbo
> node ./prebuilt-bindings install

[prebuilt-bindings] => Testing '/usr/local/lib/node_modules/@devicefarmer/stf/node_modules/@devicefarmer/jpeg-turbo/build/Release/jpegturbo.node'...
[prebuilt-bindings] => Binding not found or incompatible
[prebuilt-bindings] => Downloading 'https://github.com/sorccu/node-jpeg-turbo/releases/download/v0.4.1/jpegturbo-72-darwin-x64.node.gz'...
[prebuilt-bindings] => Server responded with '404 Not Found'
[prebuilt-bindings] => Downloading 'https://github.com/sorccu/node-jpeg-turbo/releases/download/v0.4.1/jpegturbo-72-darwin-x64.node'...
[prebuilt-bindings] => Server responded with '404 Not Found'
[prebuilt-bindings] => Unable to download prebuilt bindings: No compatible bindings found
[prebuilt-bindings] => Building from source...
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_0 Release/obj/gen/jccolor-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_1 Release/obj/gen/jcgray-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_2 Release/obj/gen/jcsample-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_3 Release/obj/gen/jdcolor-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_4 Release/obj/gen/jdmerge-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_5 Release/obj/gen/jdsample-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_6 Release/obj/gen/jfdctflt-sse-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_7 Release/obj/gen/jfdctfst-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_8 Release/obj/gen/jfdctint-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_9 Release/obj/gen/jidctflt-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_10 Release/obj/gen/jidctfst-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_11 Release/obj/gen/jidctint-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_12 Release/obj/gen/jidctred-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_13 Release/obj/gen/jquantf-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_14 Release/obj/gen/jquanti-sse2-64.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcapimin.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcapistd.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jccoefct.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jccolor.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcdctmgr.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jchuff.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcinit.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcmainct.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcmarker.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcmaster.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcomapi.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcparam.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcphuff.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcprepct.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcsample.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jctrans.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdapimin.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdapistd.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdatadst.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdatasrc.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdcoefct.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdcolor.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jddctmgr.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdhuff.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdinput.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdmainct.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdmarker.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdmaster.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdmerge.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdphuff.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdpostct.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdsample.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdtrans.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jerror.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jfdctflt.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jfdctfst.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jfdctint.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jidctflt.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jidctfst.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jidctint.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jidctred.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jquant1.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jquant2.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jutils.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jmemmgr.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jmemnobs.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jaricom.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcarith.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdarith.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/turbojpeg.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/transupp.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdatadst-tj.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jdatasrc-tj.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/simd/jsimd_x86_64.o
  LIBTOOL-STATIC Release/libjpeg-turbo.a
  CXX(target) Release/obj.target/jpegturbo/src/buffersize.o
../src/buffersize.cc:38:25: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  sampObject = options->Get(New("subsampling").ToLocalChecked());
                        ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8.h:3553:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8config.h:328:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/buffersize.cc:43:43: error: too few arguments to function call, single argument 'context' was
      not specified
    jpegSubsamp = sampObject->Uint32Value();
                  ~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8.h:2707:3: note: 'Uint32Value' declared
      here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8config.h:368:31: note: expanded from
      macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/buffersize.cc:58:26: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  widthObject = options->Get(New("width").ToLocalChecked());
                         ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8.h:3553:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8config.h:328:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/buffersize.cc:65:36: error: too few arguments to function call, single argument 'context' was
      not specified
  width = widthObject->Uint32Value();
          ~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8.h:2707:3: note: 'Uint32Value' declared
      here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8config.h:368:31: note: expanded from
      macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/buffersize.cc:68:27: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  heightObject = options->Get(New("height").ToLocalChecked());
                          ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8.h:3553:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8config.h:328:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/buffersize.cc:75:38: error: too few arguments to function call, single argument 'context' was
      not specified
  height = heightObject->Uint32Value();
           ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8.h:2707:3: note: 'Uint32Value' declared
      here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/CLEMENT/Library/Caches/node-gyp/12.18.0/include/node/v8config.h:368:31: note: expanded from
      macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/buffersize.cc:86:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../../nan/nan.h:1741:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/buffersize.cc:102:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      callback->Call(1, argv);
                ^
../../../nan/nan.h:1741:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
5 warnings and 3 errors generated.
make: *** [Release/obj.target/jpegturbo/src/buffersize.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@devicefarmer/stf/node_modules/@devicefarmer/jpeg-turbo
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
Usage: prebuilt-bindings [command...] [options]

Commands:
  build     Builds bindings locally.
  clean     Removes installed bindings.
  config    Prints out the resolved config. Can be useful to understand what
            prebuilt-bindings sees.
  install   Installs prebuilt bindings or builds them if none can be found.
            Default command if none is given.
  pack      Packs configured bindings into properly named individual archives
            for easy deployment.

Options:
  --no-download   Don't download prebuilt bindings. (PREBUILT_BINDINGS=0)
  --no-build      Don't build if prebuilt bindings can't be found.
  -h, --help      Show usage.

Error: node-gyp failed with status 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @devicefarmer/jpeg-turbo@0.4.1 install: `node ./prebuilt-bindings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @devicefarmer/jpeg-turbo@0.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/CLEMENT/.npm/_logs/2020-10-13T08_04_19_120Z-debug.log
FRL-C02C80FXLVDN:~ CLEMENT$ 
```

I'm on macOS if it might help

**Comment by jachstet-sea** [comment]
This might be your problem:

> gyp ERR! node -v v12.18.0
> gyp ERR! node-gyp -v v5.1.0

In the past, OpenSTF required NodeJS version 8 or *older*. This seems still to be the case: https://github.com/DeviceFarmer/stf#requirements and https://github.com/DeviceFarmer/stf/issues/37

**Comment by koral--** [comment]
The issue from 1st post should be outdated now since version using alternative jpeg-turbo has been released.
Regarding 2nd issue indeed we currently use v`8.9.3` .
Giving that I'm closing this ticket, but feel free to comment if needed.

**Comment by Nouxx** [comment]
Yup, my bad.. downgrading to node v8.17 worked just fine!
