### ISSUE TITLE
STFService repeatedly prompts for installation after updating to device-farmer v3.6.5

### ISSUE THREAD

**Issue by merih-sakarya** [DeviceFarmer/stf#660]
**Description:**

After updating device-farmer from version 3.6.1 to 3.6.5, I have encountered an issue with the installation of STFService. Each time the device disconnects from the minicap service, the "device worker" restarts and tries to install STFService again. As a result, the phone prompts me to "install this app via usb" and requires manual confirmation by pressing "Install". Despite checking the "remember my choice" box, the prompt still appears every time. This issue did not exist before the upgrade.

**Device details:**

XIAOMI MI 9
Android Version 11
SDK 30

**Logs:**

```
2023-05-09T18:53:47.764Z INF/device:plugins:group 71422 [d7f3319] Unsubscribing from group channel "VsPouCEfSbO6eCwhuzUpmQ=="
2023-05-09T18:53:48.206Z INF/device:plugins:screen:stream 71422 [d7f3319] Requesting frame producer to stop
2023-05-09T18:53:48.209Z INF/device:plugins:screen:stream 71422 [d7f3319] Disconnecting from minicap service
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on WebSocket instance at:
    at WebSocket.finalize (/Users/host-user/Development/workspaces/host-company/Live-Testing/devicefarmer/node_modules/ws/lib/WebSocket.js:182:41)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
2023-05-09T18:53:48.295Z INF/provider 71417 [*] Cleaning up device worker "d7f3319"
2023-05-09T18:53:48.301Z ERR/provider 71417 [*] Device worker "d7f3319" died with code 1
2023-05-09T18:53:48.303Z INF/provider 71417 [*] Restarting device worker "d7f3319"
2023-05-09T18:53:50.481Z INF/device:support:push 71492 [d7f3319] Sending output to "tcp://127.0.0.1:7270"
2023-05-09T18:53:50.497Z INF/device 71492 [d7f3319] Preparing device
2023-05-09T18:53:53.077Z INF/device:support:sub 71492 [d7f3319] Receiving input from "tcp://127.0.0.1:7250"
2023-05-09T18:53:53.079Z INF/device:support:sub 71492 [d7f3319] Subscribing to permanent channel "*ALL"
2023-05-09T18:53:53.163Z INF/device:support:properties 71492 [d7f3319] Loading properties
2023-05-09T18:53:53.212Z INF/device:support:sdk 71492 [d7f3319] Supports SDK 30
2023-05-09T18:53:53.214Z INF/device:support:abi 71492 [d7f3319] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2023-05-09T18:53:53.442Z INF/device:resources:minicap 71492 [d7f3319] Installing "/Users/host-user/Development/workspaces/host-company/Live-Testing/devicefarmer/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2023-05-09T18:53:53.444Z INF/device:resources:minicap 71492 [d7f3319] Installing "/Users/host-user/Development/workspaces/host-company/Live-Testing/devicefarmer/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-30/minicap.so" as "/data/local/tmp/minicap.so"
2023-05-09T18:53:53.445Z INF/device:resources:minicap 71492 [d7f3319] Installing "/Users/host-user/Development/workspaces/host-company/Live-Testing/devicefarmer/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/noarch/minicap.apk" as "/data/local/tmp/minicap.apk"
2023-05-09T18:53:53.743Z INF/device:resources:service 71492 [d7f3319] Checking whether we need to install STFService
2023-05-09T18:53:53.849Z INF/device:resources:service 71492 [d7f3319] Running version check
2023-05-09T18:53:54.588Z INF/device:resources:service 71492 [d7f3319] Installing STFService
2023-05-09T18:54:09.904Z FTL/device 71492 [d7f3319] Setup had an error Error: /data/local/tmp/STFService.apk could not be installed [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
    at /Users/host-user/Development/workspaces/host-company/Live-Testing/devicefarmer/node_modules/@devicefarmer/adbkit/lib/adb/command/host-transport/install.js:28:23
    at processImmediate (internal/timers.js:456:21)
2023-05-09T18:54:09.905Z FTL/util:lifecycle 71492 [d7f3319] Shutting down due to fatal error

```
**Steps to reproduce:**

1. Update device-farmer from version 3.6.1 to 3.6.5.
2. Attempt to use the minicap service.
3. Observe that after disconnecting from the minicap service, the "device worker" restarts and tries to install STFService again, prompting for manual confirmation each time.

**Expected behavior:**

The STFService should be installed without prompting for manual confirmation after the first installation, especially when the "remember my choice" box is checked. This was the behavior before the upgrade.

**Actual behavior:**

The phone prompts for manual confirmation to install STFService each time the "device worker" restarts after disconnecting from the minicap service, even when the "remember my choice" box is checked.

**Comment by merih-sakarya** [comment]
@denis99999 Thanks a lot :) I confirm that everything is working as expected now. Thanks again for your help!
