### ISSUE TITLE
On pixel phone jp.co.cyberagent.stf could not be assigned a valid UID

### ISSUE THREAD

**Issue by pr4bh4sh** [DeviceFarmer/stf#738]
**Is your feature request related to a problem? Please describe.**
Google Pixel has a limitation on the number of times an application can be installed. This creates an issue with SFT agent startup when the number of installations crosses 10000 times. I have been facing this issue on pixel 5,6,7,8. The issue has already been reported by Sacucelabs to Google https://issuetracker.google.com/issues/170867658. Google declined to fix the issue and no persistent alternative solution was provided.

**Describe the solution you'd like**
1. Can we reduce the installation if the device already has the same version of the STF application already installed and just start the service?
2. Reinstall the app only when the service fails to restart with the existing app.

**Describe alternatives you've considered**
The device currently needs to be restarted(which doesn't solve the issue most of the time) or format the device which provides some time before the issue comes back. However, the device needs to be set up again.

**Additional context**
```bash
12-11 12:07:09.618 21498 21565 I BugleRcsEngine: [175] cagd.handleMessage: RcsEngineImpl[DUAL_REG]:[470ac443-32e2]>Handler: handleMessage processing message:[NOTIFY_UPTIME_IGNORE_STATE_CHANGED] with [non-null]:RcsEngineImpl reference
12-11 12:07:09.618  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.618 21498 21538 I BugleRcsEngine: [164] bzmg.c: Connected state: [1], networkType: [WIFI]
12-11 12:07:09.618  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.619  2409  3037 E PhoneInterfaceManager: getCarrierPrivilegeStatusForUid: Invalid subId
12-11 12:07:09.619 21498 21565 I BugleRcsEngine: [175] cado.i: ProvisioningEngineDataRetriever: RCS Configuration storage in Bugle is disabled by p/h flag, using ProvisioningEngineStateCacheUtil.getProvisioningConfigurationForGivenSimIfExist()
12-11 12:07:09.620  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.620  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.621  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.621  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.621  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.621  1569  1993 W IPCThreadState: Sending oneway calls to frozen process.
12-11 12:07:09.624 15997 15997 I Wildlife_WildlifeVpnManagerImpl: toggleVpnByFeaturePreferences, -1, 1, -1, 1
12-11 12:07:09.624 15997 15997 I Wildlife_WildlifeVpnManagerImpl: createFirstPromptNotification() Same network. Ignored.
12-11 12:07:09.627  1569  1993 D ConnectivityService: NetReassign [no changes] [c 0] [a 1] [i 3]
12-11 12:07:09.939  1569  1770 W PackageManager: Not removing non-existent package jp.co.cyberagent.stf
12-11 12:07:10.132  4130  4130 I Finsky  : [2] aibz.c(76): VerifyApps: Install-time verification requested for package jp.co.cyberagent.stf, id = 15078
12-11 12:07:10.149  4130 29965 I Finsky  : [2496] VerifyAppsInstallTask.aku(63): VerifyApps: Anti-malware verification task started for package=jp.co.cyberagent.stf
12-11 12:07:10.152  1569  1770 I PackageManager: Integrity check passed for file:///data/app/vmdl143373439.tmp
12-11 12:07:10.155  4130 29965 I Finsky  : [2496] VerifyAppsInstallTask.aku(275): VerifyApps: Skipping verification. Disabled by user setting
12-11 12:07:10.156  4130 29965 I Finsky  : [2496] VerifyAppsInstallTask.aku(748): VerifyApps: Skipping anti malware verification (preconditions not met). package=jp.co.cyberagent.stf
12-11 12:07:10.158  4130 29965 I Finsky  : [2496] VerifyPerSourceInstallationConsentInstallTask.aku(231): PSIC verification started with installer uid: 2000 package name: com.android.shell, originating uid: -1
12-11 12:07:10.162  4130 29965 I Finsky  : [2496] VerifyInstallTask.i(29): VerifyApps: Returning package verification result id=15078, result=ALLOW
12-11 12:07:10.163  1569  1770 I PackageManager: Continuing with installation of file:///data/app/vmdl143373439.tmp
12-11 12:07:10.165  4130  4130 I Finsky  : [2] VerifyInstallTask.akt(58): VerifyApps: Verification complete: id=15078, package_name=jp.co.cyberagent.stf
12-11 12:07:10.206  1569  1770 W PackageManager: Package jp.co.cyberagent.stf could not be assigned a valid UID
12-11 12:07:10.209  1569  1770 W PackageManager: Scanning Failed.
12-11 12:07:10.209  1569  1770 W PackageManager: com.android.server.pm.PackageManagerException: Package jp.co.cyberagent.stf could not be assigned a valid UID
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.Settings.registerAppIdLPw(Settings.java:1303)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallPackageHelper.optimisticallyRegisterAppId(InstallPackageHelper.java:3977)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallPackageHelper.installPackagesLI(InstallPackageHelper.java:1001)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallPackageHelper.installPackagesTraced(InstallPackageHelper.java:915)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.processApkInstallRequests(InstallingSession.java:540)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.processInstallRequests(InstallingSession.java:529)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.lambda$processPendingInstall$0(InstallingSession.java:288)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.$r8$lambda$tqRjKCgCJYNNnnY7Qw5M5BHLup8(InstallingSession.java:0)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at android.os.Handler.handleCallback(Handler.java:958)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at android.os.Looper.loopOnce(Looper.java:205)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at android.os.Looper.loop(Looper.java:294)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-11 12:07:10.209  1569  1770 W PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-11 12:07:10.209  1569  2290 V SafetySourceDataValidat: Package: com.android.vending has expected signature
12-11 12:07:10.209  1569  2290 V SafetySourceDataValidat: Package: com.android.vending has expected signature
12-11 12:07:10.216  1569  1770 D PackageInstallerSession: Marking session 143373439 as failed: INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package jp.co.cyberagent.stf could not be assigned a valid UID
12-11 12:07:10.401 31279 31279 W adbd    : timeout expired while flushing socket, closing
12-11 12:07:12.046  1569  1770 W PackageManager: Not removing non-existent package jp.co.cyberagent.stf
12-11 12:07:12.273  4130  4130 I Finsky  : [2] aibz.c(76): VerifyApps: Install-time verification requested for package jp.co.cyberagent.stf, id = 15079
12-11 12:07:12.291  4130 25538 I Finsky  : [2470] VerifyAppsInstallTask.aku(63): VerifyApps: Anti-malware verification task started for package=jp.co.cyberagent.stf
12-11 12:07:12.296  4130 25538 I Finsky  : [2470] VerifyAppsInstallTask.aku(275): VerifyApps: Skipping verification. Disabled by user setting
12-11 12:07:12.297  4130 25538 I Finsky  : [2470] VerifyAppsInstallTask.aku(748): VerifyApps: Skipping anti malware verification (preconditions not met). package=jp.co.cyberagent.stf
12-11 12:07:12.299  4130 25538 I Finsky  : [2470] VerifyPerSourceInstallationConsentInstallTask.aku(231): PSIC verification started with installer uid: 2000 package name: com.android.shell, originating uid: -1
12-11 12:07:12.305  1569  1770 I PackageManager: Integrity check passed for file:///data/app/vmdl953533143.tmp
12-11 12:07:12.305  4130 25538 I Finsky  : [2470] VerifyInstallTask.i(29): VerifyApps: Returning package verification result id=15079, result=ALLOW
12-11 12:07:12.306  1569  1770 I PackageManager: Continuing with installation of file:///data/app/vmdl953533143.tmp
12-11 12:07:12.308  4130  4130 I Finsky  : [2] VerifyInstallTask.akt(58): VerifyApps: Verification complete: id=15079, package_name=jp.co.cyberagent.stf
12-11 12:07:12.346  1569  2298 V SafetySourceDataValidat: Package: com.android.vending has expected signature
12-11 12:07:12.346  1569  2298 V SafetySourceDataValidat: Package: com.android.vending has expected signature
12-11 12:07:12.360  1569  1770 W PackageManager: Package jp.co.cyberagent.stf could not be assigned a valid UID
12-11 12:07:12.362  1569  1770 W PackageManager: Scanning Failed.
12-11 12:07:12.362  1569  1770 W PackageManager: com.android.server.pm.PackageManagerException: Package jp.co.cyberagent.stf could not be assigned a valid UID
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.Settings.registerAppIdLPw(Settings.java:1303)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallPackageHelper.optimisticallyRegisterAppId(InstallPackageHelper.java:3977)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallPackageHelper.installPackagesLI(InstallPackageHelper.java:1001)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallPackageHelper.installPackagesTraced(InstallPackageHelper.java:915)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.processApkInstallRequests(InstallingSession.java:540)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.processInstallRequests(InstallingSession.java:529)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.lambda$processPendingInstall$0(InstallingSession.java:288)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession.$r8$lambda$tqRjKCgCJYNNnnY7Qw5M5BHLup8(InstallingSession.java:0)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.pm.InstallingSession$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at android.os.Handler.handleCallback(Handler.java:958)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at android.os.Looper.loopOnce(Looper.java:205)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at android.os.Looper.loop(Looper.java:294)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-11 12:07:12.362  1569  1770 W PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-11 12:07:12.371  1569  1770 D PackageInstallerSession: Marking session 953533143 as failed: INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package jp.co.cyberagent.stf could not be assigned a valid UID
12-11 12:07:12.488 31279 31279 W adbd    : timeout expired while flushing socket, closing
12-11 12:07:13.180 31279 31285 I adbd    : USB event: FUNCTIONFS_SUSPEND
12-11 12:07:13.209   940  2025 I android.hardware.usb.aidl-service: port0
12-11 12:07:13.210   940  2025 I android.hardware.usb.aidl-service: 0:port0 connected:0 canChangeMode:1 canChagedata:0 canChangePower:0 usbDataEnabled:1
12-11 12:07:13.212   940  2025 I android.hardware.usb.aidl-service: ContaminantDetectionStatus:2 ContaminantProtectionStatus:0
12-11 12:07:13.213   940  2025 I android.hardware.usb.aidl-service: powerTransferLimited:0

```

**Comment by denis99999** [comment]
@pr4bh4sh , what version of Devicefarmer/STF are you using ?

Normally, the STF agent is installed on the device only if it is not already installed or if it is already installed but the current version is not the same the required version by the STF server.

Nervertheless, it has hapenned for older STF versions the required version of the STF agent in the STF server code was not updated to the real version of the STF agent embedded as an `.apk` in the STF server distribution, which could raise the issue you are currently experiencing.

So, I recommend you to upgrade your STF server to the latest version, that is the `v3.6.6` one which works fine.

**Comment by pr4bh4sh** [comment]
Hi @denis99999. I am using docker image `devicefarmer/stf:3.6.6`. I have created a device agent consistent with Android 14 devices. Which the last release of [stf-service](https://github.com/DeviceFarmer/STFService.apk) does not support. So I rebuilt the stf-service apk from the latest master and replaced it inside the running device-farmer container. 

I'm not sure if that could be causing the issue. Do we get the apk version number from the apk itself when the version number is checked or it's stored somewhere?

I see that there is no docker image released after 3.6.6 and it contains the stf-service apk which doesn't support Android 14. Would it be possible to release a new docker image with the latest master stf-service apk any time soon?

**Comment by denis99999** [comment]
@pr4bh4sh , for Android 14 compatibility you have to use the `latest` docker image, let me know if it solves your problem ?

**Comment by pr4bh4sh** [comment]
I have updated the docker image to the latest. Devices are connected and operational. It does solve the issue with devices stuck in the preparing state, so I'm closing the task and report back if the issue happens again.

Thanks for your help.
