### ISSUE TITLE
login failed serveral times(with ldap) will throw error

### ISSUE THREAD

**Issue by JoeJoeYuan** [DeviceFarmer/stf#75]
Hi all, anyone can help me ?
stf version: 3.4.1
stf intergate with ldap, if someone login failed serveral times(maybe input wrong password or account), stf will throw error and other users will disconnect his device, this is error logs:

2020-08-27T06:19:26.581Z WRN/auth-ldap 49 [::ffff:127.0.0.1] Authentication failure for "xxxxxxx"
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 10.122.128.41:389
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
2020-08-27T06:19:32.337Z FTL/cli:local 1 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2020-08-27T06:19:32.337Z INF/cli:local 1 [*] Shutting down all child processes
2020-08-27T06:19:32.340Z INF/util:lifecycle 18 [app001] Winding down for graceful exit
2020-08-27T06:19:32.341Z INF/util:lifecycle 24 [proc001] Winding down for graceful exit
2020-08-27T06:19:32.341Z INF/util:lifecycle 29 [proc002] Winding down for graceful exit
2020-08-27T06:19:32.341Z INF/util:lifecycle 19 [dev001] Winding down for graceful exit
2020-08-27T06:19:32.341Z INF/util:lifecycle 30 [reaper001] Winding down for graceful exit
2020-08-27T06:19:32.341Z INF/util:lifecycle 36 [*] Winding down for graceful exit
2020-08-27T06:19:32.341Z INF/util:lifecycle 54 [*] Winding down for graceful exit
2020-08-27T06:19:32.341Z INF/util:lifecycle 72 [*] Winding down for graceful exit
2020-08-27T06:19:32.344Z WRN/db 24 [proc001] Connection closed
2020-08-27T06:19:32.344Z WRN/db 30 [reaper001] Connection closed
2020-08-27T06:19:32.344Z WRN/db 72 [*] Connection closed
2020-08-27T06:19:32.344Z INF/provider 36 [*] Cleaning up device worker "291bb795dfef"
2020-08-27T06:19:32.344Z WRN/db 54 [*] Connection closed
2020-08-27T06:19:32.344Z INF/provider 36 [*] Cleaning up device worker "1234567890ABCDEF"
2020-08-27T06:19:32.344Z INF/provider 36 [*] Cleaning up device worker "6EJ7N19323006352"
2020-08-27T06:19:32.345Z INF/provider 36 [*] Cleaning up device worker "AQ4TOFJNG6NZK7HA"
2020-08-27T06:19:32.345Z INF/provider 36 [*] Cleaning up device worker "c8cf3640"
2020-08-27T06:19:32.345Z INF/provider 36 [*] Cleaning up device worker "b340d99"
2020-08-27T06:19:32.345Z INF/provider 36 [*] Gracefully killing device worker "291bb795dfef"
2020-08-27T06:19:32.345Z INF/util:lifecycle 67 [*] Winding down for graceful exit

**Comment by JoeJoeYuan** [comment]
Maybe i have found the issue,
LDAP host is HA, one IP can not ping
