### ISSUE TITLE
Missing ARM based docker images on the devicefarmer/stf Dockerhub repository

### ISSUE THREAD

**Issue by jozenstar** [DeviceFarmer/stf#820]
**What is the issue or idea you have?**

There are no ARM based docker images on the devicefarmer/stf Dockerhub repository, although the ARM Dockerfile is present in this github repo.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

Not Applicable

**Please provide the steps to reproduce the issue.**

Open the Dockerhub page https://hub.docker.com/r/devicefarmer/stf/tags -> look for ARM images

**What is the expected behavior?**

ARM based images are present in the Dockerhub repository

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

Not Applicable

**Please run `stf doctor` and paste the output here.**

Not Applicable

**Comment by denis99999** [comment]
@koral-- , do you think we could do that on https://docs.semaphoreci.com/reference/os-ubuntu-images/ubuntu-2204-arm-image ?

**Comment by koral--** [comment]
I'm on it.

**Comment by koral--** [comment]
I've just merged the x86 and arm64 into single Dockerfile and it seems to build without issues with buildx on my machine but the arm build times out on CI.
I need to investigate it.

**Comment by gounthar** [comment]
Thanks! 🙏

**Comment by jozenstar** [comment]
Happy New Year!
Any updates on this issue?

Thank you!

**Comment by gounthar** [comment]
Thanks for the update 🤗

**Comment by jozenstar** [comment]
@koral--
There's just one problem, the only tag that got the arm based docker image built is the `latest`. Can we also get it on the current latest version [3.7.1](https://hub.docker.com/layers/devicefarmer/stf/3.7.1/images/sha256-70b792884f999fee17590b484dc644295dc305460755396cc1263ea4a7c750bd) ?
Thank you!

**Comment by koral--** [comment]
I'll Release the next version ASAP.

**Comment by jozenstar** [comment]
@koral-- Thank you so much for your help!
I'm sorry for bringing it up again, but I think there may be a library missing from the image. On startup I'm getting this error
```
Failed to load addon at /app/node_modules/zeromq/build/linux/arm64/node/127/addon.node: Error: libc.musl-aarch64.so.1: cannot open shared object file: No such file or directory
Error: libc.musl-aarch64.so.1: cannot open shared object file: No such file or directory
    at Object..node (node:internal/modules/cjs/loader:1715:18)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at findAddon (/app/node_modules/zeromq/lib/load-addon.js:29:25)
    at Object.<anonymous> (/app/node_modules/zeromq/lib/load-addon.js:50:15)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
Trying others...
```

Tried on Raspberry Pi and on AWS graviton instances. 
The pod doesn't die though, it does start up, but I'm not sure if it's gonna be actually alright like this

**Comment by koral--** [comment]
Thanks I will Investigate that

**Comment by gounthar** [comment]
musl is the alpine replacement of libc6, more or less. 🤔

**Comment by koral--** [comment]
Let's keep this issue open until stf runs without errors on arm.
After installing musl package the latest error has gone. But instead there is another one, like below.
I'll try to investigate that further.

```
Failed to load addon at /app/node_modules/zeromq/build/linux/arm64/node/127/addon.node: Error: /app/node_modules/zeromq/build/linux/arm64/node/127/addon.node: undefined symbol: __cxa_call_terminate
Error: /app/node_modules/zeromq/build/linux/arm64/node/127/addon.node: undefined symbol: __cxa_call_terminate
    at Object..node (node:internal/modules/cjs/loader:1715:18)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at findAddon (/app/node_modules/zeromq/lib/load-addon.js:29:25)
    at Object.<anonymous> (/app/node_modules/zeromq/lib/load-addon.js:50:15)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
```
